### ISSUE TITLE
Deploying a business network archive to a Hyperledger Fabric V1 requires a lowercase identifier

### ISSUE THREAD

**Issue by Jakeeyturner** [hyperledger/composer#1081]
When deploying a business network archive file to a running Hyperledger Fabric v1 instance using `composer network deploy ...`, the business network identifier must be lowercase. However, when deploying a business network archive file to a Hyperledger Fabric v0.6, the case of the identifier doesn't affect the deployment.
## Context

This was first observed in the related issue #1075 
 
## Expected Behavior

The business network archive file should deploy to a Hyperledger Fabric v1 instance
## Actual Behavior

```
Deploying business network from archive: another-Name.bna
Business network definition:
	Identifier: uppercase-Test@0.0.1
	Description: test

✖ Deploying business network definition. This may take a minute...

Error: Error starting container: API error (500): {"message":"Error parsing reference: \"dev-peer0-uppercase-Test-0.7.2\" is not a valid repository/tag: repository name must be lowercase"}

Command failed
```
## Possible Fix

There will probably need to be changes across the whole Composer stack to remove this issue

## Steps to Reproduce

1. Create BNA with an identifier which has an uppercase letter
2. Try to deploy to a Hyperledger Fabric v1 instance
3. 
4.

## Existing issues

- [ ] [Stack Overflow issues](http://stackoverflow.com/tags/hyperledger-composer)
- [ ] [GitHub Issues](https://github.com/hyperledger/composer/issues)
- [ ] [Rocket Chat history](https://chat.hyperledger.org/channel/composer)

Issue #1075 
## Context

Prevents deploying BNA to a Hyperledger Fabric v1 instance
## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by dselman** [comment]
@davidkel @sstone1 this would be a good one to discuss with the Fabric team. Are there other name restrictions we should be aware of?

**Comment by davidkel** [comment]
@dselman in fact more restrictions have come in through alpha2 which I cater for but didn't wasn't aware of the uppercase limitation, will give it a try on alpha2

**Comment by davidkel** [comment]
The fix for this is now included in the 1.0.0-beta support

**Comment by sstone1** [comment]
@davidkel the fix for this is not right; it's going to lead to confusing code in playground when we deploy a business network thinking that the name is X and infact we then silently turn the name into Y. We will then only be able to discover (using `list`) the business network with the name of Y.

Please can you remove this code and change the business network definition handling code to throw exceptions when the name is not valid with respect to the Hyperledger Fabric restrictions for chaincode IDs. Can you get this done for this Thursdays release please.

**Comment by sstone1** [comment]
Apparently the check belongs in `BusinessNetworkMetadata` in `composer-common`.

**Comment by davidkel** [comment]
@sstone1 ok, will change the code and all the system tests

**Comment by sstone1** [comment]
OK, so since dots `.` are banned in chaincode IDs the restrictions may be a step too far, even for me.
I see two options:

1. We add code to apply the same restrictions to business network names as Hyperledger Fabric has applied to chaincode IDs. Just to recap, the allowed characters are "a-z plus dash and underline only". The lack of capital letters and dots seems overly restrictive to me.
2. We allow a reasonable set of characters in chaincode IDs and then hex encode the business network names (base64 encoding violates the restrictions) for use as the chaincode IDs. This has the effect of rendering the Fabric administrative APIs a bit more difficult to use.

**Comment by davidkel** [comment]
soln now implemented.
