### ISSUE TITLE
Cannot remove an identity from the wallet in the playground

### ISSUE THREAD

**Issue by greg2git** [hyperledger/composer#1109]
An error has occurred
Error: Could not determine the participant for identity 'id'. The identity may be invalid or may have been revoked.

Seems to persist across browser sessions.

I can add a new identity, but cannot remove it from the 'wallet'.

All actions should be reversible, esp when other objects don't persist between sessions.

The added identity cannot be removed:
1. close the browser session
2. load a new scenario

**Comment by sstone1** [comment]
Marking with `design` as we will need designs for removing identities from the wallet, if we don't have them already 😉

**Comment by EdMoffatt** [comment]
There was an existing design for revoking IDs, but obviously we had to tweak the UIs because we were adding in the ID screen before the ID Registry work is available.

In which case, we need to add in the "remove from wallet" functionality, definitely!

The original design, on #533, looked like this:

![image](https://user-images.githubusercontent.com/7454304/26878711-55472754-4b86-11e7-9f25-82f73d6c7f31.png)

The current implementation looks like this:
![image](https://user-images.githubusercontent.com/7454304/26878722-67f8f6d4-4b86-11e7-8c6e-03ebac468370.png)

There's no specific hover behaviour currently, the whole "tile" is just a target to click and "Use this ID".  I suggest we need to bring in a few things from the original design, but slightly modified in light of this not being the ID Registry...

- [ ] Add in the icon that is displayed to show whether an ID in the wallet can be used to issue other IDs (this is just missing for some reason - we don't display any difference between the ones that can and can't do this).  This also needs hover-help to say "This ID can be used to issue other IDs".
- [ ] Add buttons to all but the active ID, styled as in the attached design from #533 , but with the text being "Remove" instead of "Revoke"
- [ ] My feeling is that if we have the word "Remove" there on a button, we should also alter the interaction to "Activate" an ID.  i.e. I would recommend adding a "Use now" button along with the "Remove" one, in case someone is worried about clicking a tile because the only verb they see on there is "Remove" - this way there's something they can actively choose to click, and feel confident it'll have the effect they wanted :)
- [ ] Button ordering, left to right, should be "Use now", "Remove".  The original mockup gives a good indication of positioning and padding!
- [ ] For bonus points, if we could have both these buttons only appear on hover on a tile, that would be extra-ace ;)

**Comment by caroline-church** [comment]
done with bonus points so closing
