### ISSUE TITLE
Adding model file from disc with conflicting namespace will overwrite existing

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#1189]
If I have a BND within playground and add a model file from disc that happens to have the same namespace within it as one already in the BND, the existing model file will be overwritten without warning.

## Context
Adding a model file to an existing BND should not vandalise the existing BND without any form of warning being issued to the user. 

## Expected Behavior
A warning dialog should appear indicating to the user that there is a namespace conflict is present and that continuation will result in the existing model file being replaced. Maybe even give the user an option to "bump" the namespace of the file being imported.

## Actual Behavior
The existing model file is overwritten without warning

## Steps to Reproduce
Start with basic BND, import a model file that has the same namespace declared, but is a different file name to that within the BND. Observe the file swap.

## Context
Was doing some exploratory testing add import of same namespace model file overwrote an existing model file.

## Your Environment
https://composer-playground-unstable.mybluemix.net/editor

**Comment by dselman** [comment]
This is a symptom of #1174 -- once that is fixed I'd expect the ModelManager to throw an exception if you add a ModelFile which has a namespace that already exists.

**Comment by sstone1** [comment]
Needs work to decide what actions the playground offers in this case.

**Comment by shachisharma** [comment]
There are two things: 1. Addition of a model file 2. Updation of a model file. When calling add a model file the intention is to add anew model file. If anyone inputs file with namespace already existing, the composer will throw an error that namespace already exists (PR#1573 has the fix) and retains the file already with it. Whereas, when update model file is called then obvious intention is to update the model file and the composer does the same i.e. updating the model file without an error. The composer in this case throws an  error when namespace does not match. This is expected behavior.

**Comment by shachisharma** [comment]
I checked it in playground on bluemix (the link provided by you) and observed the same behavior. The add model file is called here and hence the silent replacement of file. With the fix of issue #1174 via the PR #1573, this problem will stop occurring.

**Comment by caroline-church** [comment]
The initial problem of the file silently being replaced is now fixed. An error is given when the file is imported and it is not overwritten. While this behavior could be improved the actual bug is fixed so closing
