### ISSUE TITLE
instructions for github authentication are incorrect

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#1210]
When configuring a local environment to authenticate against github with a client id, the instructions are wrong:
 - the folder to place the env file in should be under composer-playground-api
 - the sample .env file contains a comma at the end of a line, which should not be there
 - might help if there was a hint to restart the cli

## Context
When trying to follow the "how to guide" and using the sample file, it is not possible to create the github authentication required to connect

**Comment by sstone1** [comment]
Assuming these instructions:
https://hyperledger.github.io/composer/managing/github-oauth.html

These docs seem to be targeted at a contributor rather than a user who is installing the playground via Docker or npm; no user should be going near composer-playground-api or modifying files inside that module.

**Comment by sstone1** [comment]
@dselman one for the doc review.

**Comment by mbwhite** [comment]
Script to help copy these in https://github.com/mbwhite/documents/blob/master/set-git.sh

**Comment by caroline-church** [comment]
Can we remove the doc then close this as it's no longer relevant

**Comment by sstone1** [comment]
I've done this in one of my pending PRs.

**Comment by caroline-church** [comment]
closing then
