### ISSUE TITLE
Docs: Deploying REST server guide needs improvement

### ISSUE THREAD

**Issue by winslet** [hyperledger/composer#1211]
## Context

This page: https://hyperledger.github.io/composer/integrating/deploying-the-rest-server.html

The document is less of a guide than it needs to be, there should be step by step instructions for getting a REST server up and running. It makes a lot of assumptions about the knowledge of the person going through this page (and their level of expertise in Loopback). 

It also needs to be updated to reflect a v1.0 connection profile as the guide is currently only referencing v0.6 profiles.

It seems as though the content at the bottom of the page "Deploying a persistent and secured REST server using Docker" needs to be moved more to the top as this is closest to the guide as we have, however this errors in use:

<img width="679" alt="image" src="https://user-images.githubusercontent.com/13980028/26922971-ab4cb210-4c38-11e7-8c2f-153cfb0334a6.png">

Further question:

This page: https://hyperledger.github.io/composer/integrating/getting-started-rest-api.html

Seems to have a completely different guide to do the same thing? Could we remove one of these?

--

@caroline-church has also had a large number of community raised problems with this section of our documentation. This is a common problem people are running into.

**Comment by markcastle3** [comment]
@dselman is this something which could be included in next weeks doc reviews ?

**Comment by sstone1** [comment]
As the author, it would be great if these could get tackled by the docs guild.
To answer @winslet's question, the intended flow here is:

1. This is how you generate a REST API (easy)
2. This is how you secure the REST API (medium)
3. This is how you deploy the REST API (hard)

Relevant to this, @caroline-church dealt with a question on RocketChat yesterday where somebody asked how they can configure the REST API with Passport strategy X.

Whilst we maybe need to explain LoopBack and Passport a bit more, we need to make it clear to the user that there is some knowledge of those technologies required in order to use them - we cannot sensibly document and manage extensive tutorials on configuring 300+ different Passport strategies and 20+ different LoopBack connectors.

That being said, maybe we could think about a GitHub Gist style tool (or just Gists!) where users can upload sample working configurations somewhere?

**Comment by sstone1** [comment]
Oh, another question I get on a regular basis is: how can I add API methods to the REST API?

I think this is a question asking how I can avoid having the Composer REST server and a separate REST server for other APIs required by my front end application.

The answer is take the Composer LoopBack connector and the Composer boot scripts and use them to build your own LoopBack application, which you can then freely add APIs into.

Not sure if we want a guide for that just yet but it might appear in the flow at some point.

**Comment by EdProsser** [comment]
Closed by Simon's improvements
