### ISSUE TITLE
Investigate if loading a channel config from orderer could be used to help build a connection profile

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#1265]
The Node SDK provides the ability to download the channel configuration. From that you can obtain the MSP's and Anchor Peers. It looks like you can also query the Peers for information and maybe you can query the Anchor peer for all the other peers it knows about (which is what it's supposed to be able to do)

Armed with this information we could build a configuration but may have to require some further input from the user, for example given the MSPid we can select the correct anchor peer. The user will have to also provide details of the CA. 

What we could have from this is a tool that can build a connection profile given the Orderer, CA and MSPid it could create peer entries.

The node sdk may add the capability to query a peer in your organisation and from that you could determine the orderer. 

Just some of the thoughts I have. It may turn out to be not of any real use, raised only so I didn't forget about it.

**Comment by sstone1** [comment]
@davidkel can you bulk this out with a bit information about what you're trying to achieve? What kind of information is in the channel configuration that we could use in Composer?

**Comment by sstone1** [comment]
With common connection profile support this is no longer something for us to do. Connection management is now 100% the responsibility of Fabric, not us. If the Fabric Node.js SDK can be extended to discover the rest of the info based on a minimal connection profile, great, but lets track that under a JIRA over there rather than in Composer.
