### ISSUE TITLE
IDs screen should indicate which IDs can issue other IDs

### ISSUE THREAD

**Issue by EdMoffatt** [hyperledger/composer#1321]
This is not currently possible apparently :)  But once we get the ID Registry, we should be able to add this in, so adding it as an issue for us to come back to!

This is the icon we want to display on IDs that can issue other IDs:
![image](https://user-images.githubusercontent.com/7454304/27287129-a112c3a0-54fa-11e7-9a92-d2e3fb70931b.png)

Having it in there will be useful for ID management: should help the user avoid accidentally removing all their IDs that can be used to issue others.

**Comment by sstone1** [comment]
This is very difficult to implement; the ability to issue new identities depends on the ACLs in the business network and your Fabric CA roles (which we cannot test for in order to show in the UI). Given that, I don't think we'd be able to do a complete job without significant effort and it doesn't seem worth it.
