### ISSUE TITLE
Build test bananas

### ISSUE THREAD

**Issue by jt-nti** [hyperledger/composer#1358]
There are quite a few .bna files checked in for test purposes

## Context
Binary files in git are not ideal for dealing with updates/merge conflicts

## Expected Behavior
.bna files should be created in a pretest script

## Actual Behavior
.bna files are created manually and checked in

**Comment by mbwhite** [comment]
One easy approach is a simple bash script that can zip the contents; simple effective and can be called from the npm post/pre install.

-ve are this is bash - and windows?  but we've lots of other bash so that 'ship has sailed' really. If we really want to build on windows then suspect we'll need a bash shell anyway.

```
SRCDIR="$(  basename "$0" | sed 's/sh/src/' )"
ARCHIVE="$(  basename "$0" | sed 's/sh/bna/' )"

echo Creating "${ARCHIVE}"
cd "${SRCDIR}"
zip -rq ../"${ARCHIVE}" *
cd - > /dev/null
```


---
Move to use JSZip then that could be done just before the test needs it
-ve JSZip to zip up a folder is bit more code.
-ve it's almost the inverse of the code we're testing - which seems to be wrong.. If there's a bug in usage os JSZip then we might not spot it.

---
Gulp is Javascript and would be simple to call. Just checking if it's possible to call that programmatically.
```
const gulp = require('gulp');
const zip = require('gulp-zip');
 
gulp.task('default', () =>
    gulp.src('src/*')
        .pipe(zip('archive.zip'))
        .pipe(gulp.dest('dist'))
);```

**Comment by jt-nti** [comment]
@mbwhite @sstone1 should definitely do this with JS script. Please don't use gulp! We already have dependencies on jszip so a simple script should suffice. In some places we may be able to just require the sample networks? Although I think there may be issues with versions with that approach.

**Comment by sstone1** [comment]
> -ve are this is bash - and windows? but we've lots of other bash so that 'ship has sailed' really. If we really want to build on windows then suspect we'll need a bash shell anyway.

We actually don't have that much bash in the local developer build (so excluding the Travis automation); the exceptions are the single line installers and system test automation. People shouldn't need bash just to run `npm test` against a bunch of JS code.

**Comment by mbwhite** [comment]
For reference
```'use strict';
const gulp = require('gulp');
const zip = require('gulp-zip');

gulp.task('default', () => {
  console.log('zipping');
    gulp.src('networkname.src/*')
        .pipe(zip('networkname.bna'))
        .pipe(gulp.dest('.'))
      }
);

const result = gulp.start('default');

// this will then have the file zipped
```

**Comment by mbwhite** [comment]
Simplest to use 
* https://www.npmjs.com/package/bauer-zip
* https://www.npmjs.com/package/zip-folder
* https://www.npmjs.com/package/file-zip

**Comment by nklincoln** [comment]
Could we not use our own modules that build BNAs from source files to build the required test BNAs from source files?
