### ISSUE TITLE
Existing panels re-worked for ID Cards

### ISSUE THREAD

**Issue by EdMoffatt** [hyperledger/composer#1413]
Child of #902 

Some updates are needed to the existing screens in light of the introduction of ID Cards.  Here's a quick overview of the changes:

<img width="1113" alt="existing screens" src="https://user-images.githubusercontent.com/7454304/27697675-db4458fa-5cec-11e7-978e-cf125748564d.png">

Other things to note:

- Clicking "Log Out" should return the user to the "My Wallets" screen.
- Clicking "ID Repository (this network)" will take the user to the ID Repository screen.  This is similar to the existing IDs screen in the UI, but should list IDs for the current business network only, with what is displayed subject to ACL rules.  From that screen, the user can issue or revoke IDs if access permits!  We should also indicate which IDs are available for the user to switch to (we'll still support switching between IDs from this screen, for ease of testing ACLs without the need to log out and in repeatedly).
- Changing the edit behaviour to edit a description and a version instead of a name and a version will probably need some styling consideration!

DIFFERENCES FOR THE WEB PLAYGROUND:
- Web Playground will not have a Log Out option.  Since "go to ID registry" is therefore the only action that would be in that dropdown, I'd suggest having a click on the ID name take the user to the ID Registry
- Web Playground still needs the "Get Local Version" link with the Docker-whale icon up in the top-right (so the ID name should be pushed across to the left accordingly in that version)

**Comment by winslet** [comment]
Hifi's!

Key points:
- Left hand top nav has a tooltip which shows the whole name of the business network. This is key for longer names. If we can style it similarly to the tooltip shown on #1412 that would be great.
- The right hand dropdown has a bottom border which is only shown when you have selected the "ID repository" page and are viewing that. Otherwise the background colour is only changed. (see screen 1 vs screen 2 below).

![fabric composer playground define 2 copy 110](https://user-images.githubusercontent.com/13980028/27738089-55c76bfc-5da2-11e7-8916-05825c7242e0.png)
![fabric composer playground define 2 copy 111](https://user-images.githubusercontent.com/13980028/27738093-58823c82-5da2-11e7-86d4-a47636cbf18e.png)


Marketch:
[Composer_Wallet_Dropdown_SW_2.zip](https://github.com/hyperledger/composer/files/1115339/Composer_Wallet_Dropdown_SW_2.zip)

Any questions let me know 🌮

**Comment by nklincoln** [comment]
@EdMoffatt, @Tobias-Hunter, @winslet 
Hi - this would appear to require the pretty "logout" svg, and if desired the "logged in person" icon ... could we have these generated/provided pls?

**Comment by winslet** [comment]
@nklincoln please have a gander at the hifis...they have been removed 👍
