### ISSUE TITLE
Scroll bar overshot in cto and js editors in playground

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#1503]
Scroll bars behave incorrectly when I scroll to the end of the text editor window as shown in these 2 screenshots
at the top of the editor
![image](https://user-images.githubusercontent.com/25582377/27912070-6c6988bc-6253-11e7-912b-8d70db2447bc.png)

when I scroll to the bottom, note how the scroll bar looks.
![image](https://user-images.githubusercontent.com/25582377/27912098-888b8a18-6253-11e7-9b12-176f0e312ba1.png)

**Comment by prasoc** [comment]
I'm working on it.

**Comment by jdp1g09** [comment]
This seems to be caused by the addition of the `margin` to the scroll bars inside CodeMirror. The height of the scroll bar and it's container are being calculated based on the height of the coding area, which is ~16px taller due to the margin (and `box-sizing: border-box`) applied to the scroll bar itself. 

Will investigate further to try and work a way around this.

**Comment by jdp1g09** [comment]
Adding `margin: 0px;` to `.CodeMirror-simplescroll-vertical` solves the height/overflow issue, but now results int he scroll bar being plush against the edge of the editor, which is not as per the design

**Comment by jdp1g09** [comment]
The height of the simplescrollbar is calculated in the JS of CodeMirror and based on the height of the CodeMirror editor, as such, adding padding/margin to scroll bar itself causes it to overscroll/shoot.

Decision made, following consultation with @prasoc to surround the CodeMirror editor with a div. This div will emulate the ".cm-s-default.CodeMirror" styling to mimic the editor stlying and have padding on it, as to simulate the appearance of the scroll bar being inset within the editor.
