### ISSUE TITLE
As a user, I can import an invalid BNA and rectify the errors from the playground

### ISSUE THREAD

**Issue by SweetJenn23** [hyperledger/composer#1543]
## Context

When importing a bna file (stored here: https://github.com/SweetJenn23/BlockchainLab/blob/master/stsa-temperature-part1.bna) quite a few of the 400 users experienced an error saying it detected transactionID when that was no longer in the bna file. This was an inconsistent error. Some people had no issues. It just doesn't make sense why anyone would experience it.

## Expected Behavior

Import successfully with no errors. If there is an error, I would expect to be able to import the code, have the issues highlighted and be able to fix them in the Playground.

## Actual Behavior

![image](https://user-images.githubusercontent.com/14825742/28123028-88348f7e-66e5-11e7-8ba7-33c43040de60.png)

## Possible Fix

No error messages that keep the import from happening. Alternatively, if you do have an error, allow the code to be imported anyway and do not activate the Deploy button until they are resolved. Errors should also be highlighted in the Playground as they usually are during coding.

## Steps to Reproduce

1. Realize this is an inconsistent error and could be related to volume given it occurred when 400 people were doing this all at once against Composer Playground running on Bluemix. However I would estimate the error occurred for 10-20% of the room. 
2. Open Composer Playground on Bluemix: https://composer-playground.mybluemix.net/
3. Download my bna file from: https://github.com/SweetJenn23/BlockchainLab/blob/master/stsa-temperature-part1.bna
4. Import/Replace it into Composer Playground.

## Existing issues

- [ ] [Stack Overflow issues](http://stackoverflow.com/tags/hyperledger-composer)
- [ ] [GitHub Issues](https://github.com/hyperledger/composer/issues)
- [ ] [Rocket Chat history](https://chat.hyperledger.org/channel/composer)

## Your Environment

* Version used: Composer Playground v.9.1 on Bluemix.
* Environment name and version (e.g. Chrome 39, node.js 5.4): Most users were using Firefox or Safari. Unaware of what versions they were on. Seemed to occur the most in Firefox.
* Operating System and version (desktop or mobile): Desktop.
* Link to your project:

**Comment by dwakeman** [comment]
I saw this error o Firefox 52.2.1 on mac.  I get the problem that is being detected, and I also know the bna file provided here should not have had this error, but what about all of my older bna files?  Why not let composer playground import these files with the errors so that I can fix them in composer playground, instead of blocking them from being imported?

**Comment by SweetJenn23** [comment]
To @dwakeman's point, when you're importing a BNA, after it is uploaded, the next button is deploy.
![image](https://user-images.githubusercontent.com/14825742/28124257-c6ba226a-66e8-11e7-979b-0d715a99c194.png)

I would suggest it should be "Import & Replace" instead. That way if there are errors they could be edited in the tooling and then deployed. I'm not sure what the difference in actions behind the button are, but even code that doesn't meet latest standards could be modified to fit them if allowed to import into the tooling.

**Comment by EdMoffatt** [comment]
This is definitely an issue we should fix - thanks for raising!

Button Labelling
I think we labelled it Deploy because it currently does the same as clicking the Deploy button from within the main UI panel, except that it first replaces all the files in the Business Network Definition, *then* it does a Deploy.
As you say, as part of fixing this, we'd probably seek to separate out those 2 steps, so that you just replace the files first, without trying to Deploy.  Therefore the button re-label makes perfect sense!

Behaviour to allow the fix
As you say, we need to allow broken models to be displayed and fixed in Playground.  This is exactly what #1530 is going to introduce!

It sounds like @prasoc is working on things over there, so I'll tag him to take a look at this one too :)

**Comment by caroline-church** [comment]
This should now by possible to implement now playground doesn't throw away invalid changes to the business network
