### ISSUE TITLE
As a Playground user, I would like to have an easier way to add query and acl files to my BND

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#1620]
Currently the playground enables the addition of all supported BND files via a file drag/drop option.

This method is predicated on the fact the file must exist first, and is somewhat of a hindrance with a new starter that wants to add files they do not (yet) have.

It would be better if there were radio options to generate blank readme/acl/query files for inclusion with the BND, which can then be edited by the user.

## Context
Trying to create a BND from "empty network" is frustrating.

**Comment by Tobias-Hunter** [comment]
A README.md & package.json will always be added to a BND. This click-through prototype shows the behaviour for permissions.acl and .qry files.

README.md files will remain to have the same behaviour as they currently do! 

https://xd.adobe.com/view/7a8f76e4-2e07-4db2-8eff-d16b16ad8226/

🍕

**Comment by EdMoffatt** [comment]
Quick note on this one as I'm going through reviewing stuff...

All looks good but maybe the wording on the warning is a bit wonky:

![image](https://user-images.githubusercontent.com/7454304/28719198-eacbc202-73a0-11e7-8d89-12a4f2232db7.png)

I'd suggest

* * *

Current file will be replaced

Your current ACL file will be replaced with the new one you are uploading.

Cancel / Replace

* * *

Just trying to avoid the word "Import" as all the other buttons are labelled "Add", and call it a "File" rather than a "Definition".
