### ISSUE TITLE
Functions inside transactions are called twice

### ISSUE THREAD

**Issue by woutersm** [hyperledger/composer#1703]
## Context

![screen shot 2017-07-31 at 10 04 29](https://user-images.githubusercontent.com/14258120/28768379-b88a89de-75d7-11e7-9836-f856a1649b5b.png)
![screen shot 2017-07-31 at 10 04 16](https://user-images.githubusercontent.com/14258120/28768380-b8a5d46e-75d7-11e7-9519-840596f9af2e.png)

Every function inside a transaction is called twice, the first time like it should. The second time with the transaction object.

## Expected Behavior

Only call the function when it's actually is called.

## Actual Behavior

Functions is called twice, second time with a transaction object.

## Possible Fix

Not a real fix, but adding a comment right underneath the called function will make it called only once:

![screen shot 2017-07-31 at 10 10 41](https://user-images.githubusercontent.com/14258120/28768596-91732ba2-75d8-11e7-9950-136c58e19541.png)
![screen shot 2017-07-31 at 10 10 33](https://user-images.githubusercontent.com/14258120/28768597-9173e9e8-75d8-11e7-99d4-02e1b31b63b0.png)

## Steps to Reproduce

1. See screenshots

## Existing issues

- [ ] [Stack Overflow issues](http://stackoverflow.com/tags/hyperledger-composer)
- [ ] [GitHub Issues](https://github.com/hyperledger/composer/issues)
- [ ] [Rocket Chat history](https://chat.hyperledger.org/channel/composer)

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by davidkel** [comment]
This is down to javascriptparser.findCommentBefore method. It basically starts at the function then works it way up until it finds a comment then assumes that comment applies to it. So if a function doesn't have a comment directly above it, it picks up whatever the previous comment is and in this case it is the transaction processor comment with all it's decorations so gets the same decoration. Putting a comment anywhere after the decorated comment will mean that one is picked up which is why that comment disables the function being called.
The find function needs to stop searching when it reaches the end of the previous statement.
