### ISSUE TITLE
Double labels appeared on the left pane for the online playground

### ISSUE THREAD

**Issue by fenglianxu** [hyperledger/composer#1792]
## Context
There are two trader and two Commodity labels on the left pane after deployed a trade-network model on the online playground. 

## Expected Behavior
The expected behavior should be one label for each before I create a participant and an asset. 

## Steps to Reproduce

1.
2.
3.
4.

## Existing issues

- [ ] [Stack Overflow issues](http://stackoverflow.com/tags/hyperledger-composer)
- [ ] [GitHub Issues](https://github.com/hyperledger/composer/issues)
- [ ] [Rocket Chat history](https://chat.hyperledger.org/channel/composer)

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by fenglianxu** [comment]
This issue only occurs when I import and replace the trade-network.bna.  It works as documented if I simply modify the model, the logic and ACL files with the new contents, and then deploy the business network.

**Comment by davidkel** [comment]
![image](https://user-images.githubusercontent.com/25582377/29074263-8354685a-7c46-11e7-9927-d4e76335b644.png)

**Comment by sstone1** [comment]
These are not labels, they are registry names. The playground removes the namespace from the registry name. These are probably two different registries with two different namespaces, but the same type names (Commodity). This would be visible if the screenshot was bigger.

This is most likely a duplicate of:
Default registries for types that have been removed are not removed on deployment #1796

Without the BNA or full screenshots we cannot prove otherwise.
