### ISSUE TITLE
Default registries for types that have been removed are not removed on deployment

### ISSUE THREAD

**Issue by fenglianxu** [hyperledger/composer#1796]
## Context
On the bluemix playground http://composer-playground-unstable.mybluemix.net/test, after a successful deployment with the new model files, the old participants and the asset names should be removed on the left pane. 

## Steps to Reproduce

1.
2.
3.
4.

## Existing issues

- [ ] [Stack Overflow issues](http://stackoverflow.com/tags/hyperledger-composer)
- [ ] [GitHub Issues](https://github.com/hyperledger/composer/issues)
- [ ] [Rocket Chat history](https://chat.hyperledger.org/channel/composer)

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by fenglianxu** [comment]
![unneededlabels on the left pane](https://user-images.githubusercontent.com/8037138/29076553-c3533808-7c4d-11e7-9112-be7003a49ec6.png)

**Comment by sstone1** [comment]
This was originally done so that we'd preserve data if somebody accidentally renamed a type and blatted all of their _important_ data. I think in the playground case it's more annoying/confusing not to get rid of the old registries and safety isn't so important.

I think we need a "partialResetBusinessNetwork" that just deletes all registries that were created for a type that no longer exists (note, not registries that the user created with addAssetRegistry).

**Comment by EdMoffatt** [comment]
Note from testing with Klajd: it might be possible to put the Historian in a wonky state if it contains transactions relating to assets that are no longer in the model file.  I'll try to recreate this and add more detail.

**Comment by EdMoffatt** [comment]
Yup, definitely an issue with the Historian too.  Steps to recreate...

1. Import basic-sample-network
2. Go to Test tab
3. Create a SampleParticipant
4. Create a SampleAsset owned by that SampleParticipant
5. Submit a SampleTransaction to update the value of the SampleAsset
6. Head back to the Define tab, remove all mention of SampleAsset (e.g. replace it with AnotherAsset).  Update the deployed business network.
7. Head back to the Test tab and access the SampleAsset Registry.  You get the error as you'd expect (that this issue is originally talking about):
![image](https://user-images.githubusercontent.com/7454304/31281633-f5ec862e-aaa7-11e7-8c81-3a0ab3d5bb61.png)
8. Now try looking at the Historian.  There's also an error here, and the UI fails to load in most of the history:
![image](https://user-images.githubusercontent.com/7454304/31281711-22d55332-aaa8-11e7-91ff-88f9756d443a.png)

**Comment by caroline-church** [comment]
This has been fixed by #2485 so closing
