### ISSUE TITLE
A restart of Hyperledger Fabric is needed when updating Hyperledger Composer

### ISSUE THREAD

**Issue by jexus6** [hyperledger/composer#1863]
## Context
After update Hyperledger Composer, a version error is shown

## Expected Behavior
After update Hyperledger Composer the new version works on the running hyperledger fabric instance or the documentation must tell that you have to restartHyperledger Fabric:
stopFabric.sh, teardownFabric.sh and startFabric.sh

## Actual Behavior
Executing:
composer network ping -n <<network_name>> -p hlfv1 -i admin -s adminpw
gives back  the following error:
Error: Error trying to ping. Error: Composer runtime (0.8.0) is not compatible with client (0.11.0)
Command failed
And  versions are the same:
composer -v
composer-cli                   v0.11.0
composer-admin            v0.11.0
composer-client              v0.11.0
composer-common        v0.11.0
composer-runtime-hlf           v0.11.0
composer-runtime-hlfv1         v0.11.0v0.11.0

## Steps to Reproduce

1.Update Hyperledger Composer to a new version from older one
2. Do something with composer like: composer network ping -n <<network_name>> -p hlfv1 -i admin -s adminpw
3.
4.

## Existing issues

- [x] [Stack Overflow issues](http://stackoverflow.com/tags/hyperledger-composer)
- [ ] [GitHub Issues](https://github.com/hyperledger/composer/issues)
- [ ] [Rocket Chat history](https://chat.hyperledger.org/channel/composer)

## Your Environment

* Version used:
composer -v
composer-cli                   v0.11.0
composer-admin            v0.11.0
composer-client              v0.11.0
composer-common        v0.11.0
composer-runtime-hlf           v0.11.0
composer-runtime-hlfv1         v0.11.0v0.11.0
* Environment name and version (e.g. Chrome 39, node.js 5.4):
node.js v6.11.0
* Operating System and version (desktop or mobile): 
Desktop
* Link to your project:

**Comment by sstone1** [comment]
@jexus6 this is working as designed. Hyperledger Composer follows the standard semantic versioning rules (http://semver.org), including for communications between the runtime (smart contract) and client. In your case, the client @ v0.11.0 cannot communicate with the runtime @ v0.8.0 - the client to runtime protocol has drastically changed since then. We're interested in being able to upgrade the runtime to later versions, and infact you can do this today to upgrade between patch levels (v0.11.1 to v0.11.2) using `composer network upgrade` - but not major or minor levels yet.

**Comment by jexus6** [comment]
I'm sorry, I think I didn't express myself clearly enough:
I had the version  0.8.0 and then I updated to 0.11.0 verison. Once everything was updated to 0.11.0 (client and runtime of composer) I had that error. 
How can you get rid of that error? restarting Hyperledger Fabric.

**Comment by jexus6** [comment]
I thik this issue sould be open.
