### ISSUE TITLE
As a playground user i can see reasons why my inputs are invalid

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#1875]
In various locations within Playground, buttons are disabled due to missing or invalid input. As a user of Playground, it would be useful to know what rules I am violating.

A named instance is during the creation of a new business network (per PR #1846), where a user enters the name of a business network ... this is restricted to lowercase and no white space. At the moment we can only indicate an error via a border colouring change ... but it is left to the user to determine what the constraint violation is. We could be more helpful here, though in this particular case the window is rather busy ... where could we place the warning?

## Context
Trying to deploy a new network, needed to figure out naming convention without guidance

## Expected Behavior
I should be told what to fix 

## Actual Behavior
Need to experiment

## Possible Fix
Show an indicator ... somewhere!

**Comment by EdMoffatt** [comment]
Just noting down some thoughts - since the styling of these inputs reminds me of Watson Conversation, capturing how it's done in that UI as inspiration:

![image](https://user-images.githubusercontent.com/7454304/29313526-726df896-81b2-11e7-9b36-d2ad55501c63.png)

![image](https://user-images.githubusercontent.com/7454304/29313538-8242f5f0-81b2-11e7-8e55-566cf263aa20.png)
("Learn More" links to their documentation page about intents in this instance)

**Comment by sstone1** [comment]
As far as I know, nobody is working on this at the moment or planning to work on it, so closing. 
If somebody wishes to work on this in the future, then please reopen this issue or open a new issue.
