### ISSUE TITLE
Historian UI needs redesigning due to cramped layout and ordering/naming of columns

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#1895]
## Context

Pretty cramped in here:
![screen shot 2017-08-17 at 11 42 39](https://user-images.githubusercontent.com/7118158/29408785-79713fd2-8341-11e7-8fc1-91c1459b6d38.png)

Ordering and naming of columns in the Playground Historian registry is a little confusing. “ID” should be called “Transaction ID” to distinguish from “Participant ID”. I also suggest reordering the columns so that the most important information is first (suggest Timestamp).
Particularly, I’m not sure what the relevance of transaction ID is in this view. I would move it after ‘Transaction Type” or remove it entirely.

Combining with #1818 as we don't need two different bugs for this.

## Expected Behavior

Important content such as action link should probably not be shortened.

## Actual Behavior

Important content such as action link is shortened.

## Possible Fix

Use smaller font size?

## Steps to Reproduce

1.
2.
3.
4.

## Existing issues

- [ ] [Stack Overflow issues](http://stackoverflow.com/tags/hyperledger-composer)
- [ ] [GitHub Issues](https://github.com/hyperledger/composer/issues)
- [ ] [Rocket Chat history](https://chat.hyperledger.org/channel/composer)

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4): Safari
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by neeravarora** [comment]
@sstone1 just a suggestion can we give tooltip feaure there .

**Comment by sstone1** [comment]
@neeravarora I'll defer the solution to our UX/UI designer @winslet who will know exactly how we should be handling this issue 👍

**Comment by sstone1** [comment]
@winslet please consider this one at the same time:
Ordering and Naming of columns in Historian is confusing #1818

**Comment by neeravarora** [comment]
@sstone1 sure

**Comment by EdMoffatt** [comment]
Ok, looking through the issues on this one, and also I swear there was one about the fact it says "Participant ID" which is actually the name of the Participant that owns the ID used, and does not tell you the ID (so if one participant has 2 IDs, you'd not see from this table which of them was doing the transactions)...  Here's a bash at something we could do.

### Old:
![image](https://user-images.githubusercontent.com/7454304/31615513-b25525ec-b281-11e7-9078-efe62ae57bdb.png)

### Suggested:
![image](https://user-images.githubusercontent.com/7454304/31615734-756b2662-b282-11e7-8f38-299f8b58a3ac.png)

### What's changed:
- Actually putting "Historian" into the Left-hand nav to match the page title!
- Show date *and* time (instead of just time), and have this as the first column.
- Instead of trying to display the full "Transaction type" (which I've re-labelled "Entry type", because having a Transaction as a concept in the models and then referring to things the user didn't model as transactions in the UI too just bugs me) and then ending up truncating the most important part (the last bit!) if we have to truncate...  We display *just* the most important part (not fully qualified) and provide the fully qualified info on hover.
- "Participant ID" column becomes "Participant, ID", and displays both the Participant and the ID that was used.
- Not related to the data in the table, but can we also please fix the fact that the window in which rows will display ends way above the bottom of that part of the UI (it could run all the way down to the line above the Legal, GitHub etc. links ideally).

What are people's thoughts on this?
I'll also tag @nklincoln for thoughts on what sort of size this work would be!

**Comment by sstone1** [comment]
@EdMoffatt looks good - much better today - one thing from me:

> "Participant ID" column becomes "Participant, ID", and displays both the Participant and the ID that was used.

I think we should just show the participant type and identifier, with the fully qualified type being available on hover over. ID (or rather identity) is more of an "advanced" thing you want to see - OK so it was this participant, which of their identities did they use?

**Comment by mbwhite** [comment]
@EdMoffatt    the only thing that I find 'odd' is that the Historian is listed under Transactions.
Doesn't seem to match somehow... Historian has HistorianRecords that link to transactions. 

Plus if the playground every displayed the transaction Registries they would go under Transactions.

**Comment by EdMoffatt** [comment]
@mbwhite - my thinking for leaving that heading in there was that the user has modelled Assets, Participants and Transactions, then they head over to the test tab and that's the place where they find their Transactions.
That said, it's *also* the place where they find their Events, which are also part of the modelling language 🤔 

What would the header be?  Having a header of "Historian" and then a page under it called "Historian" would look pretty weird...  Any better suggestions that "Transactions"?

**Comment by EdMoffatt** [comment]
@sstone1 - sounds like a good idea :)  I'll just let the discussion about the Historian nav heading play out, then crank another iteration of the design with that factored in!

**Comment by mbwhite** [comment]
@EdMoffatt  honestly I don't really know... Maybe it should be 'HistorianRecords' rather than 'Historian'

**Comment by EdMoffatt** [comment]
How would you feel about "Historian" and "All Records"?

**Comment by EdMoffatt** [comment]
Ok, refresh of that design:
![image](https://user-images.githubusercontent.com/7454304/31672545-c657d62e-b354-11e7-8a0e-e118d4057a42.png)

I was also having a think about responsiveness...  Now this isn't strictly accurate to a Sam W level, but I was thinking we could have the View Details column at a fixed width, and then have the other 3 split the remaining width evenly between them (with some padding):
![image](https://user-images.githubusercontent.com/7454304/31672597-edbc72e2-b354-11e7-8db7-23a76455ca17.png)

**Comment by sstone1** [comment]
I love it but as discussed with Ed, I wonder if we could save some space by reducing the `view record` text into or turning it into an icon.

**Comment by EdMoffatt** [comment]
I'm not super keen on replacing text with icons if it's avoidable.  I think we'll already be doing a lot better at the resolution Simon raised as an issue with this new layout.  Excuse the dodgy, hasty mockup, but it'll be something like...

![image](https://user-images.githubusercontent.com/7454304/31812955-8e99800a-b57c-11e7-82fc-3e2e84b360fe.png)

(Obviously some of those things may truncate but then we have the hover there).

I'd be happy with this as a first step improvement to fix the main problem, and then perhaps we could look at adding the responsiveness whereby if you reduce the width beyond a certain point, *then* we replace with an icon.  We're kind of approaching a mobile resolution at that point tho, and Composer on mobile seems like another whole battle we might not want to get into just yet ;D

**Comment by EdMoffatt** [comment]
Assigning @caroline-church and @nklincoln , as this one needs sizing and assigning to figure out whether we can get it closed out next week :)
