### ISSUE TITLE
As a Playground user,  I want to a deploy/publish my Hyperledger app on a server, so that the API's can be consumed by a external application.

### ISSUE THREAD

**Issue by MohitSuhane** [hyperledger/composer#1912]
## Use Case
1. User develop a Hyperledger app using composer playground.
2. User want to deploy the application to a server.
3. Later, User creates a external application where he/she wants to consume these API's.

## Context
The composer playground allow user to download the .bna file. But as a user I also want a functionality to publish/deploy .bna file to a server.

## Expected Behavior
1. Add a "Publish" button . On click of publish button, the .bna file should be  published to a server.
2. Build a new Publisher/Server application and add it to packages directory of composer, which will help to host the hyperledger application.

## Actual Behavior
Currently Playground has an Export button to download .bna file.

## Possible Fix
Composer-Playground:
1. A new "Publish" button will be added below "export" button in the editor view.
2. On click of this button the .bna file will be published to the Publisher/Server application that is newly added to the composer repository.

Publisher/Server:
1. A node server application, that will receive a file from playground.
2. Server will deploy the .bna file and host the application.
3. Once the application is hosted an API endpoint will be generated as a response. 
4. Those API's can be consumed by any application to build functionality on top of it.

**Comment by sstone1** [comment]
@MohitSuhane what you call "publish", we call "import" - you can currently "import" a BNA into the playground, at which point it will be deployed to the currently selected connection profile.

Next weeks release will introduce ID cards, a new feature which will make this process of deploying a new business network to a Blockchain platform (Hyperledger Fabric) much more obvious.

I'm going to close this as "fixed in next release" - please check out ID cards next week!
