### ISSUE TITLE
Restarting the network with composer.sh causes connection error when using again?

### ISSUE THREAD

**Issue by mudlee** [hyperledger/composer#2075]
I installed the latest Composer locally on a OSX and then started with the composer.sh. It works fine, can do anything what I want. After restarting the composer however it fails to connect again.

It says: 
`Error: Failed to load connection profile ce0f135f7a63287ab86f0dcc0732e185c1a60d62-hlfabric. Error was Error: ENOENT: no such file or directory, open '/home/composer/.composer-connection-profiles/ce0f135f7a63287ab86f0dcc0732e185c1a60d62-hlfabric/connection.json'`

Also, I deploy new business network, I got the same error.

If I export the admin ID card before the restart and after the restart I remport it and try to connect with it, it says:
`Error: Error trying to ping. Error: Error trying to query chaincode. Error: could not find chaincode with name 't2' - make sure the chaincode t2 has been successfully instantiated and try again`

## Expected Behavior
Access the previously deployed network as before the restart.

## Actual Behavior
It says an error.

## Steps to Reproduce
1. Install composer stuff.
2. Start Composer with composer.sh
3. Using the Angular UI deploy a sample network (your wallet now have an admin ID to the network)
4. Restart the Composer stuff with running composer.sh again
5. Try to use admin ID to login again.

## Context
I'm trying to use the same network I deployed before.

## Your Environment

* Version used: latest
* Environment name and version (e.g. Chrome 39, node.js 5.4): latest chrome, latest node
* Operating System and version (desktop or mobile):latest osx

**Comment by mudlee** [comment]
Note: the new composer (0.12.1) just came out, tried it, same happens.

**Comment by mudlee** [comment]
Closing this, composer.sh drops all docker containers thats why I lose chain data

**Comment by hgambaro76** [comment]
mudlee. I am having the same problem. Could you share with me how do you fix it? Thanks. Hernan

**Comment by mudlee** [comment]
as I wrote, rerunning composer.sh drops all docker containers, so data we created will be lost. Its not about composer but how docker works

**Comment by KaiNik98** [comment]
So, could you say how exactly your solution worked then? I am still a bit confused. How can I recreate this data then, so that it can be used again? Thx

**Comment by mudlee** [comment]
The thing is, when its restarted, it drops the docker containers it uses, so data was in the docker is lost. I dont remember what did I do, because I abandoned HL. So I might did nothing, sorry.

**Comment by cpapantoniou** [comment]
Im experiencing the same issue on my Mac Os Dev Environment. After restarting the Fabric, I can not access my business network because of the broken chaincode.
Any suggestions how to stop and start the fabric without loosing the connection between the Fabric Business Network and Docker?

**Comment by bsanil68** [comment]
I  am facing the  same issue   on a  Google  VPC where  we  have  a  enterprise  topology  of fabric  ....
Happens  even if i stop and start  the fabric topology  ...  w e have a  enterprise  connection and  it had  previously installed  the  network on the  peers  ....

**Comment by lfscoelho** [comment]
I assume you need to keep a backup of the latest network file  "tutorial-network.bna" and you need to re-install it again, so you will get all your network configs back. 
Anyways, it's not great. If some disruption occurs in a production environment, then your're done with your blockchain.... must be some other way to bring an existing network up and running.
The worst part is that Hyperledger composer is able to see the network card, but can't run because can't find the chaincode! Grrrrrrrrrrr!!!  
So bad

**Comment by cpapantoniou** [comment]
Here is the right approach in order to Start and Stop Fabric without having an issue with the chain code.
--------------
cd /.../"fabric-folder"/fabric-scripts/hlfv1/composer
docker-compose start
composer-playground
docker-compose stop

-------------------
 The point here is to start and stop the docker using the steps above. In this case you don't loose the chaincode.
