### ISSUE TITLE
Created a User identity from composer CLI , unable to login from playground

### ISSUE THREAD

**Issue by mandeepsinghey** [hyperledger/composer#2108]
**Created a User identity from composer CLI , unable to login from playground**

## Context
Provide a more detailed introduction to the issue itself, and why you consider it to be a bug

## Expected Behavior
Must be able to login from playground for identities created from CLI

## Actual Behavior
Not able to login from playground

## Steps to Reproduce
composer participant add -p hlfv1 -n 'my-network' -i admin -s adminpw -d '{"$class":"org.acme.mynetwork.Trader","tradeId":"Trader3","firstName":"JENNIFER","lastName":"JONES"}'

composer identity issue -p hlfv1 -n 'my-network' -i admin -s adminpw -u Trader3 -a "resource:rg.acme.mynetwork.Trader#Trader3"

An identity was issued to the participant 'resource:org.acme.mynetwork.Trader#Trader3'
The participant can now connect to the business network with the following details:
  userID = Trader3
  userSecret = GENERATED SECRET

composer network ping -p hlfv1 -n 'my-network' -i Trader3 -s GENERATED SECRET

## Context
Trying to provide a id to user who can login form playground on network

## Your Environment

* Version used:Playground version 12
*** Environment name and version** 
Operating Systems: Ubuntu Linux 14.04 / 16.04 LTS (both 64-bit), or Mac OS 10.12
Docker Engine: Version 17.03 or higher
Docker-Compose: Version 1.8 or higher
Node: 6.x (note version 7 is not supported)
npm: v3.x or v5.x
git: 2.9.x or higher
Python: 2.7.x.

* Operating System and version (desktop or mobile):UBUNTU16.04 LTS desktop

**Comment by mudlee** [comment]
Same, just reported a similar one. It fails only for me, if I use that identity to send a transaction first. See this: [https://github.com/hyperledger/composer/issues/2117](https://github.com/hyperledger/composer/issues/2117)

**Comment by sstone1** [comment]
@mandeepsinghey @mudlee this is working as designed; you should only enroll an identity once. Here's a copy and paste of my answer from issue #1761.

We see a lot of misunderstanding around the enrollment secret - it might not be the case here - but in general, a lot of users end up treating the generated enrollment secret as a password. The enrollment secret is a token that you can pass to the Fabric CA in exchange for an enrollment certificate. The enrollment certificate is used to sign transactions and is used to identify you on the Blockchain.

We need to guide our users towards proper management of their enrollment certificates, and we will do that by restricting the default number of maximum enrollments to 1 in issue #2056. This was the behaviour in Fabric v0.6, and the behaviour was much more indicative as to what was going on under the covers. I am asking jt-nti to add a warning message in playground around this behaviour as well.

After users have enrolled - exchanged the enrollment secret for an enrollment certificate - they will need to manage that enrollment certificate and move it between the wallets (via identity export & import APIs and CLIs we are building) in order to use it across multiple systems.
