### ISSUE TITLE
Unable to Import ID Card in Hyperledger Playground Online

### ISSUE THREAD

**Issue by AtreyeeBiswas** [hyperledger/composer#2114]
I am new to Hyperledger Playground and I am working online. I deployed my network, created ID Card but some options are missing  - I am unable to import ID Cards in Hyperledger Playground online. 
![image](https://user-images.githubusercontent.com/31063562/30322831-6bde8a04-97d8-11e7-8943-18ed99604fe9.png)

The Import / Create ID option as per the available snapshots is not available while I am opening the playground in my browser.

Using Win 10 64 Bit System, Google Chrome and IE 11.
Please Help me, am I missing something ?

**Comment by sstone1** [comment]
@AtreyeeBiswas those options are not available on the online playground: 
http://composer-playground.mybluemix.net

This is because the online playground does not support connections to Hyperledger Fabric v1.0. Instead, only the web browser connection profile is supported, which simulates a real Blockchain and persists all data in the local storage of your web browser.

If you want to work with a real Hyperledger Fabric v1.0 and ID cards, please follow the instructions here to install the playground locally:
https://hyperledger.github.io/composer/installing/using-playground-locally.html
