### ISSUE TITLE
Issued identity with cli cannot be used in Composer after any transaction sent

### ISSUE THREAD

**Issue by mudlee** [hyperledger/composer#2117]
If I issue an identity with cli and then use that identity to send a transaction, then the identity cannot be used on the composer.

**Error: Error trying to ping. Error: Error trying to query chaincode. Error: Missing "chaincodeId" parameter in the proposal request**

## Steps to Reproduce
1. Create two participants with cli
2. Issue an identity for both with cli
3. Create an ID card for participant1 on the composer UI and login, it works.
4. Send any transaction with participant2 with cli
5. Create an ID card for participant2 on the composer UI and try to login. **It wont work!**

## Note
Despite it fails using composer UI, it works if I try to ping the network with participant2's identity:
```
myhost:~/P/o/h/n/lawyer-network:master$ composer network ping -p hlfv1 -i Lawyer2 -s DxfcaWxCERNA -n lawyer-network
The connection to the network was successfully tested: lawyer-network
	version: 0.12.1
	participant: com.intermetto.Member#id:lawyer2

Command succeeded
```

**Comment by sstone1** [comment]
@mudlee this is working as designed; you should only enroll an identity once. Here's a copy and paste of my answer from issue #1761.

We see a lot of misunderstanding around the enrollment secret - it might not be the case here - but in general, a lot of users end up treating the generated enrollment secret as a password. The enrollment secret is a token that you can pass to the Fabric CA in exchange for an enrollment certificate. The enrollment certificate is used to sign transactions and is used to identify you on the Blockchain.

We need to guide our users towards proper management of their enrollment certificates, and we will do that by restricting the default number of maximum enrollments to 1 in issue #2056. This was the behaviour in Fabric v0.6, and the behaviour was much more indicative as to what was going on under the covers. I am asking jt-nti to add a warning message in playground around this behaviour as well.

After users have enrolled - exchanged the enrollment secret for an enrollment certificate - they will need to manage that enrollment certificate and move it between the wallets (via identity export & import APIs and CLIs we are building) in order to use it across multiple systems.

**Comment by mudlee** [comment]
I see, thank you for your detailed answer
