### ISSUE TITLE
As a contributor I have documentation of standards and expectactions to guide me

### ISSUE THREAD

**Issue by dselman** [hyperledger/composer#213]
The contributor guide needs to be updated:
https://github.com/fabric-composer/fabric-composer/blob/master/CONTRIBUTING.md

**Comment by EdMoffatt** [comment]
As part of a GitHub "lets get super organised" drive...

- Leaving this one as an Issue, as it doesn't seem large enough to convert to an Epic and split down
- Un-assigning Simon, since he's on holiday and shouldn't be working ;)  This will mean it appears as open for anyone to pick up
- Changing to the Playback 4 milestone, so that we can track the current playback tasks in ZenHub (ZenHub doesn't play so well with Projects!)

**Comment by nklincoln** [comment]
Initial delivery complete, though I believe there is scope for improvement in the writing style/quality. It is possible that we would prefer to use the git wiki to document all the process instead of using a set of md files. 

We should also look into breaking out contribution aspects that are scoped to UI/Runtime/Doc
