### ISSUE TITLE
 Improve performance of queries

### ISSUE THREAD

**Issue by rmoedt** [hyperledger/composer#2190]
## Context
When we sent a query from a node js application to composer it takes long time before we get a result back. During some tests we sent a query 41 times. The average time it took for a query to give back a result was 2.7 seconds. The fastest returned in 1.4 seconds and the slowest took 5.0 seconds.

At the time there where only 3 assets stored in the ledger.

## Your Environment
Tested it with Composer 0.12.

## More context
All test running locally on a MacBook Pro 15”
1 peer
2 channels
each channel has three assets stored on it
node.js application connecting to composer through the composer-client package

When we sent 2 queries simultaneously (1 to each channel):
Average time: 968 ms
Min time: 679 ms
Max time: 1267 ms

When we sent 10 queries simultaneously (5 to each channel):
Average time: 1611 ms
Min time: 1000 ms
Max time: 3658 ms

When we sent 14 queries simultaneously (7 to each channel):
Average time: 2373 ms
Min time: 851 ms
Max time: 4030 ms

Currently on our application we have one screen that requires all these 7 queries to be sent to each channel

We are executing the query from our node.js application like this:
const composerQuery = await businessNetworkHandler.connection.buildQuery(query);
const result = await businessNetworkHandler.connection.query(composerQuery);

We build the queries on our node.js side. Example of a query we use:

Query {
  identifier: 'SELECT org.example.mynetwork.nameOfAsset ' +
              'WHERE ((attributeA == \’someValue\’ OR attributeB == \’someOthervalue\’) ' +
              'AND (attributeC != \’anotherValue\’)) LIMIT 0'
}

**Comment by nklincoln** [comment]
Hi,
Could you give a little more information on the manner in which you invoked the query? For instance, were you invoking directly with the Composer API, going through a REST server etc?
Thanks

**Comment by rmoedt** [comment]
Update the ticket with more background info and more test results

**Comment by nklincoln** [comment]
Hi,
Just to let you know that this is still being looked at. I have been able to recreate the decrease in performance for multiple concurrent queries and increasing number of assets. I have slightly different results to you, though that due to platform differences ... however the trend is the same: more concurrent requests and/or more assets does degrade the response times performing a query.

At the moment logging is indicating that we are spending upwards of 70% of the time waiting for a response from Fabric - we are looking into this some more

**Comment by rmoedt** [comment]
Thnx for the update. I need to verify this for myself but I also heard had having acl's has an impact on the times. When the composer acl's were disabled the queries were a lot faster.

**Comment by nklincoln** [comment]
Hi - do you know if the ALCs had any references within them?

**Comment by celder628** [comment]
The query as described above is not a Fabric formatted query.  I am assuming another layer processes the query.   Would it be possible to see the query that is actually passed into Fabric?

**Comment by nklincoln** [comment]
@celder628 - the posted query is in Composer format, this is converted into a query that can be run in Fabric against CouchDB, for instance

```
Query {
identifier: 'SELECT org.acme.sample.SampleAsset ' +
'WHERE ((assetId == _$inputValue))'
}
```

maps through to 

```
{"selector":
 {
  "$class":"org.acme.sample.SampleAsset",
  "$registryType":"Asset",
  "$registryId":"org.acme.sample.SampleAsset",
  "assetId":{"$eq":"8"}
 }
}
```

**Comment by nklincoln** [comment]
@rmoedt 

I've performed some deeper analysis here and it would appear that the bottle neck is occurring within CouchDB (CDB).

Based on a 'reduced' test scenario, with 8k assets and 10 concurrent requests, CDB was spending between 8 and 9 seconds to provide a response. By indexing the database, it was possible to reduce this response time to between 3 and 12 ms ... quite a difference.

At the moment it is not possible to create an index in CDB via chaincode (and therefore through Composer) however, since if an index exists in CDB, and the query you pass contains the parameters that map to that index, CDB will use the index. This leads to the possibility to create the index manually and use querying that also provides the required parameters. Note that the index must be created on each CDB that exists within the network.

The best way to describe this is through an example, so the following will assume:
 - A singe CDB instance for a peer, that may be accessed via `http://127.0.0.1:5984`
 - A business network is deployed to the channel `mychannel`, and named `basic-sample-network`
 - A single query 

The command `curl -X GET http://127.0.0.1:5984/_all_dbs` should confirm that the channel does in fact exist as it will return all dbs stored on CDB (the channel being one of those).

The indexing must be created based upon the 'selector' that is generated from the query being run: in the example I provide above there are 4 selectors (class, registryType, registryId, assetId), so I will use these in the continuing example.

Create an index via curl: `curl -i -g -X POST -H 'Content-Type: application/json' -d '{"index":{"fields":
["data.$class","data.$registryType","data.$registryId","data.assetId"]},"name":"asset","ddoc":"assetDoc","type":"json"}' http://127.0.0.1:5984/mychannel/_index`

The above will create an index with the design document names assetDoc and the index named asset, which expects to be passed class, registryType, registryId and assetId. Note that 'data' is prepended to there, the reason for this, it that is it is how the document is stored in CDB. If you are unsure of the structure, you can check though using Fauxton (http://127.0.0.1:5984/_utils/#/_all_dbs)

Using `_explain`, it is possible to check that an example query uses the index:
`curl -i -g -X POST -H 'Content-Type: application/json' -d '{"selector":{"data.$class":"org.acme.sample.SampleAsset","data.$registryType":"Asset","data.$registryId":"org.acme.sample.SampleAsset", "data.assetId":"1"}}' http://127.0.0.1:5984/mychannel/_explain`

The return statement should contain the "ddoc" created in the index: `{"dbname":"mychannel","index":{"ddoc":"_design/assetDoc","name":"asset","type":"json" . ... ` If it is not there, then an 'allDocs' query is being performed and not an index based query.

At this point it is possible to run the query directly through curl (this is of limited use unless you want to run a series of queries and inspect the completion time in the couchdb.log file).

So in theory, if you have mapped the query to the index correctly, all future queries will use the indexing and so be more performant.

**Comment by rmoedt** [comment]
I've tested adding of the indexes before doing the queries. In the scenario where we have just 3 assets strored on 1 channel the queries are about 30% faster with an average of 1.6s. However when we add 100 assets to a channel the time for certain queries goes up to 25s. Adding 500 assets to a channel causes the requests to time out. 

Can you explain how you are able to run queries on a channel with 8k assets? Are you querying couchdb directly or are you going through composer?

**Comment by nklincoln** [comment]
@rmoedt I would have expected that you would have observed a faster throughput. It might be worth looking in the couchDB logs to see just how long the queries are taking - the logs may be accessed through logging into the couchDB docker image and looking under the logs directory - queries are invoked through a POST call and the execution duration is the final number in ms, for instance:

`[notice] 2017-10-09T15:00:47.020326Z nonode@nohost <0.11220.7> 69c37cceb0 127.0.0.1:5984 ***.**.0.1 undefined POST /mychannel/_find 200 ok 12`

Shows that the POST (query) to mychannel took 12ms to complete.

I can confirm that I am going through the Composer API to a Fabric instance on Docker that had been pre-loaded with 8k assets. 

How many concurrent requests were you running in your example?
