### ISSUE TITLE
Investigate possible tweaks to ID Cards

### ISSUE THREAD

**Issue by EdMoffatt** [hyperledger/composer#2256]
As discussed on today's community call, this is an issue to discuss further!

[Business Network Cards Ideas.pdf](https://github.com/hyperledger/composer/files/1341612/Business.Network.Cards.Ideas.pdf)

These are a few ideas for how we could tweak ID Cards (or as they could come to be better known, Business Network Cards) - for now this issue is to capture community discussion - will close and split out when we have decided work to be done.

**Comment by jt-nti** [comment]
Definitely think rebranding (idea 2) is worth doing. 'Business Networks' and 'Business Network Cards' make sense to me but are there any other contenders?

I like the 'Get Started' card (idea 1) but I feel like it's starting to blur with the 'Let's Blockchain!' splash screen which I seem to spend my life clicking through. Could the 'Get Started' flow hang off that splash screen instead? That would make the splash screen a bit more useful. Alternatively, is the splash screen even necessary if there's a nice welcoming way in to your first business network waiting on arrival?

I quite like the breadcrumb style link to get back to the business network screen (idea 3) but you do the lose any clue which connection profile you're using. Is that important? Not sure (see below!)

+1 for keeping a 'My Business Networks' item on the dropdown (idea 3)

I do think it would be good to have a more obvious association between cards for the same business network (idea 4). Perhaps switching to business network as the primary grouping, i.e. instead of connection profile, would fit well with the rebranding? Alternatively, or maybe in combination with other methods of association, maybe we could use identicons based on business network as the background of the user's initials? (There was a suggestion of using 'profile pictures' here, but I don't really understand why someone would want to do that when the cards are unlikely to be used to identify someone else.)
