### ISSUE TITLE
composer archive create fails for business networks with external model dependancies

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#2300]
Currently the CLI command `composer archive create` is not capable of coping with npm hosted model files, and fails with a missing dependancy path.

recreate:
- obtain a business network with an npm dependancy (go to online playground and download the animal-network.bna)
- extract contents to a folder and run the archive create command against it
- observe error of missing model file

**Comment by davidkel** [comment]
@nklincoln setting this to be a P2 for now if you want to change it please feel free to drop it to P3 if you think this isn't a big issue.

**Comment by sstone1** [comment]
As much as I'd love to treat this as a quick bug fix, there are implications here around supporting external dependencies in playground etc - we're better off thinking about how we really want it to work and then doing that as a user story.

**Comment by mbwhite** [comment]
Looked into this, and the problem is part user-error part code-bug.
The source from which Nick was working is an exploded BNA fail. This has all the model, files, queries etc. in one location. Therefore the correct syntax to pull this back into a BNA file is

```
composer archive create --sourceType dir --sourceName . --archive new.bna
```
All the dependancies have been resolved when the BNA was first produced. The reason the archve create has problems is that the package.json is the package json from original Network git repo. This does have dependancies in it. 

The code-bug therefore is that it the archive create should have simplified the package.json.

I humbly submit @sstone1  that this is a bug.
