### ISSUE TITLE
V 0.14 Admin@org1.example.com is not registered

### ISSUE THREAD

**Issue by rddill-IBM** [hyperledger/composer#2369]
Just upgraded to V0.14 and it's breaking on the admin uid. Yes, I've added the ACL to the permissions file and, Yes, I've updated the deploy statement to include -A and -S. 
```
composer network deploy -a zerotoblockchain-network.bna -p hlfv1 -i PeerAdmin -s randomString -A admin -S randomString
```
Any request to create a business network connection now fails with this message: 
```
Error trying to ping. Error: Error trying to query business network. 
Error: chaincode error (status: 500, message: 
Error: The current identity has not been registered: Admin@org1.example.com)
    at _checkRuntimeVersions.then.catch (/Users/robertdill/Documents/GitHub/Z2B_Master/Chapter11/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:663:34)
```
Where is this random id of ```Admin@org1.example.com``` coming from and what do I do about it? My code uses PeerAdmin throughout for access.

**Comment by davidoevans** [comment]
I'm experiencing the same issue when trying to issue an identity.

```
composer participant add -p hlfv1 -n healthchain-network -i PeerAdmin -s blah -d '{"$class":"org.healthchain.AccountAdmin", "accountAdminId":"jeff@healthchainrx.com"}'
Error: Error trying to ping. Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: The current identity has not been registered: Admin@org1.example.com)
```

...so beyond initial deployment using PeerAdmin, am not able to do anything.

**Comment by davidkel** [comment]
@rddill-IBM @davidoevans I suspect you both are trying to use PeerAdmin for requests to a business network (eg ping, participant add). This isn't something we advocate. PeerAdmin is a special id that has Fabric level priviledges and should only be used to do install/start/deploy/upgrade (note Not update) type actions. Any interaction with a business network should be done with identities you have obtained, most likely from the CA server in your fabric setup. 
The errors you are receiving are saying that PeerAdmin is not registered because it isn't. When you did the deploy you registered `admin` and bound it to a NetworkAdmin participant called `admin`. And of course admin is the bootstrap user for the composer development fabric ca server.

**Comment by davidoevans** [comment]
Thanks @davidkel .  This does not seem to be an issue.  Here's the commands I used to get by it.

After I start the Fabric 1.0.1 that comes with Composer, I did the following:
```
# Enroll an admin user (adminpw password is enforced)
fabric-ca-client enroll -u http://admin:adminpw@localhost:7054

# Request credentials for admin user; which stores them in the ~/.identityCredentials folder
composer identity request -p hlfv1 -i admin -s adminpw

# Create an identity in Composer using the certificates requested previously.
composer identity import -p hlfv1 -u admin -c ~/.identityCredentials/admin-pub.pem -k ~/.identityCredentials/admin-priv.pem 
```

After doing this, I seem to be fine to proceed with the instructions in the [v0.14.0 release notes](https://github.com/hyperledger/composer/releases/tag/v0.14.0)

```
# Deploy the business network specifying -A admin -S adminpw so it will be bound as a NetworkAdmin
composer network deploy -a dist/my-network.bna -p hlfv1 -i PeerAdmin -s blah -A admin -S adminpw
```

I'm now able to add participants issue identities as per ACL rules i've set for NetworkAdmin using the admin user.  However, even though the secret is required, it is not enforced.
```
composer participant add -p hlfv1 -n healthchain-network -i admin -s blah -d '{"$class":"org.healthchain.AccountAdmin", "accountAdminId":"andrew@email.com"}'
# Participant was added to participant registry.
# Command succeeded

composer identity issue -p hlfv1 -n healthchain-network -i admin -s blah -u andrew -a "resource:org.healthchain.AccountAdmin#andrew@email.com" -x false

# An identity was issued to the participant 'resource:org.healthchain.AccountAdmin#andrew@email.com'
# The participant can now connect to the business network with the following details:
#  userID = andrew
#  userSecret = FZeRPvMgGZEX
```

Any feedback on whether this is the right solution appreciated.  Thx.

**Comment by sstone1** [comment]
@davidoevans you shouldn't need the first `fabric-ca-client` command as the `composer identity request`will perform the enrolment for you, but otherwise looks good. 

@rddill-IBM as Dave said, you bound `admin` as a network admin and then tried to use `PeerAdmin` (who is not bound as a network admin) to connect to the business network.

**Comment by rddill-IBM** [comment]
Thanks! the distinction you're making between PeerAdmin and admin was not clear and I appreciate the help and clarification.
