### ISSUE TITLE
Unable to use any other id apart from PeerAdmin or admin as a NetworkAdmin

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#2370]
The developer environment for composer really only allows the use of PeerAdmin or admin as the id to bind during deployment (unless you do some messing about with creating a BN first so to allow you to issue identities first to register ids in the CA Server). If you use PeerAdmin then that has limitations as it doesn't have CA authority and we have advocated in the past that PeerAdmin should not be used to interact with Business Netwkrs. So really the only choice you have is admin from the CA. 
It should be possible to register new ids in the CA server to allow people to register ids that can be bound at deploy/start time. This would be useful for people to play more with role separation and could also be useful for interaction with fabric service provider implementations.

We could have
`composer identity register` command for example.

**Comment by davidkel** [comment]
this is related to #2363

**Comment by sstone1** [comment]
:-1: from me.

Adding new CA identities without using `composer identity issue` is a purely Fabric operational task, and wrapping the Fabric API into a Composer command line provides no real benefit over the `fabric-ca-client register` command or relevant APIs, or the initial CA configuration itself.

In addition, I think anyone not wanting to use "PeerAdmin" or "admin" (the IDs we provide out of the box for our *developer* getting started experience) is really going down into more "advanced user" territory and should be able to get comfortable with the underlying Fabric and how to configure it. The kind of people that would attempt this are those that would also be looking at `cryptogen` and `configtxgen` in order to set up a more realistic Fabric network.

Our focus has to be on providing beneficial development abstractions on top of a Blockchain platform (Fabric), not just wrapping everything that they can do.
