### ISSUE TITLE
As a user, I can understand how to bootstrap a network with my own participants

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#2387]
Although not tested yet this should be possible by way of example
- `composer participant add -p hlfv1 -i admin -s f -d '{"$class":"org.hyperledger.composer.system.NetworkAdmin", "participantId":"fred"}' -n digitalproperty-network` 
- `composer identity bind` or
- `composer identity issue`

And is probably something we should document, but also it would be good to have an easy command to do it so you don't have to remember the class type.

**Comment by sstone1** [comment]
:+1: on documentation, but not what you are thinking of documenting.
:-1: on the shortcut to create new participants of `NetworkAdmin` type.

`NetworkAdmin` isn't a special participant type, it's a built in "sample" type that makes it easier to deploy business networks without having to initially jump into more advanced stuff.

We should be documenting how users can supply their own set of bootstrap transactions during a network deploy/start operation. Those bootstrap transactions can add participants of their own types (e.g. Regulator, Manufacturer) and bind existing certificates to those new participants.

Why this instead of NetworkAdmin? Because in any realistic production network you'd need to partition  these initial participants by organisation, and limit them to the access control rules for that organisation.

For example, if I have NetworkAdmin instances named "regulator" and "manufacturer" and "insurer", how do I ensure that "regulator" can only create Regulator participants and so on? By identifier is pretty nasty - would be a lot easier to understand and deploy by just defining the Regulator participants up front during network deploy/start.

Also, this is never a P1... not sure why it was tagged as such.

**Comment by davidkel** [comment]
@sstone1 Yeah, shouldn't have been tagged as P1, it was raised for discussion as I try to see how end users of this might envisage this based on what was initially provided. I would say it wasn't obvious that NetworkAdmin was a built in "sample" type and as such because the default is for our commands to bind an identity into that instance of that participant, it comes over as more official especially as the standard deploy/start command creates a participant of that type and binds an identity to it. It's more of a base supported capability for which being able to supply your own bootstrap transactions (do they override the default ones or augment ?). So this provides a base capability that people would use with the option to do more capable things if they need/wish to. 
I think there is a valid role of a business network administrator that isn't a regulator of a business network for example which would have their own participant definition.
