### ISSUE TITLE
Identifiers no longer generated in playground for assets/participants

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#2413]
In current released playground, clicking the "Create New" button generates a random identifier:

<img width="726" alt="screen shot 2017-10-19 at 11 03 31" src="https://user-images.githubusercontent.com/7118158/31765705-3641a3fc-b4bd-11e7-95b9-a6069634b6bb.png">

I'm a fan of the random identifier as it makes it easy to create a bunch of _things_ without having to think about IDs for them.

In current unstable playground, it does not generate a random identifier, nor does it do it when you click "Generate Random Data":

<img width="723" alt="screen shot 2017-10-19 at 11 04 55" src="https://user-images.githubusercontent.com/7118158/31765746-5c8fb576-b4bd-11e7-9c85-73d8cba80a33.png">

We should fix this so there is at least _a_ way to generate random identifiers in playground. I don't mind if we don't generate them if your field requires a regex validator and we can't generate a valid field.

There was also talk about removing the `identifierFieldName:` prefix in issue #1408, which I am +1 on, but we still need to generate a random identifier number.

**Comment by samjsmith** [comment]
@sstone1 said above `I don't mind if we don't generate them if your field requires a regex validator and we can't generate a valid field.`

On top of this, from RocketChat, it seemed that most people expect the `Generate Random Data` link to result in 'generation of random data for fields that don't have a regex'.

Tagging @EdMoffatt and @winslet to get their input :)

**Comment by EdMoffatt** [comment]
Totally agree that hitting the "Generate Random Data" link should put something random in there.
I imagine it was descoped from tat function originally because we automatically generated one for you before you clicked that button.

My preference is that we don't automatically generate, but when you click the button it does if possible.  This strikes a nice balance between working if you care about the data you're creating *and* working if you don't.

**Comment by samjsmith** [comment]
As an addition, discussing with Simon, I've added the same change into the `generateRandomId` function in the `InstanceGenerator` in `composer-common` so that when you create a new Asset that has a relationship in it (mandatory property, it won't use the identifying field name with a colon as part of the identifier. This makes it more consistent across Composer.
