### ISSUE TITLE
EACCES-error when using certain keyValStore in connection.json

### ISSUE THREAD

**Issue by erNail** [hyperledger/composer#2423]
## Context

I'm running a local playground, started with `curl -sSL https://hyperledger.github.io/composer/install-hlfv1.sh | bash`. 

### Problem 1: keyValStore=/home/composer/.composer-credentials

When using a `connection.json` where `keyValStore` is `/home/composer/.composer-credentials`, i get the following errors when trying to deploy a network: 

```
$ composer network deploy -a maintenance-network.bna -p fabric-maintenance -i
 PeerAdmin -s randomString -A admin -S
Deploying business network from archive: maintenance-network.bna
Business network definition:
        Identifier: maintenance-network@0.1.11
        Description: A decentralized maintenance market with IoT devices

Error: Error trying login and get user Context. Error: Error trying to enroll user or load
channel configuration. Error: Failed to generate key for enrollment due to
error [Error: EACCES: permission denied, open
 '/home/composer/.composer-credentials/8978e0c3cba8e3fe883eacf3124a5a28f991aed531e1b03dc72e29d3a784e6d9-priv']
```

However, deploying with sudo and with the playground works. 

### Problem 2: keyValStore=/home/username/.composer-credentials
So, since i didn't want to enter sudo before each command, i now used `/home/vagrant/.composer-credentials` as `keyValStore`. I created a new business network card to import into Playground. However, when i try to import the card, i get the following error:

```
Error: failed to import identity. error trying to setup a keystore path. EACCES
```

## Expected Behavior

Playground should work with both keyValStore values.

## Actual Behavior

Playground can't import cards when the keyValStore is `/home/username/.composer-credentials`. 

## Related Issues
Issue #2438

## Steps to Reproduce
Try using Playground and console commands with both keyValStore values.

## Your Environment

* Version used: Playground 0.14.0
* Operating System and version (desktop or mobile): Ubuntu 16.04 Vagrant VM

**Comment by davidkel** [comment]
For problem 1: on your vagrant machine does the user `composer` exist ? if not then trying to use the home directory of a non existent user isn't going to work. using sudo means that you become root and it then has permission to create that directory.
For problem 2: pretty sure that the vagrant box for 16.04 doesn't have a `vagrant` user any more so the directory `/home/vagrant/` is not a valid directory
You need to ensure that the keyValStore you specify is appropriate within the environment you are running in.
a keyValStore of /home/composer is valid for our docker images because they have their own file system and they run under the `composer` userid so in the container file system a directory of /home/composer is valid but would not be valid on your vagrant VM.

**Comment by erNail** [comment]
For problem 1: There is a "composer"-directory, but i don't think the user exists.
For problem 2: I'm not using the xenial-vagrant box, because it's not designed according to the vagrant guidelines. A vagrant user with the password vagrant should exist in every box, and it does in mine.

However, the issue has been mostly resolved. See the related issue #2438.
