### ISSUE TITLE
Playground installations behave differently

### ISSUE THREAD

**Issue by erNail** [hyperledger/composer#2438]
## Context
There are 2 ways to start the Playground. You can use `$ composer-playground` or `$ curl -sSL https://hyperledger.github.io/composer/install-hlfv1.sh | bash`.
The problem is, that the two behave differently when working with them. In the past 4 days, i've tried to connect the Playground to a local running chain, so i could use the console and the Playground to work with the chain.

### Problem 1: EACCES-Error
When using the Playground startet with `$ composer-playground`, you are not able to import business-network-cards with the `keyValStore` of the `connection.json` set to `/home/composer/.composer-credentials`. 
When using the Playground startet with `$ curl -sSL https://hyperledger.github.io/composer/install-hlfv1.sh | bash`, you are not able to import cards with the `keyValStore` set to `/home/vagrant/.composer-credentials`.
Both times an EACCES-Error is thrown.

### Problem 2: Timeout when pinging
When using the Playground startet with `$ curl -sSL https://hyperledger.github.io/composer/install-hlfv1.sh | bash`, a chain named 'hlfabric' is started with it. Deploying a bna is no problem. However, when you try to ping the network via console with `composer network ping -n my-network -p hlfabric -i admin -s adminpw`, using the `connection.json` of the downloaded admin card, you get a timeout.

Since i'm using `$ composer-playground`, i can finally deploy the network via composer, and ping it via console, or deploy it via console and connect to it using the Playground.

## Expected Behavior

 `$ composer-playground` and `$ curl -sSL https://hyperledger.github.io/composer/install-hlfv1.sh | bash` should result in Playgrounds that work in the same way.

## Actual Behavior

`$ curl -sSL https://hyperledger.github.io/composer/install-hlfv1.sh | bash` causes several problems.

## Related issues
Issue #2423 

## Your Environment
* Version used: Playground 0.14.0
* Operating System and version (desktop or mobile): Ubuntu 16.04 VM

**Comment by davidkel** [comment]
This is working as expected. Connection profiles are not going to be portable between a dockerized playground and one that is running natively without work being done by the user.
When you use the installer, a docker container of playground is started.  As a docker container is like a Virtual Machine, it has it's own network and own file system, therefore a keyValStore that is coded to point to a file system on your local machine is unlikely to work on the file system of a docker container and vice-versa. It's like taking a connection profile for your machine and trying to put it on someone elses machine and expecting it to work.
As playground is running in a docker container, localhost in the context of that container refers to itself but only playground is running on that network address. So to communicate with the fabric it is connected to the same network as the fabric and can refer to the fabric container addresses by name. 
When you run playground outside of a container you are not part of that network so the names cannot be resolved, however because docker has exposed the ports to your machine, your machine can reference these containers as localhost:port. 
There is work to make connection profiles more portable regarding them having to have absolute file paths. In order to make them portable between docker containers and running native as you are trying to do would require the user to setup appropriate hostnames to map to the docker container hostnames. It's not something that Composer can or will do.

**Comment by erNail** [comment]
Okay, makes sense. It would be useful to add this explanation to the documentation. Also, the 2 ways to start composer locally should be mentioned on the same page in the documentation.

**Comment by sstone1** [comment]
No more one line installer, so no need for this.
