### ISSUE TITLE
Composer-rest-server test extensions

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#2473]
Issue #2454 included the scoping of filter query tests. At present there are 47 tests to be written, and this *will* be increased when 'include: resolve" is scoped.

Requirement is to complete each test stub, currently excluded from the test run via an `xit`, adding test resources to the test file if required.

**Comment by fenglianxu** [comment]
43 of out 47 tests cases are done with this defect.
The remained 4 of them are due to limitations of PounchDB and Loopback framework
The three of test cases are complicated nested $and and $or operators which do not behave as expected.  A PouchDB defect: https://github.com/pouchdb/pouchdb/issues/6879 has been raised recently for this issue. 
The one with the **$near** operator does not behave correctly, the entire where filter including **$near**  is omitted by the loopback framework between REST server the loopback. 
A new defect was created for further investigation.

**Comment by fenglianxu** [comment]
Close this issue now as the PR is merged.
