### ISSUE TITLE
Resolve should be able to run on all resources returned through a query

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#2479]
The loopback-connector, inside the all() function of businessnetworkconnector, does not permit a 'resolve' operation on all items returned from a query.

At the moment any attempt to perform a resolve on anything other that a single item, or all registry items, is ignored.

**Comment by fenglianxu** [comment]
@nklincoln Resolve only returns one level of relationship back at moment. This is how it works today, if we want to resolve more level of relationships. This will be a design change, this need to be discussed and agreed with @sstone1.  This is not a bug.  If we decide to support multiple level, then you can change this to an enhancement story.

**Comment by samjsmith** [comment]
@sstone1 I've had a quick look at this with @fenglianxu and the problem we're facing at the moment is that when the server starts up, the loopback visitor connects to the business network to discover all the object types and it classes all relationships as type String.  
So now we have the ability to return partial or full objects, the loopback schema needs to be different depending on what the user has asked for.
When they just want a top level object, a relationship is just a String name.
When they want the full monty, a relationship is an object. 
Somehow we need to get loopback to be able to realise this difference but for the moment, I'm not sure how.  Maybe we need to get in touch with the loopback API team?

**Comment by samjsmith** [comment]
@fenglianxu from doing a bit more digging, I think that one of the problems we have is that we don't have any current unit tests that test whether an object with a relationship to another relationship does actually get fully resolved.  The only test I could find is here: https://github.com/hyperledger/composer/blob/master/packages/loopback-connector-composer/test/businessnetworkconnector.js#L574

This is inadequate and so, odd as it seems, I can't believe that full object resolution for a single asset/participant with a relationship to another asset has ever worked from the composer-rest-server properly because the loopbackvisitor would have classed the relationship as a string.

Perhaps you could carry on the investigation by writing a bigger test that validates this theory?

**Comment by fenglianxu** [comment]
@samjsmith The  test  here: https://github.com/hyperledger/composer/blob/master/packages/loopback-connector-composer/test/businessnetworkconnector.js#L574
is mainly for code coverage test. The more test cases for the resolve relationship are covered by a system test in rest server layer.

**Comment by fenglianxu** [comment]
@samjsmith Three test cases are added to cover the filter with resolve feature and the code coverage has covered what we need to cover now.
