### ISSUE TITLE
Cannot list identity registry if participant type for an identity does not exist

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#2485]
## Context

If you follow these steps:

- Model a participant type
- Create a participant instance of that type
- Issue an identity to that participant instance
- Rename the participant type in the model file
- Deploy the updated model file
- Try to view the identity registry

The identity registry will blow up as it cannot handle the participant type.

## Expected Behavior

We should handle this case.

## Actual Behavior

We do not handle this case.

## Possible Fix

Make the code handle this case.

## Steps to Reproduce

1.
2.
3.
4.

## Existing issues

- [ ] [Stack Overflow issues](http://stackoverflow.com/tags/hyperledger-composer)
- [ ] [GitHub Issues](https://github.com/hyperledger/composer/issues)
- [ ] [Rocket Chat history](https://chat.hyperledger.org/channel/composer)

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by samjsmith** [comment]
@sstone1 I've been looking at this one with @KaiUsher this afternoon and we're not sure where the best place to swallow the error is.  At the moment, the error is being triggered by this call https://github.com/hyperledger/composer/blob/master/packages/composer-playground/src/app/identity/identity.component.ts#L48

The error is thrown from this section of code which is deep in the bowels of the common classes where the factory is attempting to build instances of the Asset relationship.  It feels very wrong to be ignoring errors in here and instead we should be swallowing errors like this in the UI component. 

I don't think that the client API allows us much scope since it only provides a `getAll()` function which attempts to materialise the objects.  

One possible solution is to introduce a new `getAllIds()` function which by nominative determinism simply returns a List of IDs.  Then in the Playground code we could use that and then loop over each ID making a call to `get(id)` to try to materialise each object in turn, swallowing errors as we go.

Since this is in common/client code, can you let me know what you think please?

**Comment by samjsmith** [comment]
Let's leave out results that are not valid object instances according to the model of the currently deployed business network.  They may become valid again in the future.
