### ISSUE TITLE
For all already enrolled users (who connected to network with their correct identity) you can pass any userSecret to have access to blockchain

### ISSUE THREAD

**Issue by a4455395** [hyperledger/composer#2545]
For all already enrolled users (who already connected to network with their identity) you can pass any userSecret to have access to clockchain
## Context

For all already enrolled users (who already connected to network with their identity) you can pass any userSecret to have access to clockchain
## Expected Behavior

with wrong userSecret connect function should throw error with failure authorization text
## Actual Behavior

with any userSecret system allows user to have access
## Possible Fix

When a participant uses an identity to submit a transaction to the deployed business network for the first time, that identity is Activated. With this identity state system don't want to check correctness of password
## Steps to Reproduce

1. first time 'correct userSecret', bash: composer network ping -p hlfv1 -n my-network -i admin -s adminpw

2.admin is enrolled, so try to use wrong secret: composer network ping -p hlfv1 -n my-network -i admin -s wrongsecrettralala

3. Command succeeded

## Existing issues

- [ ] [Stack Overflow issues](http://stackoverflow.com/tags/hyperledger-composer)
- [ ] [GitHub Issues](https://github.com/hyperledger/composer/issues)
- [ ] [Rocket Chat history](https://chat.hyperledger.org/channel/composer)

## Your Environment

* Version used: 0.14.2
* Environment name and version (e.g. Chrome 39, node.js 5.4): node 6.9.5
* Operating System and version (desktop or mobile): ubuntu 16.4
* Link to your project:

**Comment by sstone1** [comment]
The enrolment secret is not a password or a form of authentication; it is a one-time use secret that can be passed to the Fabric CA in exchange for an enrolment certificate. That process is called enrolment and only happens when you haven't already enrolled (and don't have the enrolment certificate).

If you've already enrolled, the enrolment secret is ignored and never used. There is no way for us to validate the enrolment secret without attempting to enrol again, which would generate yet more certificates (or fail if max enrolments has been hit).

We are removing the `-i` and `-s` arguments in next weeks release as part of work to make the APIs and CLIs business network card "native", and this will become a bit more obvious.

**Comment by a4455395** [comment]
@sstone1 Thanks for answer, Simon! I see that certificates was generated and stored in  path/.composer-credentials. But I need to create node API and I have no idea how can I authenticate participants with this certs to verify their identity. Probably I should use businessNetworkConnection.connect func and pass some cert there? Can you please explain it, or at least advise me some path where I can find the correct solution?
