### ISSUE TITLE
ReferenceError: s is not defined

### ISSUE THREAD

**Issue by nasht00** [hyperledger/composer#2578]
My BNA includes the following logic file: https://jsfiddle.net/4rekknuq/

This file used to run just fine, but now I get:
```
ReferenceError: s is not defined
      at __generator (eval at <anonymous> (eval at compile (contract-network/node_modules/composer-runtime/lib/scriptcompiler.js:97:33)), <anonymous>:1275:14)
      at CompiledScriptBundle.execute (contract-network/node_modules/composer-runtime/lib/compiledscriptbundle.js:53:29)
      at __dirname.submitTransaction.context.getResolver.resolve.then.then (contract-network/node_modules/composer-runtime/lib/engine.transactions.js:93:58)
      at process._tickCallback (internal/process/next_tick.js:109:7)
```

The error started happening from this specific commit:
https://github.com/hyperledger/composer/commit/81afd3a289592e27e34ea069b8fd852c4b880dc4

I tested on playground before and after this commit to compare.

I see that `javascriptparser.js` was modified in this commit. Maybe related?

**Comment by davidkel** [comment]
@mbwhite could you take a look at this as appears to be on one of your commits.

**Comment by mbwhite** [comment]
@nasht00 could you say how that code is related to your transaction functions please?

**Comment by davidkel** [comment]
The problem here is the change to the javascriptparser. It now includes functions in the function declarations that did not get included before. These functions included ones called 's' and 'e'.
What the generator function does is return an object of all executable functions for example
```
{
   onTxnFn: onTxnFn,
   s: s
   e: e
  uniqueArray: uniqueArray
}
```
The reason it provides this object is to provide a way to be able to drive the available transaction functions. And it is this object that fails to be created with the error 's' is not defined.
The fix to this is to only populate this object with actual transaction functions, ie ones that are decorated with the transaction annotation (and for backward compatibility any function that has on<transaction type> although we may just get away with exposing any function which starts with 'on').

**Comment by davidkel** [comment]
It looks like the change to the javascriptparser has had other effects and other users are getting errors "Could not find any functions to execute for transaction". They were working prior to 0.14.3 where change came in.

**Comment by nasht00** [comment]
@mbwhite The javascript file I attached is generated by running the command `browserify -r json-logic-js > lib/requires.js`. This takes the module `json-logic-js` and makes it browser-friendly.

It also declares a function called `require()`, which now allows me to call, from my transaction functions: 

```
var jsonLogic = require('json-logic-js');
return jsonLogic.apply(rules)
```

This has been a really nice workaround to the current limitation that we can't import third-party npm modules.

**Comment by nasht00** [comment]
I confirm that my BNA is successfully deployed after @davidkel 's commit.

**Comment by davidkel** [comment]
@nasht00 thanks for the feedback. I shall close the issue.

**Comment by sunil2606** [comment]
I got an error as **org is not defined**  what should i do ?
