### ISSUE TITLE
Running composer-rest-server 0.14 for 2nd org causes Error: The current identity has not been registered: admin.

### ISSUE THREAD

**Issue by denisglotov** [hyperledger/composer#2585]
My fabric network consists of 2 orgs, each with different MSP certs. When I start composer-test-server for the 1st org, it works well, but running it for the 2nd org gives the error. 0.13.2 worked well in this case.

## Context
I have 4 connections profile as @sstone1 suggested here: https://github.com/hyperledger/composer/issues/2505 so now I have: mainorg, org2, mainorgtx, org2tx.
Transaction connections (mainorgtx and org2tx) reference keyValStore: .composer-credentials/mainorg and .composer-credentials/org2, same as mainorg and org2 connection profiles. 
Now I set up the network as the following:
```
composer identity import -p mainorg -u MainPeerAdmin -c crypto-config/.../Admin@mainorg-cert.pem -k crypto-config/.../..._sk
composer identity import -p org2 -u Org2PeerAdmin -c crypto-config/.../Admin@org2-cert.pem -k crypto-config/.../..._sk
composer runtime install -n my-network -p org2 -i Org2PeerAdmin -s randomString
composer runtime install -n my-network -p mainorg -i MainPeerAdmin -s randomString
composer network start -a dist/my-network.bna -p mainorgtx -i MainPeerAdmin -s randomString -A admin -S
```
The commands run fine, both chaincode instances appear (one for each org).  But when I start composer-rest-servers, the mainorg's one is fine, but org2's one fails:
```
$ ~/bin/composer-rest-server -p org2tx -n my-network -i admin -s adminpw -N never -w true
Discovering types from business network definition ...
Connection fails: Error: Error trying to ping. Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: The current identity has not been registered: admin)
It will be retried for the next request.
Exception: Error: Error trying to ping. Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: The current identity has not been registered: admin)
Error: Error trying to ping. Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: The current identity has not been registered: admin)
    at _checkRuntimeVersions.then.catch (/home/denis/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:663:34)
```
I also tried to register 2nd admin prior to starting composer-rest-server, as suggested somewhere in the chat, but it also fails:
```
$ composer participant add -p org2tx -i admin -s adminpw -d '{"$class":"org.hyperledger.composer.system.NetworkAdmin", "participantId":"admin2"}' -n my-network
Error: Error trying to ping. Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: The current identity has not been registered: admin)
Command failed
```

## Your Environment
```
denis@node007:~$ composer-rest-server --version
v0.14.1
denis@node007:~$ composer --version
v0.14.1
denis@node007:~$ docker --version
Docker version 17.09.0-ce, build afdb6d4
denis@node007:~$ docker-compose --version
docker-compose version 1.13.0, build 1719ceb
denis@node007:~$ uname
Linux
```

**Comment by davidkel** [comment]
What you have here is 2 organisations, both with an identity called admin but of course they aren't the same identity. One is from org1 and the other is from org2. The org1 admin got registered, but you cannot register another identity called admin as you already have one. In the real world you woudn't use simple names for identities you would qualify then in some way to make them unique for each organisation.

**Comment by denisglotov** [comment]
Thanks, @davidkel, I tried to change the admin name to _admin2_ for the 2nd org. In particular, in my docker-compose.yaml for ca container I changed start command to `command: sh -c 'fabric-ca-server start -b admin2:adminpw -d'`. Still have the same error when I start the composer-rest-server:
```
$ ~/bin/composer-rest-server -p org2tx -n educhain-network -i admin2 -s adminpw -N never -w true
Discovering types from business network definition ...
Connection fails: Error: Error trying to ping. Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: The current identity has not been registered: admin2)
It will be retried for the next request.
Exception: Error: Error trying to ping. Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: The current identity has not been registered: admin2)
Error: Error trying to ping. Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: The current identity has not been registered: admin2)
    at _checkRuntimeVersions.then.catch (/home/denis/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:663:34)
```
Maybe the problem is that magic `-A admin -S` has been applied to 1st org and not to the 2nd?..

**Comment by davidkel** [comment]
So in the 2nd case again it is a different identity and it hasn't been registered (ie it isn't bound to a participant). With the deploy specifying -A bound the admin identity to the NetworkAdmin#admin participant.

**Comment by sstone1** [comment]
@denisglotov you're on the right track with:

> Maybe the problem is that magic -A admin -S has been applied to 1st org and not to the 2nd?

But this is not a bug 😉 

When we map an identity (digital certificate) to a participant, we store a mapping between that identity and the participant in the identity registry. When we do this using enrolment secrets, we only have one piece of information available - the enrolment ID - so we store the enrolment ID in the identity registry as a new identity in the `ISSUED` state.

When the identity is used for the first time, we try to match the common name of the identity against an enrolment ID that we have stored in the identity registry. If we find a match, then we update the identity registry with the certificate fingerprint instead of the enrolment ID, and we perform matching based on the certificate fingerprint for all subsequent requests.

There is a bit of a problem though - the enrolment ID is not unique to the entire Fabric network - it is only unique within the scope of an organisation. Another organisation could create an identity with the same enrolment ID on their CA, and attempt to access the business network. To prevent this, we also store the issuers organisation along with the enrolment ID in the identity registry for all `ISSUED` identities. Enrolment ID matching only works if you are in the same organisation as the user who issued you the identity.

For a multi-organisation deployment, you need to create business network administrators using certificates instead. This is the `-A admin -C /path/to/admin.pem` options to `composer network start` and `composer network deploy`.

You want something like this:

```
composer identity import -p mainorg -u MainPeerAdmin -c crypto-config/.../Admin@mainorg-cert.pem -k crypto-config/.../..._sk
composer identity import -p org2 -u Org2PeerAdmin -c crypto-config/.../Admin@org2-cert.pem -k crypto-config/.../..._sk
composer runtime install -n my-network -p org2 -i Org2PeerAdmin -s randomString
composer runtime install -n my-network -p mainorg -i MainPeerAdmin -s randomString

### Changes here!
composer network start -a dist/my-network.bna -p mainorgtx -i MainPeerAdmin -s randomString -A admin-org1 -C /path/to/admin-org1.pem -A admin-org2 -C /path/to/admin-org2.pem
```

The `admin-org1.pem` and `admin-org2.pem` files must be PEM encoded digital certificates with `-----BEGIN CERTIFICATE-----` at the top.

**Comment by denisglotov** [comment]
@sstone1, thank you for the detailed answer. I tried what you suggested and it works. But how can I use _admin-org1_ or admin-org2_ without the password? Commands like `composer-rest-server`, `composer network list` or `composer identity issue` demands `-s` parameter with enrollment secret. And `randomString` does not fit:
```
$ composer-rest-server -p mainorgtx -n my-network -i admin-org1 -s randomString -N never -w true -a true -m false                                     
Discovering types from business network definition ...
Connection fails: Error: Error trying login and get user Context. Error: Error trying to enroll user or load channel configuration. Error: Enrollment failed with errors [[{"code":400,"message":"Authorization failure"}]]
It will be retried for the next request.
Exception: Error: Error trying login and get user Context. Error: Error trying to enroll user or load channel configuration. Error: Enrollment failed with errors [[{"code":400,"message":"Authorization failure"}]]
Error: Error trying login and get user Context. Error: Error trying to enroll user or load channel configuration. Error: Enrollment failed with errors [[{"code":400,"message":"Authorization failure"}]]
    at client.getUserContext.then.then.catch (/home/denis/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:302:34)
    at process._tickCallback (internal/process/next_tick.js:103:7)
``` Please advice.

**Comment by denisglotov** [comment]
UPD2: Also I tried to add a participant, but this fails also:
```
$ composer participant add -p mainorg -i MainPeerAdmin -s randomString -d '{"$class":"org.hyperledger.composer.system.NetworkAdmin", "participantId":"admin1"}' -n educhain-network
Participant was added to participant registry.

Command succeeded

$ composer identity issue -p mainorg -n my-network -i MainPeerAdmin -s randomString -u Admin1 -a org.hyperledger.composer.system.NetworkAdmin#admin1 -x true
Error: fabric-ca request register failed with errors [[{"code":400,"message":"Authorization failure"}]]
Command failed

$ composer identity issue -p mainorg -n my-network -i admin-org1 -s adminpw -u Admin1 -a org.hyperledger.composer.system.NetworkAdmin#admin1 -x true
Error: Error trying to ping. Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: The current identity has not been registered: admin-org1)
Command failed
```

**Comment by denisglotov** [comment]
Looks working when I use MainPeerAdmin/Org2PeerAdmin with randomString when running composer-rest-server, hope this is right. Testing now...

**Comment by denisglotov** [comment]
Adding new participant still does not work: which password should I use?
```
$ composer participant add -p mainorg -i MainPeerAdmin -s randomString -d '{"$class":"MyRegistrar", "registrarId":"first", "name":"theFirst"}' -n educhain-network
Participant was added to participant registry.

Command succeeded

$ composer identity issue -p mainorg -n educhain-network -i MainPeerAdmin -s randomString -u First -a MyRegistrar#first -x false 
Error: fabric-ca request register failed with errors [[{"code":400,"message":"Authorization failure"}]]
Command failed

$ composer identity issue -p mainorg -n educhain-network -i admin-org1 -s adminpw -u First -a MyRegistrar#first -x false         
Error: Error trying to ping. Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: The current identity has not been registered: admin-org1)
Command failed
```
Please suggest: which credentials to use for 'composer identity issue'?

**Comment by MAGilleeney** [comment]
@sstone1 Many thanks for your responses to this issue and issue #2505 . Your two responses have been a great help in our multi organisation setup. However we are experiencing very similar issue to @denisglotov with regards to the following error: 

```
Error: chaincode error (status: 500, message: Error: The current identity has not been registered: admin
```

**Little background**
We've created a multi organisation Hyperledger network. 12 organisations with one central organisation which has a unique channel with every other organisation.

We are using our own custom built NodeJs REST API using the composer-client SDK to connect to the network.

After setting up our network and creating the relevant participants / identities we are able to interact with the network for a random period of time. However, after that period of time the above error starts happening for no explicable reason. 

**Debugging**
We've been trying to debug the issue in order to understand what is going on. Here's what we've found so far:

- We can connect to the network with the created identities or network admin and the problem with eventually occur. However, this only ever seems to occur when using composer-client SDK. We've tried spamming "composer network ping" on recurring loops, from multiple CLI's with the identities holding strong. Spin up the NodeJs and make a few to a lot of requests and the issue will arise 

- We've noticed that in the .composer-org1-credentials folder the various certs for the identities are present and that each request to the API ends up modifying the certs' modified date (even though the cert isn't actually modified). We assume this is down to the cert being read, however we wondered if there could be some sort of race condition on this and causing the fabric to invalidate and request a new cert

- Even though we see the error (listed above) when looking at the composer logs we see a slightly different error: 
```
{"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: The current identity must be activated (ACTIVATION_REQUIRED))","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: The current identity must be activated (ACTIVATION_REQUIRED))\n    at channel.queryByChaincode.then.catch (/usr/local/lib/node_modules/composer-cli/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:749:34)"}
```

I'd also like to understand a little bit more about the identity registry. Where is this located? Is there one per organisation or one per channel? How is the state of the identities persisted?

Any thoughts on this would be greatly appreciated. 

Many thanks.

**Comment by davidkel** [comment]
@denisglotov Identity issue requires you to use an identity that has 2 specific capabilities
1. Has issuer authority with the CA Server you are using
2. Has the authority to associate an identity with a participant in a business network. 
So in your case do admin-org1 and admin-org2 have issuer authority in your CA Server ?

**Comment by denisglotov** [comment]
@davidkel, I looked inside my fabric-ca container for mainorg, dumped /etc/hyperledger/fabric-ca-server/fabric-ca-server.db and found ```INSERT INTO "users" VALUES('admin-org1',X'243261243130247157686C30316947494F444A666B7A44722F5669436559637834473047422E796F7A72794C56496B4E567768764F414B524B503236','client','','[{"name":"hf.Registrar.Roles","value":"client,user,peer,validator,auditor"},{"name":"hf.Registrar.DelegateRoles","value":"client,user,validator,auditor"},{"name":"hf.Revoker","value":"1"},{"name":"hf.IntermediateCA","value":"1"}]',0,-1);```. Moreover I start the CA container with this option:  `command: sh -c 'fabric-ca-server start -b admin-org1:adminpw -d'`.

**Comment by davidkel** [comment]
@denisglotov ok, so you have the identities defined in the CA Server so why are you specifying the -C option on the deploy, surely you want to use the -S option as I am assuming you don't have the certs for these 2 admin identities already ?

**Comment by denisglotov** [comment]
@davidkel, this is what this issue began with. If I use `-S`, then I cannot run composer-rest-server for orgs other then the 1st. Thus @sstone1 suggested to use `-C admin-cert.pem` and this fixed running composer-rest-server for all orgs, but broke registering a new user.
I do have certs for admins of all my orgs: they are initially generated by _cryptogen_ tool.

**Comment by sstone1** [comment]
@denisglotov the next bit is a bit tricky I'm afraid.

The admins which have been generated by cryptogen are not registered with the Fabric CA, and they cannot register new identities using the Fabric CA. 

You need to enrol the Fabric CA admins, get a certificate/private key pair for them, and then bind those certificates to participants in the business network. Once bound, you can use those certificates to interact with the business network, but since they are Fabric CA admins they can be used to issue new identities.

1. Enroll the Fabric CA admins; you can use `fabric-ca-client` for this or the `composer identity request` command. This will write some files into the `.identityCredentials` directory in your home directory - `admin-pub.pem` and `admin-priv.pem`.

2. Bind the `admin-pub.pem` files to business network participants using `composer identity bind`.

3. Import the `admin-pub.pem` and `admin-priv.pem` files into the Composer wallet by using `composer identity import`.

4. Use the identities imported in 3) to interact with the business network and issue further identities.

If you do these steps up front before the deployment then you can bind the Fabric CA admins at deployment (using the -C flag) instead of the admins generated by cryptogen.

**Comment by sstone1** [comment]
Oh - just to say - this is all based on commands prior to v0.15.0 which we released today - the commands have all changed.

**Comment by denisglotov** [comment]
Brilliant, @sstone1, both generating new participants and running rest servers for all orgs worked!

Just a question, I didn't use (2) in your last explanation. Curious, what did you mean, to which participants should I bind `admin-pub.pem` and why?

**Comment by denisglotov** [comment]
Hopefully last problem :)
How can I transfer _admin-org2_ to the another host?

Now I use Swarm to run my network: orderer and mainorg on the 1st host, org2 on the 2nd host.
`composer network start ... -A admin-org2 -C ...` is run on the 1st host and all subsequent actions (composer-rest-sercer, composer participant add, conposer identity issue) work there fine.
But on the 2nd host they do not work:
```
$ ~/bin/composer-rest-server -p org2tx -n my-network -i Org2CaAdmin -s randomStr -N never -w true -a true -m false
Discovering types from business network definition ...
Connection fails: Error: Error trying to ping. Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: The current identity has not been registered: admin-org2)
```
I tried copying `~/.identityCredentials` to the 2nd host and 
```
$ composer identity import -p org2 -u Org2CaAdmin -c ~/.identityCredentials/admin-org2-pub.pem -k ~/.identityCredentials/admin-org2-priv.pem            
An identity was imported with name 'Org2CaAdmin' successfully

Command succeeded

$ composer participant add -p org2 -i Org2CaAdmin -s adminpw -d '{"$class":"org.hyperledger.composer.system.NetworkAdmin", "participantId":"admin-org2"}' -n educhain-network
Error: Error trying to ping. Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: The current identity has not been registered: admin-org2)
Command failed

$ composer identity bind -p org2 -n educhain-network -i Org2CaAdmin -s randomStr -a admin-org2 -c ~/.identityCredentials/admin-org2-pub.pem             Error: Error trying to ping. Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: The current identity has not been registered: admin-org2)
Command failed
```
How can I make _admin-org2_ work on other hosts too?

**Comment by denisglotov** [comment]
@sstone1 - please have a look to the previous post. This is still in terms of 0.14.
