### ISSUE TITLE
Imported card name in store does not reflect name of card imported

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#2677]
Having created a Business Network Card, for instance with name 'TestCard.card', and then importing the card, the resulting card in my card wallet is based upon the username from the meta-data, and bares no reflection at all on the card name itself.

I would have expected the resulting card in my card store to match the name of the card that I imported, rather than based upon internal metadata (though the reasoning behind using metadata is itself sound).

Having the card store reflect the name of the imported card would give greater clarity to a user of cards.

**Comment by bestbeforetoday** [comment]
The name by which the card is referred in the system needs to be unique and also help the user to identify which user and business network it relates to so they know what to expect when they use the card to connect. So the default naming scheme for the card is _userName@businessNetworkName_. This can be overridden by the user on import by specifying the `--name` parameter the to `composer card import` command, so they are free to name the card `TestCard` if they choose.

@EdMoffatt any design perspective on the default card naming scheme? Otherwise this can be closed.

**Comment by sstone1** [comment]
Closing. The file name of the card is not equal to the name of the card. The commands generate file names that match the name of the card by default, and you can choose to specify your own name for the card when you import it using `composer card import`.
