### ISSUE TITLE
As a developer I would like card enabled apis for issueIdentity, bindIdentity, revokeIdentity

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#2767]
Not looked into more detail at the moment in this but there is a stackoverflow question where someone tried to use issueIdentity but it didn't work as expected to them.
https://stackoverflow.com/questions/47341554/hyperledger-composer-issue-identity-but-missing-business-card

Now these apis can be used but the developer has to do more work around the card side, for example on issue identity they may need to build a card and return that.

This issue exists as a reminder to have a discussion about these apis. Also note the documentation issue that is currently out of date around these apis.
#2737 Documentation which requires changing for BN Cards

**Comment by caveman7** [comment]
Hello, I tried creating an ID Card once an Identity is issued (As this is meant to run unit tests, I used in-browser memory) using this function:

```
        function createIDCard (identity, adminConnection, isAdmin) {
            const card = new IdCard({
                userName: identity.userID,
                description: 'Card for ' + identity.userID,
                businessNetwork: 'smart_contract',
                enrollmentId: identity.userID,
                enrollmentSecret: identity.secret
            },
                {
                    name: 'defaultProfile',
                    type: 'embedded'
                });
            
            if (isAdmin) card.metadata.roles = ["PeerAdmin"];

            return adminConnection.importCard(identity.userID, card);
        }

```

and modified the **useIdentityFunction** to the following:
```
function useIdentity(identity) {
        return businessNetworkConnection.disconnect()
            .then(() => {
                businessNetworkConnection = new BusinessNetworkConnection({
                    fs: bfs_fs
                });
                events = [];
                businessNetworkConnection.on('event', (event) => {
                    events.push(event);
                });
                return businessNetworkConnection.connect(identity.userID);
            });
    }
```

When I use the identity:` return useIdentity(user1Identity)`, the error generated is:
`Error: The secret na specified for the identity user1 does not match the stored secret e505af10`

I tried looking into what happened and apparently when I imported the card in **adminConnection**, the secret is turned to PKI-style credentials:

```
IdCard {
  metadata: 
   { userName: 'user1',
     description: 'Card for user1',
     businessNetwork: 'smart_contract',
     enrollmentId: 'user1',
     version: 1 },
  connectionProfile: { name: 'defaultProfile', type: 'embedded' },
  credentials: 
   { certificate: '-----BEGIN CERTIFICATE-----\ndXNlcjE6Mzk4Zjg3NzAtNTQ1NC00ODVmLThjNmQtMGYwYzJhODczMjI4\n-----END CERTIFICATE-----\n',
     privateKey: '-----BEGIN PRIVATE KEY-----\ndXNlcjE=\n-----END PRIVATE KEY-----\n' } }
```

**connect** requires the regular enrollment secret. Any solutions to this? Is this even the right way to connect as a Participant? The sample code in **composer-network-sample** is not updated with v0.15 updates, so I have no reference. If the above explanation is not clear enough, please refer to the code: https://github.ibm.com/baldred/userorgchaincode and run the test

**Comment by kenjisiu-ibmhk** [comment]
There are several problems.

First of all, in the `jsdoc` of the `issueIdentity` method [here](https://hyperledger.github.io/composer/jsdoc/module-composer-client.BusinessNetworkConnection.html#issueIdentity__anchor), the result object is **not documented**. When I first tried the method, I did not peek into the resolved object, and the secret was lost.

For your information, in the implementation I am using (`v0.16.2`), it is an object with 2 fields, `userID` and `userSecret`, like this:

```json
{
  "userID": "user1",
  "userSecret": "GlWsaQkrPXkn"
}
```

Then, (as far as I know) I have to go to the Playground web interface, click "Create Business Network Card", select the Fabric blockchain I am using, and choose "ID and Secret", and fill in the values got above, the network name, and the card name, in order to generate the card. After that, I need to download the card from Playground, and update it using [`ibm-container-service/cs-offerings/scripts/connection-profile/update_card.sh`](https://github.com/IBM-Blockchain/ibm-container-service/blob/master/cs-offerings/scripts/connection-profile/update_card.sh) since I am using the IBM certified image, and the node is running on IBM Cloud (Bluemix), so the domain names in the card need to be updated from domain names local to the Docker network to the external IP of the Kubernetes node.

I cannot find an API for managing enrollment in any of: [`composer-common`](https://hyperledger.github.io/composer/jsdoc/module-composer-common.html), [`composer-client`](https://hyperledger.github.io/composer/jsdoc/module-composer-client.html), [`composer-admin`](https://hyperledger.github.io/composer/jsdoc/module-composer-admin.html), and [`composer-runtime`](https://hyperledger.github.io/composer/jsdoc/module-composer-runtime.html).

The [`composer identity issue` command in `composer-cli`](https://hyperledger.github.io/composer/reference/composer.identity.issue.html) seems to be available for the job, but it can only create a new identity. If the identity is already created, it returns the following error:

```
Issue identity and create Network Card for: user1

✖ Issuing identity. This may take a few seconds...
Error: fabric-ca request register failed with errors [[{"code":0,"message":"Identity 'user1' is already registered"}]]
Command failed
```

**In short, there is currently no API or command for getting a card from an existing identity by enrollment, nor is there any API for creating a new card from a participant.**

It seems that the [`composer identity request` command (there is not even a page for this command, so this is a broken link)](https://hyperledger.github.io/composer/reference/composer.identity.request.html) is able to get the certificate and private key by providing the enrollment secret. So the developer first need to do [`issueIdentity`](https://hyperledger.github.io/composer/jsdoc/module-composer-client.BusinessNetworkConnection.html#issueIdentity__anchor) using the API, and get the `userSecret` from the result. Then, use `composer identity request` to get the certificate and private key, and then go back to the API, do a [`new IdCard()`](https://hyperledger.github.io/composer/jsdoc/module-composer-common.IdCard.html#IdCard__anchor) by filling the parameters by manually, and then do a [`setCredentials`](https://hyperledger.github.io/composer/jsdoc/module-composer-common.IdCard.html#setCredentials__anchor) and fill in the certificate and private key he just got.

I did not test this solution. This is too complicated. I don't even want to spend my time trying it.

**Comment by izakblom** [comment]
This issue still exists. No methods in the API can be used to create a full card.

**Comment by alexrosenfeld10** [comment]
I'm also looking for this functionality

**Comment by hingjlee** [comment]
Supportive
