### ISSUE TITLE
Playground does not 'Helper Values' when an Asset Definition includes an array of another Asset or Concept

### ISSUE THREAD

**Issue by rthatcher** [hyperledger/composer#2777]
Using this model excerpt:
```
namespace org.acme.biznet

concept Address {
  o String street
  o String city
  o String country
}

asset Field identified by fieldId {
o String fieldId
o Address address
--> Farmer owner
}
```

Helper values for the Concept Address are provided as expected.
However when the Address for the Field is changed to the array `Address[]` then Playground does not show the helper data when creating the asset.

Using the same model, the REST server sample JSON works for a single Address or an array.

Composer v0.15.1 
Same behaviour with Bluemix hosted Playground and Local Playground.

**Comment by rthatcher** [comment]
Clarification from earlier reported error.
Now using Composer v0.19.0
When using the model above with the Address Concept as a single field I create a Field Asset in Playground and I see the following 'helper JSON': 
```
{
  "$class": "org.acme.biznet.Field",
  "fieldId": "9828",
  "address": {
    "$class": "org.acme.biznet.Address",
    "street": "",
    "city": "",
    "country": ""
  }
}
```
and in REST I see similar:
```
{
  "$class": "org.acme.biznet.Field",
  "fieldId": "string",
  "address": {
    "$class": "org.acme.biznet.Address",
    "street": "string",
    "city": "string",
    "country": "string",
    "id": "string"
  }
}
```

However when I modify the model to have the Address as an Array ` o Address [] address ` the helper JSON in Playground reduces to this:
```
{
  "$class": "org.acme.biznet.Field",
  "fieldId": "3515",
  "address": []
}
```

and in REST server it also reduces:
```
{
  "$class": "org.acme.biznet.Field",
  "fieldId": "string",
  "address": []
}
```

**Comment by bestbeforetoday** [comment]
I think what you are seeing is "as designed". The default (empty) data presented by Playground for any array field is an empty array. Clicking on **Generate Random Data** will give you an array field with one sample element.

The REST server does just give you the default (empty) data for array fields, with no option to generate more complete examples. It does show you the model too, so you can deduce your own values from that. I'm not sure whether it's worth changing this. Has there been user confusion?

The behaviour that looks slightly problematic is that the REST server is including an optional **id** field in Concepts that shouldn't be there. Nothing breaks if somebody does specify this field in input since it just gets ignored, but it's not correct.
