### ISSUE TITLE
Node-red nodes wrong reference and installing old version

### ISSUE THREAD

**Issue by jdockter** [hyperledger/composer#2793]
## Context
This issue is two fold
1) The documentation here, https://hyperledger.github.io/composer/integrating/node-red.html,  is pointing to the wrong NPM package for the Node-Red nodes.  Should point to https://www.npmjs.com/package/node-red-contrib-composer

2) When trying to install the composer nodes, 'node-red-contrib-composer', in the Node-Red pallet manager only shows 0.0.6 and fails to install

21 Nov 05:57:18 - [info] Node-RED version: v0.17.5
21 Nov 05:57:18 - [info] Node.js  version: v8.9.0
21 Nov 05:57:18 - [info] Linux 4.10.0-38-generic x64 LE
21 Nov 05:57:18 - [info] Loading palette nodes
21 Nov 05:57:18 - [warn] ------------------------------------------------------
21 Nov 05:57:18 - [warn] [rpi-gpio] Info : Ignoring Raspberry Pi specific node
21 Nov 05:57:18 - [warn] ------------------------------------------------------
21 Nov 05:57:18 - [info] Settings file  : /home/ibm/.node-red/settings.js
21 Nov 05:57:18 - [info] User directory : /home/ibm/.node-red
21 Nov 05:57:18 - [info] Flows file     : /home/ibm/.node-red/flows_ubuntu.json
21 Nov 05:57:18 - [info] Creating new flow file
21 Nov 05:57:18 - [info] Starting flows
21 Nov 05:57:18 - [info] Started flows
21 Nov 05:57:18 - [info] Server now running at http://127.0.0.1:1880/
21 Nov 06:02:34 - [info] Installing module: node-red-contrib-composer, version: 0.0.6
21 Nov 06:03:29 - [warn] Installation of module node-red-contrib-composer failed:
21 Nov 06:03:29 - [warn] ------------------------------------------
21 Nov 06:03:29 - [warn] Error: stderr maxBuffer exceeded
21 Nov 06:03:29 - [warn] ------------------------------------------

![image](https://user-images.githubusercontent.com/22593763/33076409-47c0ab16-ce92-11e7-9f4b-d0e073768f22.png)

## Possible Fix
Installed NPM package from .node-red/node_modules directory manually to get vesion 0.0.9, ie npm install node-red-contrib-composer@0.0.9

## Steps to Reproduce

1.
2.
3.
4.

## Existing issues

- [ ] [Stack Overflow issues](http://stackoverflow.com/tags/hyperledger-composer)
- [ ] [GitHub Issues](https://github.com/hyperledger/composer/issues)
- [ ] [Rocket Chat history](https://chat.hyperledger.org/channel/composer)

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by jdockter** [comment]
@caroline-church fyi

**Comment by davidkel** [comment]
@jdockter the documentation on the composer website looks correct as it looks to me that it is pointing to https://hyperledger.github.io/composer/integrating/node-red.html.
The info in the palette is out of date because it is out of date on https://flows.nodered.org/node/node-red-contrib-composer however I don't actually know what version it would attempt to install (whether it tries to install a specific version or not).
The fail to install you would have to get in touch from someone in node-red as this appears to be a problem with node-red trying to install rather than there being something wrong with the package in npm as I can install both 0.0.6 and 0.0.9 (latest) into the docker container and use it I get the same error if I use the node-red facility to try to install.

**Comment by davidkel** [comment]
I've been able to refresh the info on the flows website so now it will show 0.0.9, however it would appear that there is still a problem with node-red failing to be able to install. It's possible it can't cope with installing our nodes because of native compilation and the large amount of output it generates.

**Comment by davidkel** [comment]
raised issue https://github.com/node-red/node-red/issues/1488 to see if they can do something.

**Comment by davidkel** [comment]
Node-red have now fixed this issue. Closing
