### ISSUE TITLE
Generated networkadmin.card doesn't match the one imported into fabric

### ISSUE THREAD

**Issue by hexelon** [hyperledger/composer#2803]
When creating a network I also generate a networkadmin.card, if i try to use this card later in the api it doesn't match the card stored inside the chaincode container.

## Context
I'm creating a basic network, and when running:

composer network ping -c admin@test-network 

Everything works and i receive:

```
The connection to the network was successfully tested: intonet-network
	version: 0.15.1
	participant: org.hyperledger.composer.system.NetworkAdmin#admin

Command succeeded
```

This should work the same in the composer-rest-server with multiuser and authentication with the networkadmin.card generated during the network create but it doesn't

## Expected Behavior
I run the rest server with:
`composer-rest-server -c admin@test-network -n never -a true -m true -w true`

1.  Authenticate with github as in the tutorial
2. Register networkadmin.card to the wallet 
3. Check that the card is in the wallet

Doing /system/ping should return the same results as the cli but i get: **"Error: The current identity has not been registered: admin"**

## Actual Behavior
Doing /system/ping should return the same results as the cli but i get: **"Error: The current identity has not been registered: admin"**

## Possible Fix
What fixed for me was using card export and using the newly created card instead of the one generated during the network creation

## Steps to Reproduce
1. Build the network in the tutorial
2. Run composer-rest-server -c admin@test-network -n never -a true -m true -w true
3. Authenticate with github
4. Register the networkadmin.card card in wallet
5. Try to run /system/ping 

## Your Environment
node.js 8.9
composer 0.15.1
osx

**Comment by sstone1** [comment]
@hexelon you need to `composer card export`  the card once you have tested the connection using `composer network ping`. This is because the card file you have only contains an enrolment ID and secret (and no enrolment certificates), which means the REST server will perform a enrolment operation. This results in new enrolment certificates that the business network does not recognize, resulting in the error. By running `composer card export` after `composer network ping`, you get a card file that contains enrolment certificates.
