### ISSUE TITLE
Admin cards only work in Playground after reimport

### ISSUE THREAD

**Issue by erNail** [hyperledger/composer#2844]
## Context
I've just created my own network with multiple orgs following the [multi-org-tutorial](https://hyperledger.github.io/composer/tutorials/deploy-to-fabric-multi-org.html). After successfully deploying the BNA, importing the admin cards and pinging the network, i've tried to use the Playground to access the network. However, when using the card-files from the card-storage `~/.composer` (Already available in the Playground), the Playground is stuck at `Please Wait: Connecting to Business Network maintenance-network using connection profile innovation-net-org1-only-mychannel`. 

But, when i execute a `composer card export -n org1-mychannel@maintenance-network -f org1.card`, and import this card into the Playground, it works without problems.

EDIT: Also, when reimporting the existing cards from `~/.composer` into the Playground, it also works.

## Expected Behavior
The cards should work in the Playground without the need to reimport them.

## Actual Behavior
The cards don't work without reimporting them.

## Your Environment

* Version used: v0.15.2
* Operating System and version (desktop or mobile): Ubuntu 16.04

**Comment by davidkel** [comment]
@erNail Just so I am clear, you have started a fabric network, created and used some cards using the CLI you have installed (using npm install) and they all ping successfully. You then start playground  (again installed through npm install) and the cards you have in your card store appear in playground but when you click on one that has a business network name defined in it you see the problem ?
When you do that where you have run playground you will see some debug output being produced. When you get the problem was information is output ?

**Comment by erNail** [comment]
@davidkel Yes, you understood everything correct. Right now i can't reproduce the error, since it's not happening everytime. I'll post the output as soon as i encounter the error again.

**Comment by erNail** [comment]
I'll close this issue, as i'm fairly certain that the problem is the performance of the Playground. While stuck at `Please Wait: Connecting to Business Network maintenance-network using connection profile innovation-net-org1-only-mychannel`, as soon as i enter `playground.url/editor`, connecting only takes some seconds. The reason because for it to work after a reimpoert, was that i deleted all cards and only imported the once i wanted to use. I opened a new issue for this: #3001
