### ISSUE TITLE
What is the best practice to detect a connection failure in composer-client?

### ISSUE THREAD

**Issue by RobTS** [hyperledger/composer#3013]
I built an application on top of composer, deployed a fabric instance into the cloud and have an application running connected to it.

However, if the connection fails for any reason, there seems to be no event fired or crash of the library. When I make another request, a very verbose text message will tell me the connection broke, but parsing that message that may change at any point in time does not seem like a good practice.

What is the recommended way to deal with this? I do not even expect automatic reconnects, some easy notification to crash the application upon would already be enough. Or do I have to instantiate a new connection for every request I make?

## Context

Other database connectors have events to listen to or automatic reconnection possibilities that can be used to crash the app or reconnect.

## Expected Behavior

Working ```.on('error',()=>{})``` handler would be nice for the connection or automatic reconnects.

## Actual Behavior

Connection dies without notification, only noticed by a long error String (not even an object with a status code) when making another request.

## Possible Fix
```.on('error',()=>{})``` handler implementation, automatic reconnect, plus documentation on the topic

## Steps to Reproduce

1. Start fabric, deploy a business network.
2. Have the composer client application connect.
3. Kill Fabric.
4. Make a request to fabric.

## Existing issues

None I am aware of or I could find upon searching.

## Context

Another "Context" field?

## Your Environment

* Version used: Fabric 1.0
* Environment name and version: Nodejs 8.9.2, Composer Client 0.16.0
* Operating System and version (desktop or mobile): Mac OS
* Link to your project: private

**Comment by RobTS** [comment]
Non-trivial issue or is there no one around that is able to answer that question?

**Comment by davidkel** [comment]
So this issue may be of some relevance #2799

**Comment by krabradosty** [comment]
Are there any updates?

**Comment by davidkel** [comment]
No updates as yet, waiting to see what capabilities are being delivered in the 1.1 alpha. There are no plans currently to provide anything for the 0.16.x release stream.

**Comment by davidkel** [comment]
with #3014 the hlfv1 connector will now tolerate event hubs being lost. For chaincode events a new peer will be located to receive chaincode events if the one it was connected to was lost. For Tx Events, these are only a guide to tell composer when to return control to the application, so control will be returned correctly if some peers are unavailable. The loss of an event hub may also indicate the loss of a peer, but we currently don't provide a callback to inform of that as we would only know of this if it were the peer that chaincode events were listening on or when a transaction was requested. The connector currently doesn't continually monitor all peer event hubs while a connection is established. However a peer doesn't have to be an event source, so this isn't the best way to monitor whether all peers are still available and working. The only way we know if a peer for tx requests is down is when it is submitted to the peer, however a peer being down is not a problem in an HA environment and as such the network can still be ok depending on other available peers and endorsement policy. Any peer that responds with an error be it a connection failure because it cannot be connected to or otherwise is logged as a warning but no feedback is given to the client as from a client point of view the network may still be working ok.

## Current status 
- The aim of the hlfv1 connector is to be able to not fail if peers go offline and to not exclude those peers when they come back oneline. This has been enhanced for event hubs, but still needs to be done for peers that are targetted for query requests
- The node-sdk has a limitation with which orderer it sends the details to and as such no toleration of loss of what the node-sdk calls the primary orderer is possible. see https://jira.hyperledger.org/browse/FAB-5565
- There is no HA capability for loss of a fabric-ca server covered in part by https://jira.hyperledger.org/browse/FAB-8331

I don't think a practical on Error event mechanism in the connector to inform an application of the loss of an eventhub/peer/orderer/ca is possible as only monitoring an event hub could do it outside of the application of making an actual request and that request will respond with a fail if the request just cannot be completed.

**Comment by davidkel** [comment]
The further action now for this, so closing
