### ISSUE TITLE
Broken relationships are allowed. Is this the best behavior?

### ISSUE THREAD

**Issue by lucasdf** [hyperledger/composer#3065]
Currently it is possible to create a relationship to an entity that does not exist and then store it in the Blockchain. Is this the best behavior or should Composer try to keep the integrity of relationships? What are the pro/cons of allowing broken relationships?

**Comment by lucasdf** [comment]
I raised this question on the Rocket chat and @mahoney1 wrote some thoughts about it https://chat.hyperledger.org/channel/composer?msg=2rWBMEK2mpJbDTRRf

**Comment by sstone1** [comment]
This is the best behaviour; to try and preserve integrity of relationships would be a near impossible task. It _might_ be easier if we had a better underlying database technology, such as graph database, instead of CouchDB which has no concept of a relationship or foreign key.

Scalability: blockchain business networks are likely to be large; a participant may own 100/1000/10000s of assets. Trying to manage all of those relationships is a significant task - not impossible - but significant. Because relationships aren't bidirectional, unless you model them as so, in order to rename the participant you would have to find all of the assets (and any other entities) that reference that participant.

Access control: today it is possible for an asset to have a relationship to a participant - it's owner. Both of those entities could exist, but in the example a user might only have permission to view the asset and not the participant. From that users point of view, the relationship might appear "broken" as they cannot access the target of the relationship.

Futures: in the future we want to get to links, which would allow relationships to span across business networks - whether those business networks are in the same channel, different channels, different blockchains, or even just hosted on external services like HTTP/REST servers. Trying to maintain relationship integrity across those would be impossible.
