### ISSUE TITLE
Business card  from createPeerAdminCard script should have improved naming.

### ISSUE THREAD

**Issue by samjsmith** [hyperledger/composer#3115]
Testing the latest-unstable version of the release, I downloaded the latest fabric tools from `https://raw.githubusercontent.com/hyperledger/composer-tools/master/packages/fabric-dev-servers/fabric-dev-servers.tar.gz`. 
I then ran the start script to start the network and then the `createPeerAdminCard.sh` script which generated and imported a card for me. However, when I looked at it in Playground, I can see it's called `PeerAdmin@hlfv1` instead of the `PeerAdmin@hlfv11` which I'd expect given that I'd set the $FABRIC_VERSION environment variable.

In the discussion after, @mbwhite also suggested that the Organizations in the card could have more distinct names to help the users' experience and avoid potential confusion.

@davidkel Matthew suggested that you guys had discussed this before and there was a reason that v1 was used instead of v11 but couldn't remember what it was.

**Comment by sstone1** [comment]
The name `hlfv1` has traditionally been the name of the connection profile. It really is the name of the underlying blockchain or Fabric network. It's too easy to confuse it with the connection profile type, which is really an internal thing. If we're going to do *anything* in this area I'd like to see us change the name to `fabric-network` instead as that would make it a lot clearer.

You'd have cards for:
`PeerAdmin@fabric-network`
`admin@my-business-network`

`PeerAdmin` is also wrong because the name in the certificate is `Admin@org1.example.com` or something along those lines, but hey one thing at a time :smile:
