### ISSUE TITLE
How do I pass the secret of the private key to composer-rest-server?

### ISSUE THREAD

**Issue by jasoncys** [hyperledger/composer#3132]
`composer-rest-server` cannot handle password protected private key,

## Context
I want to enable HTTPS/TLS for my composer-rest-server and my private key is password protected. I can hardcode the `passphrase` for the private key in `composer-rest-server/server.js` to get around the problem. 

## Possible Fix
User should be prompted for the password for the private key.  Or adopt the approach for starting Apache web server where one needs to provide both the private key (some are password protected) and certificate.

## Your Environment
`composer version: v0.16.0

**Comment by jesusiglesias** [comment]
Same problem here. I would like to know if this option could be supported soon.

**Comment by Farbod29** [comment]
you can maybe find the solution here 👍 
 http://houseofding.com/2008/11/generate-a-self-signed-ssl-certificate-for-local-development-on-a-mac/

**Comment by jesusiglesias** [comment]
The ideal situation is that Composer Rest server checks if the key has a passphrase. If so it should request it and create a server passing all options (key, cert and passphrase -example below-), avoiding that the user has to modify the 'server.js' file. Otherwise, the connection should make as before with a key without passphrase. 

Example:

```
require('https').createServer({
    key: [key],
    cert: [cert,
    passphrase: [passphrase
}, app).listen(443);`
