### ISSUE TITLE
Improve multi-org tutorial

### ISSUE THREAD

**Issue by jt-nti** [hyperledger/composer#3148]
It would be nice to make it easier to follow the [Deploying a Hyperledger Composer blockchain business network to Hyperledger Fabric (multiple organizations)](https://hyperledger.github.io/composer/tutorials/deploy-to-fabric-multi-org) tutorial 

## Possible Fix

A few options...

- Clarify exactly which steps are necessary from the fabric documentation?

- Provide some validation steps/commands after completing the fabric steps to confirm that they were successfully completed?

- Duplicate fabric documentation so that it's not necessary to navigate away from the composer tutorial?

**Comment by jt-nti** [comment]
👆 @fenglianxu does that sound about right based on the retrospective? @rthatcher any thoughts?

**Comment by mahoney1** [comment]
Agree with all of the fixes above. The tutorial is not intuitive to follow, without some prior knowledge the Fabric BYFN setup and indeed having a tutorial-network.bna file built, when you may not have done the Developer tutorial recently or ever (there should be no dependency on this particular network).

I suggest the following additional changes:

- [ ] instruct user to enter fabric-samples directory explicitly, as a pre-req step to complete the 'curl' (next item)

- [ ] provide CURL command sequence to download platform-specific Binaries for version of Composer (16.x or >16.x) this tutorial is being used for. 

- [ ] Verification step to check Fabric is up and running following curl : check a list docker images appropriate to the Composer level
- [ ] Instruct user to `cd first-network` explicitly before next step (artifact generation)
- [ ] Verification that byfn 'generation of network artifacts' step shows artifacts for Org1 and Org2 in the listing (FYI: Verification that the 'BYFN "first network" generation' step already in the tutorial - ie shows a successful 'BYFN execution successfully completed' message.)
- [ ] Remove pre-dependency that you've built your BNA file (tutorial-network as it stands today) from another tutorial which you may not have done or not have the residual BNA for tutorial-network 'lying around' - just grab the 'trade-network.bna' sample network by exporting from Playground and use that.
- [ ] Make life easier for user (with key paths etc) and clearly instruct them to use '/tmp/composer' as the working directory (like we do for connection profiles for org1 org2)
- [ ] give 'copyable' instructions in tutorial for copying the cert and key for relevant Org Admin to org1 or org2 directory - with which to build the BN card
- [ ] 'Step four' should be like-for-like with 'Step three' (instruction for org2 use another 'copy' block)
- [ ] 'Step eighteen' and 'Step nineteen' should each have a 'composer participant add' and add an asset that is owned by the participant (submit transaction from CLI)
- [ ] 'Step eighteen' and 'Step nineteen' should each do a composer network list showing alice and bob are able to see 2 participants and 2 assets generated by bob and alice

**Comment by mahoney1** [comment]
have made the edits, and submitted a PR

**Comment by jpayne23** [comment]
Just a heads up, I've been going through this tutorial (Deploying to a multi-organisation Hyperledger Fabric) and ran into problems running the byfn script to start the network.

None of the docker images from hyperledger with the tag 'latest' could be found so I had to change the tag for all images being pulled to 'x86_64-1.0.5' for the script to work.

I know this is a Hyperledger Fabric script that's been forked but I imagine people will be turned off from going through this tutorial since you run into this problem in step one of the tutorial and there were several yaml files to find and update to fix this.

Happy to help out to fix this as well :)

**Comment by mahoney1** [comment]
hi Joe, assume you mean the 0.16.x tutorial? - ie link [here](https://hyperledger.github.io/composer/tutorials/deploy-to-fabric-multi-org). The 0.16.x tutorial needs changing (as the instructions aren't really that clear, incl your info above), whereas 0.17.x  tutorial [here](https://hyperledger.github.io/composer/next/tutorials/deploy-to-fabric-multi-org) is more prescriptive.

**Comment by jpayne23** [comment]
Hi Paul, that's right. It was the 0.16.x tutorial I was following. It might be worth putting a note at the start of this tutorial while it is being updated to let people know.

**Comment by mahoney1** [comment]
hi Joe -thanks!  I have the changes in my Github fork. I'm (furthemore) trying to add using cert contents (rather than paths) in the profiles,  to go with the clearer instructions and extra business network checks/tests that will show multi-org with multiple blockchain identities interacting on the same business network.  Will submit a PR in the next day or so for the 0.16.x branch.

**Comment by eguliev** [comment]
Guys, I'm just following this [tutorial](https://hyperledger.github.io/composer/latest/tutorials/deploy-to-fabric-multi-org) and at the step 18 after submission of : composer network ping -c alice@trade-network got the following error: Error: Error trying to ping. Error: 2 UNKNOWN: make sure the chaincode trade-network has been successfully instantiated and try again: could not find chaincode with name 'trade-network'  . I would highly appreciate your assistance.

**Comment by mahoney1** [comment]
Suggest to post your 0.19.0 multi-org tutorial issue / question on [Stack Overflow](https://stackoverflow.com/questions/tagged/hyperledger-composer) tagging it with hyperledger-composer - when writing the question, follow the ticket format / info required here -> https://github.com/hyperledger/composer-knowledge-wiki/blob/master/knowledge.md#issue  and include your screenshot and the preceding commands. It may just be a timing issue (doing the ping) - did you try it again (assuming your same fabric-network is still up). Anyway, you can post this on SO. Thanks (this 'issue' list is really for bugs, enhance requests etc rather than a support channel).

**Comment by phanikumar1210** [comment]
Most of the organizations looking for multi-org setup using multiple VM's. It will be nice if there is a document on how this can be achieved.
