### ISSUE TITLE
As a user I would like an equivalent composer sample to the fabric's high-throughput sample

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#3238]
This question has come up a lot on RC asking how to perform high throughput through composer referencing the following fabric sample as the driving reason
https://github.com/hyperledger/fabric-samples/tree/release/high-throughput

**Comment by labcoinpoc** [comment]
I am building a simple payment experiment project in my office and I also met the same problem. It is OK with customer's account but the store owner cannot receive money twice during one block. So I made a new model just like the high-throughput Fabric. Since Composer dose not support composite key right now, I just create new assets to store deltas of balance, then define a transaction which can merge all deltas into user's balance and then delete all of them. The payment server automatically send the merge transaction every midnight. When reading user's balance, the server reads balance and all un-megrged deltas then calculate them together. In my test the new model can process 50 transactions per second to edit the same account, not very high but enough for my project.
