### ISSUE TITLE
 Allow REST to receive a card as API argument

### ISSUE THREAD

**Issue by lucasdf** [hyperledger/composer#3260]
It would be interesting to be able to pass a Composer card as an argument to the APIs. That way, API consumers would be able to pass their cards to assume an identity. This would allow multiple users to be supported without the need to store the card in a database (and maintain a cluster of dbs). That would also allow multiple users to be supported without the need to enable authentication. The users would authenticate themselves by passing the card.

My initial idea is to receive the card as a header, like `X-Composer-Use-Card`. Then, the card would be imported in a way similar to what is done [here](https://github.com/hyperledger/composer/blob/master/packages/composer-rest-server/common/models/card.js#L257), but using a randomized name. Once imported, the card would be set like it is done [here](https://github.com/hyperledger/composer/blob/master/packages/composer-rest-server/server/boot/composer-runtime.js#L57). After `loopback-connector-composer` finishes using the card/invoking commands, then the card would be deleted from the connection.

Is there any drawback that I am not considering? Would this fit into the rest server design? Is the card import operation expensive enough to reconsider implementing this?

I am interested in working on this one, so I welcome any ideas or suggestions.

**Comment by sstone1** [comment]
@lucasdf establishing a business network connection is an expensive process, I'm not sure you'd want to do it on a per-request basis. You'd also have to ensure that the card specified only contained certificates and not an ID/secret. This is because just having an ID/secret will trigger the enrolment process to occur, and we would have no way to store the new enrolment certificates back into the card.

**Comment by mataide** [comment]
Agree

**Comment by Rmannn** [comment]
Any news on this ?
