### ISSUE TITLE
Playground: Array with value null, [] or undefined is filled with the transaction invoker their resource string

### ISSUE THREAD

**Issue by DalderupMaurice** [hyperledger/composer#3418]
Array with value null, [] of undefined is filled with the transaction invoker

## Context
I have 2 optional arrays in my model defined. as these are optional, their initial values are undefined.
Whenever I now invoke any transaction, these arrays are filled with the invoker their resource reference and it is pushed inside the array resulting in both arrays having 1 item in them.
If I initialize the array with [] or null I get the same behavior, only when I have 1 initial value in the arrays, they work as intended.

## Expected Behavior
Empty arrays should remain empty and not auto-filled with the invoker their resource string/id.

## Actual Behavior
They array (located in the parameter of the function itself) is filled with the invoker their resource string/id

## Possible Fix
Don't explicitly fill any empty array.

## Steps to Reproduce
1. Define an asset with an optional array 
```
asset X identified by XX {
  o String XX
  o String[] randomArray optional
}
```
2. Define a transaction with a reference to the asset
```
transaction InvokeX {
  --> X x
}
```
3. Create the asset WITHOUT inserting data into the randomArray (through testUI in playground)
4. Invoke transaction en log the parameter in the function
```
function InvokeX(myParam){
  var currentSigner = getCurrentParticipant();
  console.log(myParam);
}
```

Although the asset created has an EMPTY array, the console log will show the array filled with the invoker their resource string/id

## Context
Unable to develop unless initializing the array with random - irrelevant data

## Your Environment
Playground website (online, NOT local)

**Comment by DalderupMaurice** [comment]
Additional:
```
function InvokeX(myParam){
  console.log(myParam); --> myParam.randomArray exists with 1 item -> invoker their resource string
}
```

```
function InvokeX(myParam){
  console.log(myParam); --> myParam.randomArray DISAPPEARED due to the .length, why??
  console.log(myParam.randomArray.length); --> returns undefined
}
```

**Comment by DalderupMaurice** [comment]
Additional 2:

IF the array is initialized with a random value (ex: randomArray[0] = "test";)
```
function InvokeX(myParam){
  // myParam.randomArray SHOULD have 1 item which is "test'
  console.log(myParam); --> myParam.randomArray has 1 item.. the invoker his resource string...

  myParam.randomArray = [];
  console.log(myParam) --> myParam.randomArray has 1 value.. the invoker his resource string...
}
```

**Comment by mahoney1** [comment]
hi there

two things

1. myParam is the transaction - so you will see:

Invoke is Resource {id=org.acme.trading.InvokeX#2666a12d-6b91-49a9-bba2-57560da6a684}

And in Historian:
    {
 "$class": "org.acme.trading.InvokeX",
 "x": "resource:org.acme.trading.X#2000",
 "transactionId": "2666a12d-6b91-49a9-bba2-57560da6a684",
 "timestamp": "2018-02-16T15:20:11.508Z"
}

(ie the transaction reference in the InvokeX transaction registry).

2. I think your code SHOULD look like the following:

/**
 * Track the trade of a commodity from one trader to another
 * @param {org.acme.trading.InvokeX} myParam - the trade to be processed
 * @transaction
 */
function InvokeX(myParam){

     console.log("Invoke is: " + myParam);
     console.log("randomArray submitted is:  " + myParam.x.randomArray);
     console.log("1st element in randomArray is:  " + myParam.x.randomArray[0]);
  
     myParam.x.randomArray = [];
 
     console.log("randomArray is now:  " + myParam.x.randomArray);
  
}

output:

Invoke is:  Resource {id=org.acme.trading.InvokeX#a405d65e-5f61-41ef-a988-36145efc292f}  
randomArray submitted is:  test  
1st element in randomArray is:  test  
randomArray is now:                       // _null_

I'm not seeing the issue you're seeing - mainly for reasons above - . I just tried in online playground?

**Comment by DalderupMaurice** [comment]
Thanks for the quick reply! I'll have a try with it and report back!

**Comment by DalderupMaurice** [comment]
Your code gives me the same/intended input. But my old function is still doing the weird "bug".
Although I do a console.log on the first line of the function, the array is filled with my invoke user.

Btw, when doing: 
```      console.log("Invoke is: ", myParam);  
or   
 console.log(myParam)```
You get the complete object and can toggle down to x --> randomArray and see the value. This is where I saw that it was already initialized.

**Comment by DalderupMaurice** [comment]
I have found the difference.
Im my code. the first line of code looks like this:
` var currentSigner = getCurrentParticipant();`
Comment this line out gives me the wanted result, but now I am unable to check whether the function is executed by the desired user.

**Comment by mahoney1** [comment]
hello,

You wrote:

_Although I do a console.log on the first line of the function, the array is filled with my invoke user._

I don't see what problem you are having - happy to be wrong.

As mentioned (going on your last comment above), you're doing a console.log of the **transaction object**.  I've included some sample reference code below with randomArray not defined at all, or set to null (your initial question),  or set to 'something' .  Having the `getCurrentParticipant()` line in or out should not make any difference (and it doesn't for me at least). 

When you pass in a transaction object its because you want to achieve some deterministic transaction logic (ie you would not edit the input parameter). Assigning to `var` is standard javascript  - I suggest to look at the sample networks here -> https://github.com/hyperledger/composer-sample-networks/tree/v0.16.x/packages and have a look at how functions and transaction processors are used - also see here -> https://hyperledger.github.io/composer/reference/js_scripts
```
/**
 * Test code for Dalderup using trade-network sample
 * @param {org.acme.trading.InvokeX} myParam - the trade to be processed
 * @transaction
 */
function InvokeX(myParam){
  
  var currentSigner = getCurrentParticipant();
  
  console.log("current participant is: " + currentSigner);
  
  console.log("Invoked transaction is: " + myParam);
  
  console.log("passed X asset is: " + myParam.x);
  
  console.log("randomArray object is: " + myParam.x.randomArray);

  console.log("1st element in randomArray is: " + myParam.x.randomArray[0]);

 // myParam.randomArray = []; // your original code FYI, commented out
  myParam.x.randomArray = [];
 
  console.log("randomArray is now empty: " + myParam.x.randomArray);
  
}
```
with an empty randomArray submitted (its an optional field in any case)

yields:


randomArray object  is: undefined   // 'passed in'
current participant is: Resource {id=org.acme.trading.Trader#1}  // my participant identity is #1
Invoked transaction is: Resource {id=org.acme.trading.InvokeX#76fba3bf-18d9-414a-8349-de73e23bd070}
passed X asset is: Resource {id=org.acme.trading.X#2080}    // relationship object
randomArray object is:  undefined   // you set it so in your code.

<< cannot get first element of array - there is none define - throws >>

I am closing this issue based on what you've provided in your comments - suggest to open a new issue, with the concise problem definition,  if you feel there is a genuine bug that you can demonstrate is replicable - thank you
