### ISSUE TITLE
Breakage in the aggregation of criteria in queries

### ISSUE THREAD

**Issue by sun337** [hyperledger/composer#3460]
The aggregation of operators dosen't work in Query language
### Context

Example:
```
asset Order identified by orderId {
    o String orderId
    o OrderType orderType
    o OrderStatus orderStatus default = 'PENDING'
    o Double bidTokenPrice
    o Double tokenQuantity
    o DateTime orderTime
    --> User orderer
    --> Property property
}
```
The query below doesn't work as expected
 ```
query Q_BUY_SELL{
  description: "Select filtered Orders "
  statement:
    SELECT namespace.Order
        WHERE (orderType == _$filterType AND orderStatus == _$filterStatus AND bidTokenPrice == _$bidTokenPrice AND orderer == _$orderer AND property == _$property )
}
```

### Expected Behavior

Query should return results filtered with all 5 conditions. 
**(1 AND 2 AND 3 AND 4 AND 5)**
### Actual Behavior

Query returns results filtered with only first and last conditions, irrespective of what order they are defined in. 
**(1 AND 5)**

### Existing issues

- [ ] [Link to the issue on Stack Overflow](https://stackoverflow.com/questions/48926230/hyperledger-composer-queries-not-returning-expected-result)

**Comment by sun337** [comment]
## Steps to reproduce
Try the following out with the trade-network from online playground https://composer-playground.mybluemix.net/ (deploy trade-network sample) 

### STEP 1 : Define the following 
**Tx Processor Function**
```
/**
 * Try access elements of an array of B assets
 * @param {org.acme.trading.Qry} qry - function to access A elements (and B assets)
 * @transaction
 */
function myQryfunc(qry) {
    return query('myQryTest', {
      "tradingSymbol": "1",
      "description": "2",
      "mainExchange": "3",
      "quantity": 4,
      "owner": "resource:org.acme.trading.Trader#1"
    })
    .then(function (results) {
       var promises = [];
       for (var n = 0; n < results.length; n++) {
        var asset = results[n];
               console.log('Query result is ' + (n+1) + ', object is ' +  asset);
               console.log('Asset identifier is ' + asset.getIdentifier());
       }

    }); 
}
```
**Query definition**
```
query myQryTest {
  description: "Select all commodities"
  statement:
      SELECT org.acme.trading.Commodity
         WHERE (tradingSymbol != _$tradingSymbol AND (description == _$description OR description == _$description) AND mainExchange == _$mainExchange AND quantity == _$quantity AND owner == _$owner )
}
```
**Model definition** for Qry transaction (to call it in playground)

```
transaction Qry {
    --> Commodity commodity
}
```
### STEP 2 : 
a) Create a Trader with **tradeId: 1** record in the Participant. 
b) Create the following Commodity:
```
{
  "$class": "org.acme.trading.Commodity",
  "tradingSymbol": "1",
  "description": "2",
  "mainExchange": "3",
  "quantity": 5,
  "owner": "resource:org.acme.trading.Trader#1"
}
```

### STEP 3 :
Submit the txn 'Qry'. 

### RESULTS :
**The log in console should be empty because there is no Commodity with quantity: 4 (see the txn processor fn).
But it is still returning the only Commodity (which has quantity: 5)**

**Comment by rthatcher** [comment]
I've tested and seen similar results in v0.16.3  
I have retested some of the queries in v0.17.6 - and they work as expected.

**Comment by mahoney1** [comment]
hi there - I used ONLINE PLAYGROUND which is v0.16.4 - note - I did not choose to test the condition ( description == _$description or description == _$description) in my test (which originally just used to see if the query string size was a restriction). From testing, it breaks at more simpler forms of query strings in a .qry file.

With online playground - 0.16.4 - and given my build query in my Transaction processor javascript as follows (note I had 3 other records in my Commodity Asset registry, none of which should match anything below - but there anyway, to see if I get bogus matches etc

return query('myQryTest', {
  "tradingSymbol": "3",
  "mainExchange": "3",
  "quantity": 4,
 "owner": "resource:org.acme.trading.Trader#1",
    "description": "22"
   })


TEST 1 - Query def, followed by results

query myQryTest {
  description: "Select all commodities"
  statement:
      SELECT org.acme.trading.Commodity
         WHERE ( tradingSymbol == _$tradingSymbol AND mainExchange == _$mainExchange AND quantity == _$quantity AND owner == _$owner AND description == _$description )
}

ALL CONDITIONS MATCHED - WILL RETURN THE RIGHT RESULTS


{
  "$class": "org.acme.trading.Commodity",
  "tradingSymbol": "3",
  "description": "22",
  "mainExchange": "3",
  "quantity": 4,
  "owner": "resource:org.acme.trading.Trader#1"
}

TEST 2 - Query definition (below) with 1 negation in CONDITION match - specifically negation on a relationship field ($owner) - , followed by results - I should NOT get any records

query myQryTest {
  description: "Select all commodities"
  statement:
      SELECT org.acme.trading.Commodity
         WHERE ( tradingSymbol == _$tradingSymbol AND mainExchange == _$mainExchange AND quantity == _$quantity AND owner != _$owner AND description == _$description )
}

FAILURE: I get this row back (seems to ignore the comparison on the owner field which is a relationship field)

{
  "$class": "org.acme.trading.Commodity",
  "tradingSymbol": "3",
  "description": "22",
  "mainExchange": "3",
  "quantity": 4,
  "owner": "resource:org.acme.trading.Trader#1"
}

 
TEST 3 - Same Query def as TEST 2, but slight amend on actual asset record - change the asset 'owner' to become ""resource:org.acme.trading.Trader#2" now - again test negation on relationship field - SHOULD now a match)

query myQryTest {
  description: "Select all commodities"
  statement:
      SELECT org.acme.trading.Commodity
         WHERE ( tradingSymbol == _$tradingSymbol AND mainExchange == _$mainExchange AND quantity == _$quantity AND (owner != _$owner) AND description == _$description )
}

ALL CONDITIONS MATCHED (ie a record 'not' owned by the owner Trader#1 shows up)  - I GET THE CORRECT RESULTS - BUT - IS IT IGNORING THE COMPARISON ANYWAY ON OWNER?

{
  "$class": "org.acme.trading.Commodity",
  "tradingSymbol": "3",
  "description": "22",
  "mainExchange": "3",
  "quantity": 4,
  "owner": "resource:org.acme.trading.Trader#2"
}

TEST 4 - Same Query def as TEST 1 - same asset record as TEST 1 - but  - change the quantity (a Double field) to either 3 or 3.01 in the asset record - should not get a match.


query myQryTest {
  description: "Select all commodities"
  statement:
      SELECT org.acme.trading.Commodity
         WHERE ( tradingSymbol == _$tradingSymbol AND mainExchange == _$mainExchange AND quantity == _$quantity AND owner == _$owner AND description == _$description )
}

FAILURE: I get this row back (seems to ignore ANY comparison whether relationship or double field ?)

{
  "$class": "org.acme.trading.Commodity",
  "tradingSymbol": "3",
  "description": "22",
  "mainExchange": "3",
  "quantity": 4,
  "owner": "resource:org.acme.trading.Trader#1"
}

TEST 5 - change my original 'myQryTest'statement in my JS code and put in any old rubbish for the owner comparison string" AND set mainexchange to = "2" - should not get a match

return query('myQryTest', {
  "tradingSymbol": "3",
  "mainExchange": "2",
  "owner": "anyoldrubbishhkjhkjkjhr",
    "quantity": 4,
    "description": "22"
   })

FAILURE: I get this row back (seems to ignore ANY comparison (as two conditions fail) and doesn't even stop a match because the mainexchange in my 'myQryTest' is 2 and the asset record is '3' !

{
  "$class": "org.acme.trading.Commodity",
  "tradingSymbol": "3",
  "description": "22",
  "mainExchange": "3",
  "quantity": 4,
  "owner": "resource:org.acme.trading.Trader#1"
}

TEST 6 - remove relationship field, remove its comparison in the query and re-test  

return query('myQryTest', {
  "tradingSymbol": "3",
  "mainExchange": "2", // pls note
      "quantity": 4,
    "description": "22"
   })

FAILURE: I get this row back (seems to ignore ANY comparison (as two conditions fail) and doesn't even stop a match because the mainexchange in my 'myQryTest' is 2 and the asset record is '3' !

{
  "$class": "org.acme.trading.Commodity",
  "tradingSymbol": "3",
  "description": "22",
  "mainExchange": "3",
  "quantity": 4,
  "owner": "resource:org.acme.trading.Trader#1"
}


TEST 7 - remove quantity and relationship field - just 3 fields following on from above tests - should not get a match (mainexchange is 2 in query, 3 in the asset record)

return query('myQryTest', {
  "tradingSymbol": "3",
  "mainExchange": "2",    /// pls note
  "description": "22"
   })

query myQryTest {
  description: "Select all commodities"
  statement:
      SELECT org.acme.trading.Commodity
         WHERE ( tradingSymbol == _$tradingSymbol AND mainExchange == _$mainExchange AND description == _$description )
}

FAILURE: I get this row back (seems to ignore comparison of mainexchange with value 2 and yet the asset record is '3' - why would this fail now?)

{
  "$class": "org.acme.trading.Commodity",
  "tradingSymbol": "3",
  "description": "22",
  "mainExchange": "3",
  "quantity": 4,
  "owner": "resource:org.acme.trading.Trader#1"
}

**Comment by markcastle3** [comment]
We believe this has no being fixed after yesterday's fixes in this area. Please reopen if this is not the case

**Comment by HoneyShahOX** [comment]
It is expected that pagination should work correctly. Though I am getting all records by using following query.

`query AllFlightsSkipLimit {
  description: "Limits the number of flights returned"
  statement:  
    SELECT  org.acme.airline.flight.Flight
      LIMIT  _$limit 
       SKIP   _$skip
}`
