### ISSUE TITLE
Cannot export my card from the Playground

### ISSUE THREAD

**Issue by uluhonolulu** [hyperledger/composer#3478]
In the Playground docs (https://hyperledger.github.io/composer/playground/id-cards-playground) is says that the card can be exported using the export icon. However, this icon is always disabled (even on the video in the docs that explais how to create a card and on the Playground tutorial video on https://www.ibm.com/developerworks/cloud/library/cl-model-test-your-blockchain-network-with-hyperledger-composer-playground/index.html).

## Expected Behavior
I should be able to export the Business Network Card

## Actual Behavior
The Export icon is disabled

## Steps to Reproduce

1. Open https://composer-playground.mybluemix.net/login
2. Deploy a network
3. Return to the list of networks
4. The Export icon is disabled

**Comment by nklincoln** [comment]
Hi @uluhonolulu,

The reason that the export is greyed out is because you are using the bluemix staged Playground that is in the 'web-connector' mode. In order to meaningfully export a business network card, you will need to create a connection to Hyperledger Fabric. The steps you outline above will not create a business network in Hyperledger Fabric, but within a web connector.

If you follow the developer tutorial (https://hyperledger.github.io/composer/tutorials/developer-tutorial) you will be taken through the process of creating a (local) Fabric, from which you can connect Playground and export business network cards.

**Comment by uluhonolulu** [comment]
@nklincoln thanks! So I'm installing Playground locally, connect to my local Fabric, create a Business Network using Playground, and deploy it to Fabric, and then I'll be able to export a card. Is that correct?
