### ISSUE TITLE
When creating an app with yo hyperledger-composer:angular it always defaults to bond-network

### ISSUE THREAD

**Issue by gente21** [hyperledger/composer#3607]
By using yo hyperledger-composer:angular I expect to have an app created according to the model that I provide as a .bna, according to the documentation: [https://www.npmjs.com/package/generator-hyperledger-composer](https://www.npmjs.com/package/generator-hyperledger-composer) however, it always creates a bond-network.

## Expected Behavior

When using the yo hyperledger-composer:angular wizard, the app created should reflect the model that you provide when asked: "What is the name of the business network archive file?"

## Actual Behavior

It always defaults to bond-network, no matter if your .bna was created from another sample network.

## Steps to Reproduce

1. Create a .bna file using any of the sample networks found at: [https://github.com/hyperledger/composer-sample-networks/tree/master/packages](https://github.com/hyperledger/composer-sample-networks/tree/master/packages)
2. Run yo hyperledger-composer:angular and feed the wizard with the file that you just created
3. Upon running the server with composer-rest-server you will have access to the REST endpoints @ http://localhost:3000.
4. You will see the endpoints from bond-network, not the one that you provided as .bna

## Your Environment

* Version used: 0.16x
* node.js 8.10
* Ubuntu 16

**Comment by gente21** [comment]
A workaround for this is regenerate the business network archive as shown on: [https://hyperledger.github.io/composer/tutorials/queries](https://hyperledger.github.io/composer/tutorials/queries)

The steps are:
`composer archive create --sourceType dir --sourceName <folder of the model that you want> -a test-network@0.0.1.bna

composer network update -a test-network@0.0.1.bna -c admin@test-network
`

After this, run the server and you should see the endpoints that correspond to the correct type of network.

**Comment by zachgoll** [comment]
It most likely is happening because you have existing Docker containers running in the background.  To solve (Mac):

1. Delete any unnecessary cards from ~/.composer/cards
2. Remove unnecessary Docker containers

If you don't have any important Docker containers running on your machine, just run:

```
docker kill $(docker ps -q)
docker rm $(docker ps -aq)
docker rmi $(docker images dev-* -q)
```

3. In fabric-tools, run `./stopFabric.sh` and `./teardownFabric.sh`
4. In fabric-tools, run `./startFabric.sh`, and `./createPeerAdminCard.sh`
5. In root of project, run `mkdirp ./dist && composer archive create -t dir -n . -a ./dist/<your-network>.bna`
6. `composer runtime install -c PeerAdmin@hlfv1 -n <your-network>`
7.  `composer network start -c PeerAdmin@hlfv1 -A admin -S adminpw -a ./dist/<your-network>.bna -f networkadmin.card`
8. `composer card import --file networkadmin.card`

Now, try generating the angular application.  Should work fine!

**Comment by lesleyannjordan** [comment]
Closing; Given that 0.19 is now the latest replacing 0.16 we won't do any further enhancements for 0.16.x in this respect.

**Comment by VarunLashkari** [comment]
I have a sample POC where in the data of a patient can be flowing on a network where in different individuals can participate if they are patients or hospitals or doctors or clinics or pharmacies wherein each one can be given access of the patient records wherever and whenever required and the access to that particular health record can be revoked when the transaction between the involved parties is executed.This will protect patient data thefts which is a growing concern for future days in the medical industry. I have tried to implement this on Hyperledger Composer partially and I am seeking for help in creating peers and admin card that can not be queried for get request in my rest-server .I have used logic file from pii network template please help me if you can help me in any way.
