### ISSUE TITLE
Common connection profile certs inclusion

### ISSUE THREAD

**Issue by litong01** [hyperledger/composer#3623]
next gen common connection profile includes many certs, this creates some rather big problems:

1. embed many certs in a json file makes json file not readable which is against common usage of json file which is to make the file human readable.
2. certs are required to be altered (insert new line escape) to satisfy json validation, doing this is painful and error prone.

I would suggest to do the following:

1. Use a compressed file instead of a single json file as a connection profile
2. The json file should be at the root of the package
3. The json file use url to locate various certificates
4. Url can be remote or local, if it is local, then the cert should be inside of the package relative to the json file, if it is remote, then cert get retrieved over https or http.

**Comment by litong01** [comment]
this issue is real and need to be addressed. Someone please!!!

**Comment by jt-nti** [comment]
Business network cards are already in a zip file format. I wonder if the connection profiles they contain could include references in the json rather than the actual certificate content. If not, I guess this would need to be addressed in Fabric.

**Comment by bestbeforetoday** [comment]
Possibly this could be addressed in the code that loads the business network card: `IdCard.fromArchive` and `IdCard.fromDirectory`. After parsing the _connection.json_, look for certificate entries that are file names rather than embedded certificates, and load these files from within the card archive and tack them into the object representation of the connection profile.

Alternatively, maybe the best place to handle this from a Composer perspective is in the `composer card create` command. Do the resolution of external certificate files described above and embed the certificate content into _connection.json_ that gets included in the card archive. Then none of the downstream code needs to worry about resolving external certificate content.

It is important for the certificates to actually live inside the card (not reference external files and/or URLs) to make it truly portable.

**Comment by litong01** [comment]
connection profile should be made an archive file which includes all the certs. When user asks for the connection profile, the server should make that available. We can not ask users writing more code to deal with connection profile. We really have to fix this problem. The way it is implemented today made the yaml not edible by humans and create huge files when there are many peers in orgs, and the worst is alter the certificates which nobody will want to do that. Certs should be their own file period and always.

**Comment by jt-nti** [comment]
@litong01 you're right, it probably does make more sense to fix this properly in the connection profile rather than working around it in Composer. Connection profiles are part of Fabric so you'll need to create a new JIRA issue http://hyperledger-fabric.readthedocs.io/en/latest/CONTRIBUTING.html#reporting-bugs

I'll close this issue for now but I suspect that some work will be required if Fabric do change the common profile spec. Thanks for submitting the issue, and for the reminder- sorry it got missed originally.
