### ISSUE TITLE
Invoking composer network from another testing

### ISSUE THREAD

**Issue by lesleyannjordan** [hyperledger/composer#3657]
- [ ] Title and menu reference is "Invoking a Hyperledger Composer business network from another business network" Please consider shortening.

 - [ ]  Step Two point 1 -> calls out to run developer tutorial - within Developer Tutorial -> Step Two Adding access control -> says **create** a permissions.acl -> the generator now seems to create one...so should be **replace contents**

 - [ ]  Also in  Developer tutorial -> Step  Four point 3 -> composer card import --file **networkadmin.card**  -> should be referring to **networkA.card** which is generated in point 2.

 - [ ]  Steps Six and Eight -> would be useful to show the impact on networkB - is the amount removed from networkB???

**Comment by caroline-church** [comment]
"Also in Developer tutorial -> Step Four point 3 -> composer card import --file networkadmin.card -> should be referring to networkA.card which is generated in point 2." - this is not an issue in the developer tutorial or the invoking another business network tutorial. 

Other things have been fixed in referenced pull request

**Comment by caroline-church** [comment]
fixed so closing
