### ISSUE TITLE
After deleting a card in the filesystem, some of the credentials are still there

### ISSUE THREAD

**Issue by mbwhite** [hyperledger/composer#3702]
Add a card to the file system, and use it with a network eg `composer network list`
Then remove it `composer card delete`

There are some bits of the client-data left behind.

**Comment by davidkel** [comment]
@mbwhite does this affect all the wallet implementations or just file system ?

**Comment by mbwhite** [comment]
Would like to resolve this...

**Comment by davidkel** [comment]
This looks like to be the cause of some issues people see around the admin identity retrieved from the fabric-ca-server.

Scenario
1. start a business network using -A admin -S adminpw
2. import the card and ping it
3. restart fabric
4. start a business network using -A admin -S adminpw
5. import the card fails
6. delete the admin card
7. import the card now works
8. ping the card (appears to work)
9. try to issue an identity using the card, fails
That's because the admin identity wasn't enrolled because it is still enrolled in the state store and is now not a valid identity for the fabric-ca-server.

**Comment by L1tR05** [comment]
Whenever you try to issue the new identity card for the same userid, it fails because there are remainings of the previous identity.
