### ISSUE TITLE
npm install fails behind corporate proxy

### ISSUE THREAD

**Issue by rudrasur** [hyperledger/composer#3741]
Package installation is failing behind the corporate proxy

running: sudo npm install -g composer-rest-server
Getting following error:
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated fs-promise@1.0.0: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated constantinople@3.0.2: Please update to at least constantinople 3.1.1
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN deprecated socks@1.1.9: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm WARN deprecated mailcomposer@4.0.1: This project is unmaintained
npm WARN deprecated buildmail@4.0.1: This project is unmaintained
/usr/bin/composer-rest-server -> /usr/lib/node_modules/composer-rest-server/cli.js

> dtrace-provider@0.8.6 install /usr/lib/node_modules/composer-rest-server/node_modules/dtrace-provider
> node-gyp rebuild || node suppress-error.js

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: unable to get local issuer certificate
gyp ERR! stack     at TLSSocket.<anonymous> (_tls_wrap.js:1105:38)
gyp ERR! stack     at emitNone (events.js:106:13)
gyp ERR! stack     at TLSSocket.emit (events.js:208:7)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:639:8)
gyp ERR! stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:469:38)
gyp ERR! System Linux 4.13.0-37-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/composer-rest-server/node_modules/dtrace-provider
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

**Comment by davidkel** [comment]
This isn't a problem specific to composer and is related to how you might have to set up your npm configuration. You can google for various solutions, for example a quick google found this
https://jjasonclark.com/how-to-setup-node-behind-web-proxy/. But the solution you need to adopt will depend on your company infrastructure so suggest you get help from your network support group as necessary.

**Comment by rudrasur** [comment]
@davidkel Thanks a lot for your quick reply, I did configured the required proxy settings. Please find my .npmrc file below:
![image](https://user-images.githubusercontent.com/7859582/38240204-94e75c5a-374c-11e8-9a1a-5bd598dce858.png)

npm install composer-rest-server is trying to install dependent module "pkcs11js" & it seems that the registry of pkcs11js different than registry.npmjs.org & certificate validation is failing for this module.

When try to run "npm install -g pkcs11js", I am getting the same error.

**Comment by davidkel** [comment]
@rudrasur It's odd that pkcs11 would be different to any other module, but again this won't be specific to composer but rather npm. All I can suggest is google your particular problem, for example
https://github.com/nodejs/help/issues/979

**Comment by rudrasur** [comment]
@davidkel I did google a lot & didn't find the solution. I understand that it's specific to pkcs11. But it's blocking me to proceed further in hyperledger composer setup. It would be really great if you find any solution for this. I think this should be common problem to everyone who working on composer behind corp proxy.
Once again, thank you so much for your time.

**Comment by davidkel** [comment]
@rudrasur unfortunately this isn't a common problem as we have heard of quite a few people running behind proxies for a long time now and they have never encountered this problem. Unfortunately I can't help any further and can only suggest you try some of the suggestions found on google.

**Comment by rudrasur** [comment]
Solution provided in nodejs/help#979 fixed the issue. Thank you @davidkel for your support.

**Comment by nitishbhushan2013** [comment]
This is exactly the same error I am getting in my local mac env running from my home network. 


nitishs-MacBook-Pro:archive nitishbhushan$ npm install -g composer-rest-server
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated constantinople@3.0.2: Please update to at least constantinople 3.1.1
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN deprecated mailcomposer@4.0.1: This project is unmaintained
npm WARN deprecated socks@1.1.9: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm WARN deprecated buildmail@4.0.1: This project is unmaintained
/Users/nitishbhushan/.nvm/versions/node/v8.11.2/bin/composer-rest-server -> /Users/nitishbhushan/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/cli.js
+ composer-rest-server@0.19.8
updated 9 packages in 125.311s


Till now, I have updated all the mentioned packages through npm but still problem persists.  I am in look out zone to get this sorted.

**Comment by nitishbhushan2013** [comment]
Below advise from other thread had worked for me 


down vote
you need to rebuild it

go to the folder first

cd '/root/.nvm/versi ons/node/v8.9.1/lib/node_modules/composer-rest-server/'
(into the folder where you have 'composer-rest-server')

then

npm rebuild --unsafe-prem
It will work now

Resource - https://stackoverflow.com/questions/47759395/error-while-generating-rest-api-using-hyperledger-composer-rest-server-in-centos
