### ISSUE TITLE
Composer network start not working in v0.19

### ISSUE THREAD

**Issue by aosti** [hyperledger/composer#3746]
I've executed the command composer network start -c PeerAdmin@energy-market -A admin -S adminpw -n energy-market -V 0.0.1 and received the following message as result :
`
Starting business network energy-market at version 0.0.1

Processing these Network Admins: 
	userName: admin

✖ Starting business network definition. This may take a minute...
Error: Error trying to start business network. Error: No valid responses from any peers.
Response from attempted peer comms was an error: Error: 2 UNKNOWN: error starting container: Failed to generate platform-specific docker build: Error returned from build: 1 "npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! request to https://registry.npmjs.org/composer-common failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org:443

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-04-03T13_55_10_936Z-debug.log
"
Response from attempted peer comms was an error: Error: 2 UNKNOWN: error starting container: Failed to generate platform-specific docker build: Error returned from build: 1 "npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! request to https://registry.npmjs.org/composer-common failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org:443

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-04-03T13_55_10_926Z-debug.log
"
Command failed
`
The same message can be seen in the peer logs. I've tried to see the content of the xxx-debug.log file, but it doesn't exist in the peer.
The previous command, composer network install, worked without any problems.

## Context

This worked back in composer v0.16 with Fabric 1.0, but now it fails. 
I've also tested the created fabric v1.1.0 network with a go chaincode and everything worked fine.

I'm using a 4 Orgs / 2 peers network that was working with Fabric 1.0 and also with Fabric 1.1.0 when using go chaincode.

## Existing issues
I've search through the issues here and stack overflow, but nothing looked similar to my problem.

## Your Environment

* Version used: Fabric 1.1.0, composer-cli 0.19.0
* Environment name and version (e.g. Chrome 39, node.js 5.4): v8.10.0
* Operating System and version (desktop or mobile): Ubuntu 16.04 64 bits
* Link to your project:

**Comment by aosti** [comment]
I just retried the command without restarting the machines and it worked now.

**Comment by davidkel** [comment]
Glad you got the problem solved.
For completeness EAI_AGAIN is a return code resulting from a DNS lookup timeout and is thus related to your network environment. Peers as part of a network start perform an NPM install to build the chaincode container image.

**Comment by RainbowArea** [comment]
I also havr same problem but when I retried the command again 4-5 times I stil get the same problem  
actually right now I am in China is it because about the Connection through the vpn ?  


✖ Starting business network definition. This may take a minute...
Error: Error trying to start business network. Error: No valid responses from any peers.
Response from attempted peer comms was an error: Error: 2 UNKNOWN: error starting container: Failed to generate platform-specific docker build: Error returned from build: 1 "npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! request to https://registry.npmjs.org/composer-runtime-hlfv1 failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org:443

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-06-19T12_37_57_067Z-debug.log
"
Command failed

**Comment by RainbowArea** [comment]
problem solved  by I click disable and enable network in UBUNTU  again.

**Comment by qq6690876** [comment]
I locate at china too, and meet the same problem. 
The problem logs 
✖ Starting business network definition. This may take a minute...
Error: Error trying to start business network. Error: No valid responses from any peers.
Response from attempted peer comms was an error: Error: 2 UNKNOWN: error starting container: Failed to generate platform-specific docker build: Error returned from build: 1 "npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! request to https://registry.npmjs.org/composer-common failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org:443

npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2018-04-03T13_55_10_936Z-debug.log
"
Response from attempted peer comms was an error: Error: 2 UNKNOWN: error starting container: Failed to generate platform-specific docker build: Error returned from build: 1 "npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! request to https://registry.npmjs.org/composer-common failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org:443

npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2018-04-03T13_55_10_926Z-debug.log

**Comment by hirsche** [comment]
I've got exactly the same issue! But I tried to get the registry manually using curl:
``curl --url https://registry.npmjs.org/composer-common
which worked perfectly. So it is not the network or at least I don't see how...

**Comment by mplescano** [comment]
I have this problem too:
`
⠙ Starting business network definition. This may take a minute...
✖ Starting business network definition. This may take a minute...
Error: Error trying to start business network. Error: No valid responses from any peers.
Response from attempted peer comms was an error: Error: failed to execute transaction db0ea1b08ead6546a3ed2b7a34edc1bb7fc67e524b6548a87afbb1d3aea08283: error starting container: error starting container: Failed to generate platform-specific docker build: Error returned from build: 1 "npm ERR! code ECONNREFUSED
npm ERR! errno ECONNREFUSED
npm ERR! FetchError: request to https://registry.npmjs.org/composer-runtime-hlfv1 failed, reason: connect ECONNREFUSED 104.16.26.35:443
npm ERR!     at ClientRequest.req.on.err (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/index.js:68:14)
npm ERR!     at emitOne (events.js:116:13)
npm ERR!     at ClientRequest.emit (events.js:211:7)
npm ERR!     at TLSSocket.socketErrorListener (_http_client.js:387:9)
npm ERR!     at emitOne (events.js:116:13)
npm ERR!     at TLSSocket.emit (events.js:211:7)
npm ERR!     at emitErrorNT (internal/streams/destroy.js:64:8)
npm ERR!     at _combinedTickCallback (internal/process/next_tick.js:138:11)
npm ERR!     at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR!  { FetchError: request to https://registry.npmjs.org/composer-runtime-hlfv1 failed, reason: connect ECONNREFUSED 104.16.26.35:443
npm ERR!     at ClientRequest.req.on.err (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/index.js:68:14)
npm ERR!     at emitOne (events.js:116:13)
`

And the reason is that I have my peer servers behind a proxy without to set the environment variable in those servers for security reasons.

So, my questions are:
* How can I set environment variables of proxy in the chaincode's containers?
* Why dont make a self-contained containers so that they dont pull files from internet?

Regards

**Comment by maheshbalan** [comment]
@mplescano I am getting exactly the same error, where you able to resolve this ?. When I try to start a business network in hlv1.1 composer 0.19, I am getting this error. I have tried passing the -o npmrcFile= options with the correct settings for proxy and https-proxy, no cigar. 

✖ Upgrading business network definition. This may take a minute...
Error: Error trying to upgrade business network. Error: No valid responses from any peers.
Response from attempted peer comms was an error: Error: 2 UNKNOWN: error starting container: Failed to generate platform-specific docker build: Error returned from build: 1 "npm ERR! code ECONNREFUSED
npm ERR! errno ECONNREFUSED
npm ERR! FetchError: request to https://registry.npmjs.org/composer-common failed, reason: connect ECONNREFUSED 104.16.20.35:443
npm ERR!     at ClientRequest.req.on.err (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/index.js:68:14)
npm ERR!     at emitOne (events.js:116:13)
npm ERR!     at ClientRequest.emit (events.js:211:7)
npm ERR!     at TLSSocket.socketErrorListener (_http_client.js:387:9)
npm ERR!     at emitOne (events.js:116:13)
npm ERR!     at TLSSocket.emit (events.js:211:7)
npm ERR!     at emitErrorNT (internal/streams/destroy.js:64:8)
npm ERR!     at _combinedTickCallback (internal/process/next_tick.js:138:11)
npm ERR!     at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR!  { FetchError: request to https://registry.npmjs.org/composer-common failed, reason: connect ECONNREFUSED 104.16.20.35:443
npm ERR!     at ClientRequest.req.on.err (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/index.js:68:14)
npm ERR!     at emitOne (events.js:116:13)
npm ERR!     at ClientRequest.emit (events.js:211:7)
npm ERR!     at TLSSocket.socketErrorListener (_http_client.js:387:9)
npm ERR!     at emitOne (events.js:116:13)
npm ERR!     at TLSSocket.emit (events.js:211:7)
npm ERR!     at emitErrorNT (internal/streams/destroy.js:64:8)
npm ERR!     at _combinedTickCallback (internal/process/next_tick.js:138:11)
npm ERR!     at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR!   message: 'request to https://registry.npmjs.org/composer-common failed, reason: connect ECONNREFUSED 104.16.20.35:443',
npm ERR!   type: 'system',
npm ERR!   errno: 'ECONNREFUSED',
npm ERR!   code: 'ECONNREFUSED',
npm ERR!   stack: 'FetchError: request to https://registry.npmjs.org/composer-common failed, reason: connect ECONNREFUSED 104.16.20.35:443\n    at ClientRequest.req.on.err (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/index.js:68:14)\n    at emitOne (events.js:116:13)\n    at ClientRequest.emit (events.js:211:7)\n    at TLSSocket.socketErrorListener (_http_client.js:387:9)\n    at emitOne (events.js:116:13)\n    at TLSSocket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)',

**Comment by mplescano** [comment]
> r

I had to create a new docker's image like this:
`FROM hyperledger/fabric-ccenv:latest
MAINTAINER mplescano@
ARG http_proxy
ARG https_proxy
ARG no_proxy
ENV http_proxy=$http_proxy
ENV https_proxy=$https_proxy
ENV no_proxy=$no_proxy
ENV npm_config_strict_ssl=false
ENV npm_config_registry="http://registry.npmjs.org/"
RUN npm config set strict-ssl false
RUN npm config set registry "http://registry.npmjs.org/"
`
and after building it I set this image in the configuration env in the peer like this:
- CORE_CHAINCODE_BUILDER=mplescano/fabric-proxied-ccenv:latest

**Comment by maheshbalan** [comment]
Thank you @mplescano so I presume I specify CORE_CHAINCODE_BUILDER in docker-compose.yml in the peer section ?

**Comment by maheshbalan** [comment]
@mplescano somehow when we look at the peer logs does not want to pick the CORE_CHAINCODE_BUILDER image. He goes back to using hyperledger/fabric-ccenv:s390x-1.1.0  (we are on zlinux)
SO we used FROM hyperledger/fabric-ccenv:s390x-1.1.0  when we built our own docker image

**Comment by vishrutJha** [comment]
> problem solved by I click disable and enable network in UBUNTU again.

Thank you!!

**Comment by singhrajgithub** [comment]
Although this is a closed issue but i would like to know the root cause if you guys are aware of it.  I am also facing same issue . Below are the error logs for the same 
```
 composer network start --networkName tutorial-network --networkVersion 0.0.1 --networkAdmin admin --networkAdminEnrollSecret adminpw --card PeerAdmin@hlfv1 --file networkadmin.card
Starting business network tutorial-network at version 0.0.1

Processing these Network Admins: 
	userName: admin

✖ Starting business network definition. This may take a minute...
Error: Error trying to start business network. Error: No valid responses from any peers.
Response from attempted peer comms was an error: Error: failed to execute transaction 237dd17d8f2b14085f1bc43a30a49e665a3fec56a08d3114392091ac440e00f5: error starting container: error starting container: Failed to generate platform-specific docker build: Error returned from build: 1 "npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! request to https://registry.npmjs.org/composer-common failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org:443

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-04T15_07_39_405Z-debug.log

```

**Comment by LeeJCherry** [comment]
I have the same issue
`2019-06-10 14:40:54.417 UTC [main] InitCmd -> WARN 001 CORE_LOGGING_LEVEL is no longer supported, please use the FABRIC_LOGGING_SPEC environment variable
2019-06-10 14:40:54.422 UTC [main] SetOrdererEnv -> WARN 002 CORE_LOGGING_LEVEL is no longer supported, please use the FABRIC_LOGGING_SPEC environment variable
2019-06-10 14:40:54.428 UTC [chaincodeCmd] checkChaincodeCmdParams -> INFO 003 Using default escc
2019-06-10 14:40:54.428 UTC [chaincodeCmd] checkChaincodeCmdParams -> INFO 004 Using default vscc
Error: could not assemble transaction, err proposal response was not successful, error code 500, msg error starting container: error starting container: Failed to generate platform-specific docker build: Error returned from build: 1 "npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! request to https://registry.npmjs.org/@theledger%2ffabric-chaincode-utils failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org:443

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-10T14_44_12_426Z-debug.log`

I don't believe this has anything to do with a network connectivity issue as I can run the following and get a valid response 
`curl https://registry.npmjs.org/@theledger%2ffabric-chaincode-utils`
