### ISSUE TITLE
New deploy modal needs some design love

### ISSUE THREAD

**Issue by caroline-church** [hyperledger/composer#3780]
The new deploy status modal needs some design love
![image](https://user-images.githubusercontent.com/23044145/38458215-05f966ca-3a9c-11e8-9aa2-54a6b3832510.png)

i'm not sure i understand why on the start status it says you need a card with the channelAdmin role. At this point you already have to have it.

**Comment by caroline-church** [comment]
@winslet could you provide some design input please

**Comment by winslet** [comment]
Hey @caroline-church Im thinking we can simplify this hugely:

![kapture 2018-04-19 at 11 28 39](https://user-images.githubusercontent.com/13980028/38986618-e2fe9db6-43c4-11e8-83f9-bab2ba1c96d1.gif)

Do you think this would work?

**Comment by caroline-church** [comment]
@winslet yes i think that could work, and looks much better 👍

**Comment by jt-nti** [comment]
@winslet the only problem with that is that no one is likely to see the install network message (it tends to be _way_ quicker than the start network) so it's not as clear what's going on. Also, the check box is probably unnecessary in the new design since the dialog will just vanish when it's done.

**Comment by caroline-church** [comment]
@winslet  @jt-nti Without the checkmark then we basically have what we had before (with just updated messages, i assumed the idea was to do something different then before?). The install network was visible before and is now slower so i don't see why people wouldn't see it

**Comment by jt-nti** [comment]
@caroline-church @winslet the original design had an enlarged progress box for deploys and the idea behind what's there now was to provide more information about what was going on and why, since there's some magic going on with the ID cards. The update does now force you to pick cards, however under normal circumstances they will pre-selected with no choice so I doubt many people will spend time reading that dialog. They do get more time to read the progress dialog because it's so slow, although showing a conga comic would be more fun. Also, there's currently no dialog to select ID cards for the original deploy, although that could easily be added.

**Comment by winslet** [comment]
Okay im very confused, let me ask some silly questions:

- @jt-nti what extra information on the deploy could we show here? 
- @caroline-church I guess this feeds from the above, but why would we want to do anything different? I know it takes longer, but my understanding was that we really cant tell how long it takes to get this stuff to complete on the fabric side?
- @jt-nti what magic are we doing with the ID cards in the background? 

- On the note about the dialogue to select ID cards for the original deploy, could we do this with fields in the deploy screen instead of a dialogue? That might save us an extra click through.

**Comment by jt-nti** [comment]
As discussed...

> what extra information on the deploy could we show here?

Not much/nothing (I don't think we get any progress information back from fabric)

> what magic are we doing with the ID cards in the background?

We're 'randomly' picking ID cards to use for deployment (not actually random but user has no say)

> On the note about the dialogue to select ID cards for the original deploy, could we do this with fields in the deploy screen instead of a dialogue? That might save us an extra click through.

Hopefully we can sort out these sort of design issues, including the need for a dialog box in the upgrade flow, in the upcoming wider playground redesign. (Is there an issue for that?) The cards used for network install and start/upgrade possibly don't fit cleanly in the 'business network' card concept (they are not typically associated with business networks) and could perhaps be treated differently. Or, even better, we could further restrict the scenarios that the playground is expected to handle to purely the prescribed fabric dev environment and really simplify things.

**Comment by winslet** [comment]
Just to add to the above, the text we would like to show in the modal (below the title as per my mockup above) needs to switch between the below on completion:

> Installing business network using **peeradmin@hlfv1** (1/2)

> Starting business network using **peeradmin@hlfv1** (2/2)

Ta 😀

**Comment by caroline-church** [comment]
done so closing
