### ISSUE TITLE
Rest Server POST /system/identities/issue: not working.

### ISSUE THREAD

**Issue by leowyennhan** [hyperledger/composer#3792]
The rest server in order to issue an identity is not working, its stuck at the loading location.  The authorisation failure might be due to certain reason.
It was working on 0.18.2

## Expected Behavior

A card should appear.

## Actual Behavior

Treating unknown remoting type "issueidentityrequest" as "any"
Treating unknown remoting type "issueidentityrequest" as "any"
Unhandled error for request POST /api/system/identities/issue: Error: fabric-ca request register failed with errors [[{"code":20,"message":"Authorization failure"}]]
    at IncomingMessage.<anonymous> (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/fabric-ca-client/lib/FabricCAClientImpl.js:741:22)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

## Steps to Reproduce

1. Start the rest server with oauth2 google authentication.
2. Export a new restadmin card after issuing and after importing.
3. Import the restadmin.card file to the rest server, then get a 200 response.
4. Set it as default.
5.  Issue an identity 
6. Stuck on the screen with dots moving.
## Existing issues

- [ ] [Stack Overflow issues](http://stackoverflow.com/tags/hyperledger-composer)
- [ ] [GitHub Issues](https://github.com/hyperledger/composer/issues)
- [ ] [Rocket Chat history](https://chat.hyperledger.org/channel/composer)

## Your Environment

* Version used:
V0.19.0 Hyperledger composer.
AWS ubuntu  16.0

**Comment by tanhuiya** [comment]
delete your old card file and import new ,when start network

**Comment by rthatcher** [comment]
Covered by Issue #2647

**Comment by rthatcher** [comment]
I would think that you are trying to Issue a new Identity with a existing Identity that does not have the rights.  If you lookup the `composer identity issue` in the documentation you will see there is an option `-x` to create the new identity with the right to create others.  I the problem persists I would posrting a Question to Stack Overflow.

**Comment by mydevfingers** [comment]
I have been getting the same error while calling the "/system/identities/issue" API and when compared with "/system/identities/bind" API, the issue seems to have caused due to the the NS missing in the "participant" field. 
In the bind API, it clearly throws a "Missing namespace" 500 error message. However, the identities issue API just hangs. 

**Solution:** Just add the Namespace to the participant as shown in the attached screenshot
![issueidentities_api_ns-issue](https://user-images.githubusercontent.com/29328825/47196144-c4300480-d391-11e8-85d1-c63fb66b5864.PNG)

PS: There could be other reasons for the API hanging. The above is one of them resolved by providing the namespace of the participant.
