### ISSUE TITLE
0.19.x Playground tutorial updates required

### ISSUE THREAD

**Issue by lesleyannjordan** [hyperledger/composer#3821]
0.19.1
Local and Hosted tested

- [ ] Step Seven - diagram is out of date 
    - it has 'Update' button' rather than deploy changes
    - it is missing features of the screen - Update Network from to etc 

 - [ ] Step Seven - Local playground you get an extra screen to handle after 'Deploy Changes' button  See #3825

![image](https://user-images.githubusercontent.com/33546098/38671359-134429f0-3e43-11e8-9225-d1a256d701d2.png)

**Comment by davidkel** [comment]
associated with #3825

**Comment by davidkel** [comment]
Merging in text from another issue and closing

When wanting to work with a real fabric, playground behaves differently to when online or just using the web profile. Anyone trying to follow the guide will be struggling. The following is missing

Cards MUST have appropriate roles defined. If you don't you can't deploy
They need to be told to scroll down to the bottom of the page to fill in some credential information otherwise the Deploy button will not be enabled
Then they need to be told to scroll up again to find the deploy button again.
On Upgrade an explanation is required for the extra dialog that appears asking for cards.
It needs to be explained why it takes so long and the potential impact of all the docker chaincode containers that will build up because of the way hyperledger fabric works
It should also be explained that playground has a limitation where it will not work connecting to an existing multi-org fabric with a business network that has been deployed with an endorsement policy definition.
There is also reference to playground deploy here
https://hyperledger.github.io/composer/unstable/business-network/bnd-deploy
which either needs updating or should be removed as appropriate.

**Comment by rthatcher** [comment]
Tutorial file modified and will be included in @winslet PR.

Approach taken is that _most_ readers of the doc are not connecting to a real Fabric so we don't want to interrupt the flow.  Where the differences occur for a real Fabric a **NOTE** is made to refer to additional information at the bottom of the doc.
