### ISSUE TITLE
Emit System Events for REST Server Interaction

### ISSUE THREAD

**Issue by ydennisy** [hyperledger/composer#3840]
I would like to see events emitted into the `ws` channel for any interaction with the system which happens through the `composer-rest-server`.

## Context
This is not a bug, it would be an improvement. I feel many would have the need to track the creation of new participants in their network. Right now to do this you do not need to write any transaction logic as it is available as a POST request. Therefore receiving events for this becomes difficult.

## Expected Behavior
When participants are added, updated, queried - events should be emitted in the ws channel.

**Comment by sstone1** [comment]
System level events is something I've been pondering for a while, so a definite +1 from me.

**Comment by ypeckstadt** [comment]
I also agree this would be really helpful. Not just system events though. Basically an event for anytime a registry.add, update or remove is called for an asset or participant.  

For example currently making a real-time dashboard style application that keeps it state, with Redux, in sync is very difficult to do with composer rest server. Well maybe not difficult but the overhead is huge. 

Unless I am missing something you need to  create a transaction and event for every action you do on a registry, for every type, to make this work. For a normal CRUD scenario that means 3 transactions + an event for each model type to keep it readable unless you group it all into one transaction.   Which defeats the purpose of using the composer-rest-server  because you have all these pre-generated end-points you can't use because you can't notify the user of a data change somebody else made.  In my case it is the reason I  needed to move to custom server - composer SDK combo. However would prefer to use the composer rest server as going custom also creates a lot of useless copy/pasting overhead work :)

Security could be an issue though due to not being able to do ACL on events.
