### ISSUE TITLE
Cannot start blockchain buisness network behind corporate proxy

### ISSUE THREAD

**Issue by arich-net** [hyperledger/composer#3852]
Cannot start buisness network behind corporate proxy with SSL interception

## Context
I am trying to start my business network within Debian OS. following all the steps on https://hyperledger.github.io/composer/latest/tutorials/deploy-to-fabric-single-org.

The main difference is that within my corporate network there is a proxy which is intercepting SSL connections and issuing certificates signed by a custom "Proxy CA".

When installing the business network I have passed as well the custom npmrc file successfully.
composer network install -c PeerAdmin@business-network -a business-flow@0.0.1.bna -o npmrcFile=/path/to/npmrc.docker

The npmrc file contains the following instructions:
registry=http://registry.npmjs.org/
strict-ssl=false
unsafe-perm=true
rejectUnauthorized=false

But on start I have the following log file within the docker image "peer0.org1.example.com"
> x509@0.3.3 install /chaincode/output/node_modules/x509
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: unable to get local issuer certificate
gyp ERR! stack     at TLSSocket.<anonymous> (_tls_wrap.js:1103:38)
gyp ERR! stack     at emitNone (events.js:106:13)
gyp ERR! stack     at TLSSocket.emit (events.js:208:7)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:637:8)
gyp ERR! stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:467:38)
gyp ERR! System Linux 4.9.0-4-amd64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /chaincode/output/node_modules/x509
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN real-hackers-flow@0.0.1 No repository field.
npm WARN The package composer-common is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! x509@0.3.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the x509@0.3.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-04-16T09_45_24_283Z-debug.log
"

## Expected Behavior
Command successful. I expect that custom npm settings are passed as well to the peer docker image. It seems that inside chaincode there is some custom npm which is not reading this config file?

## Actual Behavior
See above logs

## Possible Fix
Passing to chaincode custom npm config settings whe rebuilding node-gyp?

## Steps to Reproduce
1. ./stopFabric.sh
2. ./startFabric.sh
3. composer card create -p connection.json -u PeerAdmin -c Admin@org1.example.com-cert.pem -k 114aab0e76bf0c78308f89efc4b8c9423e31568da0c340ca187a9b17aa9a4457_sk -r PeerAdmin -r ChannelAdmin
4. composer card import -f PeerAdmin@business-network.card
5. composer network install -c PeerAdmin@business-network -a business-flow@0.0.1.bna -o npmrcFile=/path/to/npmrc.docker
6. composer network start --networkName business-network --networkVersion 0.0.1 -A admin -S adminpw -c PeerAdmin@business-network

## Your Environment

* Version used: 
$ npm version
{ 'business-network': '0.0.1',
  npm: '5.7.1',
  ares: '1.10.1-DEV',
  cldr: '32.0',
  http_parser: '2.7.0',
  icu: '60.1',
  modules: '57',
  nghttp2: '1.25.0',
  node: '8.10.0',
  openssl: '1.0.2n',
  tz: '2017c',
  unicode: '10.0',
  uv: '1.19.1',
  v8: '6.2.414.50',
  zlib: '1.2.11' }

$ uname -a
Linux larichblockchain01 4.9.0-4-amd64 #1 SMP Debian 4.9.65-3+deb9u1 (2017-12-23) x86_64 GNU/Linux

$ docker ps
CONTAINER ID        IMAGE                                     COMMAND                  CREATED             STATUS              PORTS                                            NAMES
8b773cbd1602        hyperledger/fabric-peer:x86_64-1.1.0      "peer node start"        23 minutes ago      Up 23 minutes       0.0.0.0:7051->7051/tcp, 0.0.0.0:7053->7053/tcp   peer0.org1.example.com
f9806342a169        hyperledger/fabric-couchdb:x86_64-0.4.6   "tini -- /docker-ent…"   23 minutes ago      Up 23 minutes       4369/tcp, 9100/tcp, 0.0.0.0:5984->5984/tcp       couchdb
b9a790d606b2        hyperledger/fabric-orderer:x86_64-1.1.0   "orderer"                23 minutes ago      Up 23 minutes       0.0.0.0:7050->7050/tcp                           orderer.example.com
7d5393c803ee        hyperledger/fabric-ca:x86_64-1.1.0        "sh -c 'fabric-ca-se…"   23 minutes ago      Up 23 minutes       0.0.0.0:7054->7054/tcp                           ca.org1.example.com

**Comment by eramitg** [comment]
Dear Friend,

Use no proxy during running your fabric network or use local network as exception for proxy and then try it should work.



Regards,
Amit Kumar Gupta
LFID:eramitg

From: Arich.net
Sent: Monday, April 16, 2018 3:37 PM
To: hyperledger/composer
Cc: Subscribed
Subject: [hyperledger/composer] Cannot start blockchain buisness networkbehind corporate proxy (#3852)

Cannot start buisness network behind corporate proxy with SSL interception
Context
I am trying to start my business network within Debian OS. following all the steps on https://hyperledger.github.io/composer/latest/tutorials/deploy-to-fabric-single-org.
The main difference is that within my corporate network there is a proxy which is intercepting SSL connections and issuing certificates signed by a custom "Proxy CA".
When installing the business network I have passed as well the custom npmrc file successfully.
composer network install -c PeerAdmin@business-network -a business-flow@0.0.1.bna -o npmrcFile=/path/to/npmrc.docker
The npmrc file contains the following instructions:
registry=http://registry.npmjs.org/
strict-ssl=false
unsafe-perm=true
rejectUnauthorized=false
But on start I have the following log file within the docker image "peer0.org1.example.com"
x509@0.3.3 install /chaincode/output/node_modules/x509
node-gyp rebuild
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: unable to get local issuer certificate
gyp ERR! stack at TLSSocket. (_tls_wrap.js:1103:38)
gyp ERR! stack at emitNone (events.js:106:13)
gyp ERR! stack at TLSSocket.emit (events.js:208:7)
gyp ERR! stack at TLSSocket._finishInit (_tls_wrap.js:637:8)
gyp ERR! stack at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:467:38)
gyp ERR! System Linux 4.9.0-4-amd64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /chaincode/output/node_modules/x509
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN real-hackers-flow@0.0.1 No repository field.
npm WARN The package composer-common is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! x509@0.3.3 install: node-gyp rebuild
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the x509@0.3.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2018-04-16T09_45_24_283Z-debug.log
"
Expected Behavior
Command successful. I expect that custom npm settings are passed as well to the peer docker image. It seems that inside chaincode there is some custom npm which is not reading this config file?
Actual Behavior
See above logs
Possible Fix
Passing to chaincode custom npm config settings whe rebuilding node-gyp?
Steps to Reproduce
1. ./stopFabric.sh
2. ./startFabric.sh
3. composer card create -p connection.json -u PeerAdmin -c Admin@org1.example.com-cert.pem -k 114aab0e76bf0c78308f89efc4b8c9423e31568da0c340ca187a9b17aa9a4457_sk -r PeerAdmin -r ChannelAdmin
4. composer card import -f PeerAdmin@business-network.card
5. composer network install -c PeerAdmin@business-network -a business-flow@0.0.1.bna -o npmrcFile=/path/to/npmrc.docker
6. composer network start --networkName business-network --networkVersion 0.0.1 -A admin -S adminpw -c PeerAdmin@business-network
Your Environment
• Version used:
$ npm version
{ 'business-network': '0.0.1',
npm: '5.7.1',
ares: '1.10.1-DEV',
cldr: '32.0',
http_parser: '2.7.0',
icu: '60.1',
modules: '57',
nghttp2: '1.25.0',
node: '8.10.0',
openssl: '1.0.2n',
tz: '2017c',
unicode: '10.0',
uv: '1.19.1',
v8: '6.2.414.50',
zlib: '1.2.11' }
$ uname -a
Linux larichblockchain01 4.9.0-4-amd64 #1 SMP Debian 4.9.65-3+deb9u1 (2017-12-23) x86_64 GNU/Linux
$ docker ps
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
8b773cbd1602 hyperledger/fabric-peer:x86_64-1.1.0 "peer node start" 23 minutes ago Up 23 minutes 0.0.0.0:7051->7051/tcp, 0.0.0.0:7053->7053/tcp peer0.org1.example.com
f9806342a169 hyperledger/fabric-couchdb:x86_64-0.4.6 "tini -- /docker-ent…" 23 minutes ago Up 23 minutes 4369/tcp, 9100/tcp, 0.0.0.0:5984->5984/tcp couchdb
b9a790d606b2 hyperledger/fabric-orderer:x86_64-1.1.0 "orderer" 23 minutes ago Up 23 minutes 0.0.0.0:7050->7050/tcp orderer.example.com
7d5393c803ee hyperledger/fabric-ca:x86_64-1.1.0 "sh -c 'fabric-ca-se…" 23 minutes ago Up 23 minutes 0.0.0.0:7054->7054/tcp ca.org1.example.com

**Comment by arich-net** [comment]
Is there anyway to do it without changing proxy settings?

**Comment by sstone1** [comment]
@arich-net can you try running the install of the failing module on your development machine that is behind the corporate proxy, to see what happens? I suspect it will fail in the same way as the chaincode container build.

`npm install --registry=http://registry.npmjs.org/ --strict-ssl=false --unsafe-perm=true --rejectUnauthorized=false -g x509@0.3.3`

**Comment by lsheks** [comment]
I believe in the npmrc file you should also specify your
https-proxy = "http://yourproxy:port"
proxy = "http://yourproxy:port"

That is what I had to do behind a corporate proxy at least...
