### ISSUE TITLE
As an end user I can rename model and script files

### ISSUE THREAD

**Issue by sstone1** [hyperledger/composer#387]
We need to allow users to rename both model and script files in a business network definition, and redeploy the business network. The name of the model file should not be tied to the namespace at the top of the model, e.g. `models.cto` should be able to contain `namespace org.acme.stuff`.

**Comment by EdMoffatt** [comment]
Screen grabbing from Sam's latest hi-fis...

![image](https://cloud.githubusercontent.com/assets/7454304/24101570/c2e1225a-0d70-11e7-8834-e1db3c4bc8f5.png)

To achieve this (and give the full range of required functionality), we need to do/add a few things...

- [ ] Display names of files instead of name of Business Network when a Model, Script or ACL file is open
- [ ] Amend the design slightly to include an edit icon (so that the behaviour is similar to editing the Business Network name).
- [ ] In order for the Business Network name/version to always be editable in this new setup, we need there to always be an ABOUT navigation.  Right now, we don't display one if there is no README.md...  So what will we display there in that case?  Should we offer the user the ability to edit that file in markdown too?  So that if they're exporting a business network definition they created from scratch and want to add a readme for the people they're sending it to, they can do so from the UI?

Assigning this to Toby, as he also has #386 , which touches on the same area of the UI.

**Comment by EdMoffatt** [comment]
Had some discussion around this today with @Tobias-Hunter , @winslet and @14gracel - capturing here so we don't forget!

1. The ABOUT navigation item should always exist.  It will show the user the name/version of the business network, which behave as in the UI currently (i.e. there is an edit pencil to make them editable which also reveals the link to package.json).

2. Also displayed on the ABOUT page is the README.md file from the root of the project.  If there's no README.md file there, we'll create a blank one.  Stuff on the ABOUT page cannot be deleted i.e. there is always a readme and a package.json file, even if they're empty.

3. In line with the other files planning to have a "visual" and "code" view, the Readme will do too...  Visual is actually the one we have implemented now, where we render the file.  The code view will switch it into a markdown editor, so that the user can make changes to the readme in Playground.

4. The only way to "start from scratch" presently is to have something imported, then delete all the stuff from it.  This isn't great, particularly as the user may end up with stuff floating around in package.json that no longer makes sense...  We suggest we should re-do the Import/Replace Network modal to allow a "New Empty Model" option: this will need to appear above the GitHub samples (as it can be an option without GitHub auth).

5. What about adding new Readme or package.json files?  We reckon that should not be supported.  There's one and only one of each.

6. But...  But...  What about if you try to import one??  Ok, in that case, we should probably allow it, but have a warning on the confirmation modal that says it will replace your current readme or package.json file.

**Comment by EdMoffatt** [comment]
Next step on this - need @Tobias-Hunter to upload a link to the finished low-fis (the file on Box is not finished yet by the look of things, so need to get that completed and trimmed down to just the screens needed, please!)

**Comment by Tobias-Hunter** [comment]
Please see page at the start of each flow & comments above, all taken into account with this new flow. Apologises for the use of the old UX mock-up!

.XD Click-through prototype:
https://xd.adobe.com/view/ecf28622-33df-42c8-b553-c0f2fa414b0b/

.XD File on Box:
https://ibm.box.com/s/8s0ktbpj3ja62m31crkdzyfcv168drp0

Assigning @winslet for hi-fis! 🐨

**Comment by winslet** [comment]
Hifi's below, please refer to @Tobias-Hunter 's XD prototypes for the full flows. 

### 1. User can view both the readme.md in either a code "editor" view or a standard rendered view. 
![fabric composer playground define 2 copy 67](https://cloud.githubusercontent.com/assets/13980028/24756174/c68ba3e6-1ad4-11e7-92a6-98aaed553e83.png)
--
![fabric composer playground define 2 copy 57](https://cloud.githubusercontent.com/assets/13980028/24756183/cd4b053c-1ad4-11e7-9e8b-8d6163741cb5.png)

### 2. Selecting the "edit" icon next to the name will hide the code/visual view buttons and drop the opacity of the content allowing someone to edit the BN name and version number.

![fabric composer playground define 2 copy 58](https://cloud.githubusercontent.com/assets/13980028/24756236/f77c80e2-1ad4-11e7-8c3a-203cdb8cefed.png)

### 3. Selecting import now allows users to create an empty business network

![fabric composer playground define 2 copy 59](https://cloud.githubusercontent.com/assets/13980028/24756637/5ca8cef8-1ad5-11e7-9090-544bbb90ec1f.png)

--

![fabric composer playground define 2 copy 60](https://cloud.githubusercontent.com/assets/13980028/24756643/68a92c84-1ad5-11e7-893b-b858e0d26359.png)

--

_with an empty readme file_
![fabric composer playground define 2 copy 62](https://cloud.githubusercontent.com/assets/13980028/24756949/9287dc94-1ad5-11e7-8597-dedf0b634ad6.png)

### 4. Readme's can be updated/replaced by uploading a new version in the "add a file" dialogue.

![fabric composer playground define 2 copy 63](https://cloud.githubusercontent.com/assets/13980028/24756986/b296e624-1ad5-11e7-8a41-b492d4e51591.png)

--

![fabric composer playground define 2 copy 64](https://cloud.githubusercontent.com/assets/13980028/24757001/bbae30dc-1ad5-11e7-845e-a0ecd9922d4c.png)

--

![fabric composer playground define 2 copy 65](https://cloud.githubusercontent.com/assets/13980028/24757009/c46dbdb4-1ad5-11e7-938b-1ecd795dcfb7.png)


**Marketch:** 
[Edit_Rename_FC_SW_1.zip](https://github.com/fabric-composer/fabric-composer/files/902681/Edit_Rename_FC_SW_1.zip)

**Updated Assets:** 
[MD_File_Icon.zip](https://github.com/fabric-composer/fabric-composer/files/902683/MD_File_Icon.zip)

**Comment by winslet** [comment]
@sstone1 could you direct this back out to the team? Hopefully everything should be there, happy to help if we need anything more. 👍

**Comment by samjsmith** [comment]
@winslet Hey Sam, looking at this one, in Section 3 above `3. Selecting import now allows users to create an empty business network`, I don't think that the 'Empty Business Network' option has been implemented yet has it?  
It isn't there in the latest code that I've just run so I think that perhaps we need a separate issue for that 'allow an empty business network to be created via the 'Create/Replace' link as a pre-req to this issue right?
I may have missed something here so feel free to set me straight :)

**Comment by winslet** [comment]
@samjsmith yup you're right, I agree we need to create an issue for making a blank business network (apologies - for some reason I had it in my head that there was already one) 🙈

**Comment by samjsmith** [comment]
Cool thanks @winslet  :) 
I'll create one now and link it in here

**Comment by EdMoffatt** [comment]
Doing a little "design tag" triage - looks like this one needs assigning out to someone as the next step?  (The sidebar about blank business network has resolved but there is still the renaming piece still needs someone assigned) - who should look at this, @sstone1 ?

**Comment by sstone1** [comment]
@caroline-church @bestbeforetoday please could you find somebody to pick this up?

**Comment by nklincoln** [comment]
Current status is:
 - Import of new BND will issue a warning that the existing BND will be overwritten
 - Possible to edit script and file names, inclusive of validation applied to filename (alpha-numeric)

Required for story completion:
 - Enable import of README.md file

**Comment by sstone1** [comment]
@nklincoln please move that final piece "Enable import of README.md file" into a new user story, it does not seem relevant to the original user story 😉

**Comment by nklincoln** [comment]
@sstone1 - sorry, I had already completed that aspect!
