### ISSUE TITLE
As a Playground user, I can find the objects I'm looking for even when Registries become very full

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#396]
## Context
A user may submit transactions within the Fabric Composer Playground UI. Each successful transaction is logged and retained. Each Transaction is displayed in the Transaction Registry, within a single list based on transaction timestamp (most recent at top of list). It is anticipated that there will be a significant number of transactions that accrue over time, meaning that this list will become very large.

## Expected Behavior
When the list of transactions reaches a limit, the list of transactions should become paginated, so that there is no overflow of the registry display area and the need to scroll through a very large list.

## Actual Behavior
The list grows, being appended to with each successful transaction. As the list grown, the side scroll bar is required to inspect the list, and the Submit Transaction button (on left menu) remains within the center of this "total height", meaning that it is necessary to scroll down to reach the submit action.

## Possible Fix
1) Modify the flex container for the Submit Transaction button
2) Implement pagination for the registry items. Whilst the transaction list was highlighted (because it represents the extreme case) this is equally valid for all registry items within a business network.

## Steps to Reproduce
Use the UI and submit a large number of transactions, watch the list grow!

**Comment by EdMoffatt** [comment]
Hey @nklincoln - just as I'm working on this one...  I'm not able to recreate the part of the issue you describe here:

> As the list grown, the side scroll bar is required to inspect the list, and the Submit Transaction button (on left menu) remains within the center of this "total height", meaning that it is necessary to scroll down to reach the submit action.

When I submit a lot of transactions, the RHS of the screen where those transactions are listed remains independent of the LHS.  The button stays where it is.
I'm *guessing* this has been fixed since the issue was raised, but could you just check on fabric-composer.org with the current build and let me know whether you're still seeing that part of the problem?

(No argument on the need to have a way of dealing with there being a ton of stuff in there tho - I'll rustle up some ideas for that ;) )

**Comment by EdMoffatt** [comment]
Set of low-fi designs here: https://xd.adobe.com/view/64673adc-1eba-4ec1-9afc-68e4280d3ce6/

Proposal is that we need to enrich our APIs so that we're not just getting back *everything* from the Fabric (which will definitely not scale well as we get to the point of many entries in a registry).  Instead, we should be able to request...

1. Give me the first N records...
2. ...ordered by X...
3. ...And filtered according to Y

The mockups offer some initial suggestions for what N, X and Y might be, i.e...

1. N can be set to 50, 100 or 200 via a dropdown, and defaults to 50 (50 should be fine for most demos!)
2. X is also a dropdown, with some initial suggestions being to sort by most recently created, oldest, ID A-Z, and ID Z-A.  We may well want to change or extend that list of options!
3. Initial suggestion for Y is to offer a "contains" filter on each of the keys in the object's data, and also date ranges for created and modified.  It might be cool to play with an "advanced" version too, where you can do more than just "contains".

**Comment by EdMoffatt** [comment]
Leaving a note to say...  I think this one is actually effectively saying "implement support for Query in Playground, and use this to make the registries work with large numbers of assets".

i.e. I believe this will mean implementing the front-end component of #543 therefore it probably makes sense to do those two pieces of work concurrently

**Comment by sstone1** [comment]
Blocked by lack of complex query support.

**Comment by EdMoffatt** [comment]
Closing this as it feels entirely covered by #1011 and #1015 , which effectively separately say "we need search/filtering/sort functionality on registries" and "we need pagination on registries" - and I feel like 2 separate issues for those things is more useful than this 1 issue.
Also, all the designs that Sam and Toby have attached to those ones are better than the stuff I had on here, so we should work on those ;)
