### ISSUE TITLE
cli-network txn failure check

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#4047]
Exceptionally nickpicky issue ... 

#3992 modified the json parsing/rejection and that picked up on invalid json going into a txn function within the integration tests ... which resulted in a test failure.

The test was correctly modified to make it legitimately pass, but it would have been super nice to have retained the failing item within a 'run an expected fail command' style test to ensure that things fail when they should too.

So this issue is to add in an 'expected fail' test for a badly specified txn input json.

**Comment by bestbeforetoday** [comment]
@nklincoln Invalid JSON input is already covered by unit tests. What value are we adding by also driving this from integration tests?

**Comment by nklincoln** [comment]
because it is a new feature that is trivial to test inside the integration framework. Additionally at no point in any of the delivered unit tests are there any checks/enforcement that the error message returned is of any use to an end user.

**Comment by bestbeforetoday** [comment]
For the record, "because we can" is absolutely not a good reason to implement a test; particularly an integration test which is inherently heavier weight and provides feedback much more slowly than a unit test. Adding unnecessary (or duplicate) tests slows down the test process and decreases the value of the whole test suite.

I can buy that it is useful to integration test a failing transaction. This is a general scenario that seems to be missing from our test coverage, not specifically related to the changes I made that triggered this discussion, but they will do as a specific test case.
