### ISSUE TITLE
Playground - Network Deployment Inconsistency

### ISSUE THREAD

**Issue by rthatcher** [hyperledger/composer#4150]
When I am modifying the Business Network in Playground (enhanced transaction logic for instance), on clicking the the `Deploy Changes` button I can choose the cards that I use for Installation and Upgrade.

However when I initially `Deploy a new Business Network` from the "My Business Networks" screen, I do not have that choice. 

( This issue brought to light when investigating #4143 )

**Comment by yulong12** [comment]
what do you mean is that I can't use composer-playground to create Admin card and use this Admin card to deploy a new business network ,am I right?

**Comment by caroline-church** [comment]
@yulong12 The issue was raised because when you try and deploy a business network within playground if you have more than one card that has Peer Admin and Channel Admin roles you cannot select which card that you want to use for deployment. This would generally occur if you had multiple organizations. So you can deploy a business network within playground but can't choose which card to use. However when you upgrade a network you are given the option to choose which card you wish to use to perform the upgrade. This is the inconsistency mentioned in the title. 

The error you are receiving suggests that the certificates you have provided are incorrect. If you want more help with this problem please create an issue on stackoverflow or ask on rocket chat
