### ISSUE TITLE
Playground (or Composer) hangs when invoking a transaction on an asset that a participant doesn't have explicit have READ access for.

### ISSUE THREAD

**Issue by annumberhocker** [hyperledger/composer#4153]
Composer hangs (while testing within Playground) when attempting to execute a transaction that changes an asset without proper READ access control.  This happens both on the web based Composer Playground and locally installed.
## Context

We are trying to find a way to provide access control for only certain fields within an asset by defining transactions that allow updating on these fields.  We defined access control rules to allow participants to have READ and UPDATE access against the transaction and the asset within the transaction.  We don't want the participant to have full READ access to the entire asset so we removed that rule and when we try to test our model on Playground, it goes into a loop and eventually hangs.  We can provide our .cto, .acl and .js files for this very simple test scenario.
## Expected Behavior

I would expect an error message indicating that the Participant attempting to create the transaction doesn't have access to the asset.
## Actual Behavior

Composer (or Playground) hangs.
## Steps to Reproduce

1. Import the test files or .bna into the Playground into a sample network, redeploy 
2. Create a Buyer and a Seller participant
3. Create separate id's for each of these participants
4. Create an Order Asset as the Seller
5. Attempt to do an UpdateOrder_BuyerNotes transaction as the Buyer. Should be able to do it.
6. Comment out first rule in .acl file and retest step 5.  Composer will hang.

## Existing issues

- [ ] [Stack Overflow issues](http://stackoverflow.com/tags/hyperledger-composer)
N/A
- [ ] [GitHub Issues](https://github.com/hyperledger/composer/issues)
N/A
- [ ] [Rocket Chat history](https://chat.hyperledger.org/channel/composer)
N/A

## Context

We are trying to find a way to provide access control for only certain fields within an asset by defining transactions that allow updating on these fields.  We are unable to test our theory and attempt other methods.

## Your Environment

* Version used:
https://composer-playground.mybluemix.net/
* Environment name and version (e.g. Chrome 39, node.js 5.4):
Whatever is bound with the Bluemix Composer version
* Operating System and version (desktop or mobile):
* Link to your project:
https://github.com/annumberhocker/projectcode_for_HL_issues/upload/master/HLC_acl_READ_hang

**Comment by mbwhite** [comment]
@annumberhocker thanks for your detailed report; one question that came to mind is what is the flow for retrieval of the order. Is this done by the buyer/seller or is it done by another participant - not shown here?

**Comment by mbwhite** [comment]
The good news is that it is possible to rewrite the ACL as follows (I did reproduce based on the testcase)
```
rule Buyer_UPDATE_notes_tx_UpdateOrder_BuyerNotes {
    description: "..."
    participant(p): "org.example.basic.Buyer"
    operation: UPDATE, READ
    resource(v): "org.example.basic.Order"
    transaction(tx): "org.example.basic.UpdateOrder_BuyerNotes"
    condition: (tx.order.getIdentifier() === v.getIdentifier() && v.buyer.getIdentifier() === p.getIdentifier())
    action: ALLOW
}
```

*Why does the original fail?*
The problem was that the original condition was `tx.order.buyer.getIdentifier() == p.getIdentifier()` and the resource that was being checked was the `org.example.basic.Order`  - note that in the expression `tx.order.buyer` that needs to resolve the `tx.order` object to find the buyers identity. 

tx.order is a `org.example.basic.Order` therefore the same rule needs executing to determine to allow/deny.  This then gets into the loop.

*Why does the new one work?*
Aside first - swapped to using === as these are JS conditions so === is preferred. 
To get a resource identifier you don't need to resolve a relationship... `tx.order.getIdentifier()` is safe.
This is checked against the order currently in the tx.  If it's not the same then we can deny access. 
Only if it's the same then get the order that is in the transaction we can then access the buyer identifier.

This is access via the variable v - so there is no lookup of an order required. 

*Summary* is don't, have in a condition the need to resolve a relationship that is directly or indirectly the resource of this rule.

**Comment by annumberhocker** [comment]
Thanks.  This ACL rule change enlightened us and works perfectly for what we need to demonstrate.  I will leave this issue open for now until it is decided how to better handle the hang scenario (catch and throw an error?) as I fear customers will end up doing the same type of rule condition.

**Comment by mbwhite** [comment]
Added a more distinctive error message
```
Error: attempt to get property buyer on an InvalidRelationship is not allowed. InvalidRelationship created due to Object with ID '5345' in collection with ID 'Asset:org.example.basic.Order' does not exist; [cause=attempt to get property buyer on an InvalidRelationship is not allowed. InvalidRelationship created due to Object with ID '5345' in collection with ID 'Asset:org.example.basic.Order' does not exist; [cause=Cyclic ACL Rule detected, rule condition is invoking the same rule]]
```
