### ISSUE TITLE
Network reset not working after network start returned an unusable BNC

### ISSUE THREAD

**Issue by b509** [hyperledger/composer#4257]
If `composer network start` returns a card that cannot be imported, the business network is started anyway, but cannot be reset (without resetting the whole chain).

## Context
I started `composer network start` with the -C (key) and not the -S (password) option, but gave the wrong key (public, not private key). The command succeeds and returns a BNC. However, this card cannot be imported (error message: "privateKey not specified or not a string"). 
The problem is: Resetting the network seems to work only with this exact BNC. Otherwise I get the error "business network identifier not specified". At this point I see no way around the issue than to restart the complete network.

## Expected Behavior
Either the initial network start checks the key and stops if it is not the private key.
Or I have the option to reset the network with the PeerAdmin card that I created earlier.

## Actual Behavior
I reached a dead point.

## Steps to Reproduce
1. Create PeerAdmin card
2. Run `network install` with PeerAdmin card and some archive
3. Run `network start` with PeerAdmin card and public key for option C

## Your Environment
* Version used: 0.19.10
* Environment name and version: node v8.11.1
* Operating System and version (desktop or mobile): Ubuntu 16.04.4 LTS

**Comment by medoamanquer** [comment]
teardown fabric and remove docker containers and start the fabric again

check if this resolved your problem

**Comment by b509** [comment]
@medoamanquer: Yeah, as I wrote: That's what solves it. But its the sole option at this point and that should not be the case. It's the whole point of this issue. That's why I suggested two workarounds as "expected behaviour".

**Comment by davidkel** [comment]
-C has to be the public certificate and you have to get it right as this is the identity you are binding to an initial participant so that you have some sort of access to the business network. Get it wrong and you won't have access. You can specify the -K option with -C and it will create a usable business network card file. However if you don't then the card file isn't of much use but nothing stops you from creating your own card file from the crypto material you have and importing that card.
Closing As this isn't a bug
