### ISSUE TITLE
Unable to request external data from secured API

### ISSUE THREAD

**Issue by Juanan92** [hyperledger/composer#4277]
## Context

I have some troubles trying to get data from an external secured API from a Composer transaction. The API is secured through a Keycloak server. The access_token step is done, but I cannot accomplish the request using this key and I get this error:

 
> {"originalStack":"g@http://localhost:8080/polyfills.eb7a9fefe827db0c2516.bundle.js:1:144464\nd.prototype._onFinish/p.onerror@[...]/main.1d28ad001464306011bd.bundle.js:1:3799461\nn@ [...]polyfills.eb7a9fefe827db0c2516.bundle.js:1:132877\n867/http://localhost:8080/polyfills.eb7a9fefe827db0c2516.bundle.js:1:152536\n867/http://localhost:8080[...]80/main.1d28ad001464306011bd.bundle.js line 1 > Function line 3 > eval:691:2\n"}

Using this chunk of code: 

`var options = { 
    method: 'GET', 
    url: uri, 
    headers: { 
        Authorization: 'Bearer ' + access_token, 
       //Accept: 'application/json'//, 
       'Content-Type' : 'application/json' 
    } 
};

alert(JSON.stringify(options))

request(options, function (error, response, body) { 
    if (error){ 
        qry=error alert(error) throw new Error(error); 
    }

    alert(body); qry = body 
});`

It works for me using the same chunk of code in the javascript console, using curl and postman, but not from a Composer Playground transaction...
Any ideas?

## Expected Behavior

Return a valid response to the GET request as occurs using the Node console or CURL.

## Actual Behavior

Returns this error:
> {"originalStack":"g@http://localhost:8080/polyfills.eb7a9fefe827db0c2516.bundle.js:1:144464\nd.prototype._onFinish/p.onerror@[...]/main.1d28ad001464306011bd.bundle.js:1:3799461\nn@ [...]polyfills.eb7a9fefe827db0c2516.bundle.js:1:132877\n867/http://localhost:8080/polyfills.eb7a9fefe827db0c2516.bundle.js:1:152536\n867/http://localhost:8080[...]80/main.1d28ad001464306011bd.bundle.js line 1 > Function line 3 > eval:691:2\n"}

## Possible Fix

Must be a Composer bug, as it works outside of Composer

**Comment by davidkel** [comment]
Playground is a simple introduction to how to write business networks and test them and provides a web browser simulation of the composer runtime. That means it emulates a fabric and uses the javascript engine inside the browser (so all requests are made from your browser. When you deploy your business network to a fabric network this will not be the case it will be executed from your chaincode container). You can see this by the fact that functions such as alert() are available which will not work when you run the business network inside a real fabric. You wouldn't use playground as your end user front end to a fabric network.

In your case the call to request is not correct. The request api available in composer is not a callback api, but an asynchronous implementation. If you managed to get the callback version running somehow in playground via the web browser profile, it certainly will not work when you try to deploy your business network to a real fabric.

See https://hyperledger.github.io/composer/latest/integrating/call-out which explains more about how request works and is exposed (note that it makes the request-promise version of request available rather than the callback based request module).
