### ISSUE TITLE
Filters are not working as documentation

### ISSUE THREAD

**Issue by mhamzawey** [hyperledger/composer#4292]
`The key = operator is not supported`
## Context

Trying to use filters against simple model and I get error message that operator `=` is not supported
## Expected Behavior

According to the tutorials in this [link](https://hyperledger.github.io/composer/latest/business-network/query)
## Actual Behavior

I get this error: 

```
{
  "error": {
    "statusCode": 500,
    "name": "Error",
    "message": "The key = operator is not supported by the Composer filter where",
    "stack": "Error: The key = operator is not supported by the Composer filter where\n    at Function.parseObjectValue (/home/vagrant/.yarn-global/node_modules/loopback-connector-composer/lib/filterparser.js:115:19)\n    at Function.parseWhereCondition (/home/vagrant/.yarn-global/node_modules/loopback-connector-composer/lib/filterparser.js:206:35)\n    at Function.parseFilter (/home/vagrant/.yarn-global/node_modules/loopback-connector-composer/lib/filterparser.js:53:27)\n    at ensureConnected.then.then (/home/vagrant/.yarn-global/node_modules/loopback-connector-composer/lib/businessnetworkconnector.js:321:58)\n    at <anonymous>"
  }
}
```

## Steps to Reproduce

1. Start your composer rest server
2. Filter against any of your assets/participants using `{"where": {"field1": {"op":"value1"}}}` where op can be `=`,'or`, and `and`

## Your Environment

* Version used:  **hlfv11**
* Environment name and version: **Chrome 67.0.3396.99 , node.js 8.11.3**
* Operating System and version (desktop or mobile): Desktop Ubuntu 16.04

**Comment by kidsil** [comment]
It looks like rather than using
`{"where": {"field1": {"op":"value1"}}}`
One should use the following for equivalence:
`{"where": {"field1": "value1"}}`

This is noted on Loopback's docs:
https://loopback.io/doc/en/lb2/Where-filter.html#equivalence
And also in the loopback-connector-composer package: https://github.com/hyperledger/composer/blob/60261521cea0e714cc713967dee1aadd7a557dfe/packages/loopback-connector-composer/lib/filterparser.js#L36


As Loopback's docs are referenced on the tutorials link you gave, seems like no changes are required.
