### ISSUE TITLE
Hyperledger REST Server Google Oauth

### ISSUE THREAD

**Issue by gokceozer** [hyperledger/composer#4325]
I deployed the network to query from the REST client and launched the REST instance. I wanted to use Google Oauth for the authentication needs but there happens to be an authentication error. 

## Context
{

The network is on the localhost:3000 and looks fine; however, when I import a business card and "try it out" the /system/historian I get this response body: 

  "error": {
    "statusCode": 500,
    "name": "Error",
    "message": "Error trying login and get user Context. Error: Error trying to enroll user or load channel configuration. Error: Enrollment failed with errors [[{\"code\":20,\"message\":\"Authorization failure\"}]]",
    "stack": "Error: Error trying login and get user Context. Error: Error trying to enroll user or load channel configuration. Error: Enrollment failed with errors [[{\"code\":20,\"message\":\"Authorization failure\"}]]\n    at client.getUserContext.then.then.catch (/home/composer/.npm-global/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:395:34)\n    at <anonymous>\n    at process._tickDomainCallback (internal/process/next_tick.js:228:7)"
  }
}
## Expected Behavior
I should be seeing a set of transactions

## Actual Behavior
I get the error code above

## Possible Fix
I checked the wallet, thinking I might have a problem with the card but there seems to be no problem. The code is 200 which is expected, and here is the response body:

[
  {
    "name": "liner1",
    "default": false
  },
  {
    "name": "liner1@iot-perishable-network-advanced",
    "default": true
  }
]

## Steps to Reproduce

1.
2.
3.
4.

## Existing issues

- [ ] [Stack Overflow issues](http://stackoverflow.com/tags/hyperledger-composer)
- [ ] [GitHub Issues](https://github.com/hyperledger/composer/issues)
- [ ] [Rocket Chat history](https://chat.hyperledger.org/channel/composer)

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by mahoney1** [comment]
have you seen the Google OAUTH2 tutorial https://hyperledger.github.io/composer/latest/tutorials/google_oauth2_rest    ?

Without enough info, I would imagine you needed to imported, pinged, then exported the card you created elsewhere (the 'ping' is so that it goes to the Fabric CA, to download the cert/key for the identity in question and populates his/her card in the wallet, which can then be exported and used in the REST API (which uses its own wallet). You can still do that, then import that card into the REST API, set it to default then try the historian query again. The other 'question' I have is whether the connection profile you built for that card (if that's what you did) is defined correctly - is this a custom Fabric or using the Fabric local dev Fabric setup? I would post any further issues to https://stackoverflow.com/questions/tagged/hyperledger-composer using the https://github.com/hyperledger/composer-knowledge-wiki/blob/latest/knowledge.md#issue
