### ISSUE TITLE
ACL condition fails when script uses getSerializer()

### ISSUE THREAD

**Issue by bttong** [hyperledger/composer#4330]
JavaScript condition expression does not work as expected if the script in the BNA uses getSerializer() function.

## Context

If the getSerializer() statement is removed from the script file in the BNA, the condition in the ACL rule works as expected

## Expected Behavior

We are using getSerializer() to create new instance of asset as part of an update operation.  Getting serializer object should not interfere with conditional ACL rules.

## Actual Behavior

All JavaScript expressions with comparison operations in the condition clause fails except `condition: (true)`, even `condition: ( true == true )` fails.

## Steps to Reproduce

I'm able to reproduce the problem in both our BNA and the basic-sample-network provided by the composer playground.  In addition, I'm seeing the same issue on both Composer 16.2 and 19.13 (via online composer playground).  My group is currently using Composer 16.2 (and planning to move to 19.5 soon).  
1. Rename the attach basic-sample-network.bna.txt to basic-sample-network.bna and deploy to 16.2 or 19.13 composer playground
2. Go to Test, create a participant and issue an ID
3. As network admin, create one sample asset with status set to "WORKCOMP"
4. As network admin, create one sample asset with status set to "RESOLVED"
5. Switch to the new created participant in step 2
6. Click on Sample Asset and notice that no record is showing
7.  Go to Define, remove `var serializer = getSerializer();` from the script and redeploy the BNA
8. Click on Sample Asset again and notice that you can see one of the records, record with status "WORKCOMP"
[basic-sample-network.bna.txt](https://github.com/hyperledger/composer/files/2278543/basic-sample-network.bna.txt)

## Existing issues

- [ ] [Stack Overflow issues](http://stackoverflow.com/tags/hyperledger-composer)
- [ ] [GitHub Issues](https://github.com/hyperledger/composer/issues)
- [ ] [Rocket Chat history](https://chat.hyperledger.org/channel/composer)
No existing issue found

## Context

This issue is blocking the ability for us to create conditional ACL rule.  Please advice if there's a workaround for composer 16.2.

## Your Environment

* Version used: 16.2
* Environment name and version (e.g. Chrome 39, node.js 5.4): node.js 8.11
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by mahoney1** [comment]
hi, 

without going into too much detail - the reason is because you have defined `var serializer = getSerializer()` outside any of your existing (in this case, basic sample) transaction functions.  It must be defined inside the scope of your function. The ACLs load in the scripts (as ACLs can also use custom functions too for rules evaluation etc). So if you had (say)

`/**
 * Sample transaction processor function.
 * @param {org.example.basic.SampleTransaction} tx The sample transaction instance.
 * @transaction
 */

async function sampleTransaction(tx) {  // eslint-disable-line no-unused-vars
    
    var serializer = getSerializer();
    // Save the old value of the asset.
    const oldValue = tx.asset.value;  
   // rest of your function follows incl. setting up for a new asset instance etc
  
}
` then all should be good
