### ISSUE TITLE
createPeerAdminCard.sh Bus error (core dumped) "${HL_COMPOSER_CLI}"

### ISSUE THREAD

**Issue by kevinjwchen** [hyperledger/composer#4369]
When I use composer-cli@0.20 to run createPeerAdmin.sh, it encounter Bus error (core dumped). 

## Your Environment
* Version used: composer-cli@0.20
* Environment name and version (node v8.9.1, docker 18.06.1-ce)
* Operating System and version (Ubuntu 16.04)

**Comment by jerry81333** [comment]
I have the same error as you. It shows me: createPeerAdminCard.sh: line 159: 11567 Bus error               (core dumped) "${HL_COMPOSER_CLI}" card import --file /tmp/PeerAdmin@hlfv1.card
### My Enironment
    Version used: composer-cli@0.20
    Environment name and version (node v8.11.4, docker 18.06.1-ce)
    Operating System and version (Ubuntu 16.04)

Is it possible that because I run Ubuntu under VMware?

**Comment by kevinjwchen** [comment]
Thanks a lot. I tried to stopFabric and teardownFabric and delete all the network card and retry. It works for me now.

**Comment by Pingze-github** [comment]
I met the error too.
I tried to stopFabric and teardownFabric but can not solve the problem.

At last, I found the error came because my npm module composer-cli was not completely installed, caused by network problem.

So try to uninstall composer-cli, and reinstall it. This time check the log carefully.
