### ISSUE TITLE
Programatically invoking one transaction from another

### ISSUE THREAD

**Issue by alexrosenfeld10** [hyperledger/composer#4375]
## Context

Hi, I'm wondering if it's possible to invoke one transaction programatically from inside another. 

I have tried doing this, but I get a log stating "cyclic acl rule detected". It doesn't however tell me which rule. I **have** tested transactionTwo independently and it works as expected.

For example, something like this:

```
/**
 * TransactionOne
 * @param {org.example.TransactionOne} The transaction one object
 * @transaction
 */
async function transactionOne(tx) {
  const factory = getFactory();

  tx.subTransactions.forEach(async (subTransactionData, idx) => {
    const subTx = factory.newResource(namespace, "TransactionTwo", tx.transactionId + ":" + idx);
    subTx.subTransactionData= subTransactiondata;

    await transactionTwo(subTx);
  });
}
```

Thanks in advance for any help you can provide.

**Comment by davidkel** [comment]
Suggest you ask this on stackoverflow as this isn't a bug with composer, however one thing I will suggest is don't use async/await inside a forEach loop. It doesn't work the way you would expect. Change it to a normal for loop to loop around subTransactions.

**Comment by davidkel** [comment]
A TP Function is just a standard javascript function so there is nothing to stop one function calling another.

**Comment by alexrosenfeld10** [comment]
@davidkel Thanks again for the followup. I've adjusted my ACL logic as well as used the loop you recommended and I can now programatically invoke one transaction from another.

However, I do have a followup question. When I invoke transactionTwo(), it does not appear in the all transactions history, nor do they get added to the transaction registry. At this point that feels like a bug in composer, seeing as there is a way to invoke transactions without having any record of them.

**Comment by davidkel** [comment]
@alexrosenfeld10 it's not a bug, you are just invoking another function under the same transaction context, it's not seen as a separate transaction. Working as expected.

**Comment by alexrosenfeld10** [comment]
@davidkel Thanks again. So, as a developer if I want to view all transactionTwo's history I'm expected to pull it out of the transactionOne history? I understand how it's under the same context, but as far as history goes it does feel a bit odd.

**Comment by davidkel** [comment]
@alexrosenfeld10 however you want to solve the problem, but if you invoke a function called transactionTwo it isn't running it as a separate transaction or see it as a separate thing, it is being run as just a function call and therefore part of the logic of the TP function you initiated.

**Comment by raphmc** [comment]
Hi, I'm joining your discussion since I'm standing in front of the same problem.
I'm trying to implement a **double auction** where producers of energy and consumers of energy can commit `bids` (buy certain amount of energy at certain price) and `asks` (offer certain amount of energy at certain price). The auction is supposed to clear the market every X minutes and I'm currently wondering how the `clear_market` transaction is to be evoked. Ideally, there is no central authority calling it when it's time, but some code executing itself automatically "on-chain" after the auction time has elapsed.
However, I currently don't see how to implement it.
My initial idea was that when a participant commits a `bid` oder `ask` transaction, it would fist check if there is a new auction period, and if yes, invoke the `clear_market` transaction. But if I understood @davidkel answer correctly, it wouldn't show up in the transaction registry. However, it would be good to have a trace of that transaction, since it returns the market clearing price and updates coin balances of the producers/consumers.
Do you see a solution?
Thanks in advance!

**Comment by xxLestadxx** [comment]
@raphmc I think you can still emit event, and if you are subscriber, you will be able to see the "new auction period" event.

**Comment by raphmc** [comment]
@xxLestadxx thanks, that's a good point! 
And will there be a trace "on-chain"? Since events are not stored in the ledger.
I mean, if my `clear_market` transaction changes the coin balances of the producers/consumers I need a trace of that. 
Thanks for your rapid answer ;)

**Comment by xxLestadxx** [comment]
I am not sure, but in the playground, you can see how many and which events have been emitted during a transaction. You have to try and see.

**Comment by raphmc** [comment]
I will :) thanks!
