### ISSUE TITLE
'/logout' not redirecting the user to configurable client url

### ISSUE THREAD

**Issue by sillysachin** [hyperledger/composer#4387]
Using the passport-github or passport-google strategy, I am able to logout the user from the rest server using /logout but the url gets stranded at rest server at <ipaddress>:3000 . If we are invoking <ipaddress>:3000/auth/logout from angular client which is running at <ipaddress>:4200 , we would need post logout the url to be redirected to <ipaddress>:4200

## Expected Behavior

post logout the url to be redirected to <ipaddress>:4200
Can the redirect be made configurable to client url <ipaddress>:4200/login

## Actual Behavior

post logout the url is stranded at <ipaddress>:3000

## Steps to Reproduce

1. https://github.com/hyperledger/composer/issues/2095
2. invoke auth/logout as part of href from angular client running at 4200

## Existing issues

- [ ] [Stack Overflow issues](https://stackoverflow.com/questions/51490682/hyperledger-composer-rest-server-logout)
- [ ] [GitHub Issues](https://github.com/hyperledger/composer/issues/2095)

## Context

- https://hyperledger.github.io/composer/latest/tutorials/google_oauth2_rest
- https://hyperledger.github.io/composer/latest/integrating/deploying-the-rest-server

**Comment by sillysachin** [comment]
@davidkel - is there a alternative approach or workaround ?

**Comment by David-Kim-TPE** [comment]
I've encountered the same issue. I'm also in search if there're better solutions. But found this not yet answered.

I think it's currently hard-coded to redirect to the root of the composer rest server after logging out.
Not just for Google, I suppose. For each and every strategy you choose to use. 

To change that,
Find your composer-rest-server package in your local machine.
For me, it's under "/home/{name}/.nvm/versions/node/v8.11.3/lib" in my Ubuntu 16.04.
Find "server/server.js" :162

change from
`res.redirect('/');`
to
`res.redirect('http://localhost:4200/');`
or you may try using process.env parameter instead of your choise.

![image](https://user-images.githubusercontent.com/10493277/45669633-39ba7200-bb53-11e8-8fc7-7af97ee8fa05.png)

It's straight forward. Works fine for me.
However, this is only a workaround.

**Comment by mortonsykes** [comment]
@davidkel  Hey David, cheers for your awesome hint, any idea how to start serving the change after making the edit? I have made the edit but I am not getting redirected yet. I assume i need to do the equivalent of a npm start?  cheers

**Comment by mahoney1** [comment]
@mortonsykes  yes, you would need to restart the application server process to take effect.

**Comment by David-Kim-TPE** [comment]
@mortonsykes Since you edited the composer-rest-server package that you installed earlier. You may like to re-run the "composer-rest-server" command again for it to take effect. It will launch an API server for you which handles the login & logout using LoopBack.js & Passport.js.

**Comment by davidkel** [comment]
Closing the issue, for reference please see
https://lists.hyperledger.org/g/composer/message/125
