### ISSUE TITLE
using 1.0.0 as version in package.json & networkVersion on composer network start causes admin permission error

### ISSUE THREAD

**Issue by rddill-IBM** [hyperledger/composer#4485]
if package.json uses version 1.0.0 then business network connect for all users fails with 
```
 Participant 'org.hyperledger.composer.system.NetworkAdmin#admin' does not have 'READ' access to resource 'org.hyperledger.composer.system.Network#zerotoblockchain-network@1.0.0'
```
This error occurs for admin and for all subsequently created Participants. Changing the version to another number (e.g. 1.1.5) resolves the error. 

Version 1.0.0 is a valid version number and should not randomly cause permission errors. 

## Expected Behavior

The network should start correctly and Participants should be able to connect, limited only by the contents of the permissions.acl file. 

1. change version to 1.0.0 in network/package.json file
2. start the network using networkVersion=1.0.0
3. import the generated admin card
4. ping the network using the admin id

## Context

Wasted 2 weeks trying to figure out what was wrong with previously working permissions file. 

## Your Environment

Ubuntu 16, Composer 0.20.2, fabric 1.2.2

**Comment by davidkel** [comment]
This will be due to old chaincode images on your system. If you don't clear out the old chaincode images then fabric can decide that an existing image is re-usable and not build a new image. This means that even though you have put a package onto a peer, that package is not going to get used because there is already an image with the same chaincode id (business network) and version and fabric can decide that it doesn't need to build an image from the package and use that image instead. You need to clear out old chaincode images to ensure that using packages with the same version and same business network are rebuilt.
