### ISSUE TITLE
As a user I can generate skeleton command line and web applications from a business network

### ISSUE THREAD

**Issue by dselman** [hyperledger/composer#45]
- [x] Refactor the yo generators to ask consistent questions.
- [ ] Put in place tests to ensure that the generated code actually works
- [x] Ensure the documentation is accurate

**Comment by Jakeeyturner** [comment]
We should add system tests so that we run through the entire process for generating an angular app. This includes:
- Generating angular applications given different business network archive files and live (deployed) business networks
- Test that the correct files have been generated
- If successful then run the applications generated unit tests

**Comment by EdMoffatt** [comment]
Shifting this over to Playback 4 for now to clear out the Playback 3 milestone

**Comment by dselman** [comment]
What is the status of this?

**Comment by sstone1** [comment]
@nklincoln please can you review the testing that is in place for the Angular generators and determine what we need to do to close this issue off (the only remaining work we can see is test coverage).

**Comment by nklincoln** [comment]
@sstone1 The existing test target a BND and subsequently assert that specific files were created via the generators. At present there is no validation of the output files themselves other than existence. We can extend this base set of testing in various ways:
 - A handy protractor test suite is automatically generated, which we could utilise against the generated files. This one seems like a no-brainer. We should be running this.
- Look into flexing the underlying API that is generated, which we could do by file inspection (since we are generating against known applications, the api output would be relatively stable until a yo-generator change come through. Alternatively we could look at extending the existing protractor suite that is generated to drive interaction rather than evaluating the rendered components.
