### ISSUE TITLE
[Master] fabric client InitializeChannel always uses first peer 

### ISSUE THREAD

**Issue by volodyad** [hyperledger/composer#4528]
Inside hlfconnection class we have we have next code on initialize error

```
while (!this.initialized) {
            try {
                await this.channel.initialize();
                this.initialized = true;
            } catch(error) {
                LOG.warn(method, `error trying to initialize channel. Error returned ${error}`);
                if (ledgerPeerIndex === ledgerPeers.length - 1) {
                    throw new Error(`Unable to initalize channel. Attempted to contact ${ledgerPeers.length} Peers. Last error was ${error}`);
                }
                ledgerPeerIndex++;
                const nextPeer = ledgerPeers[ledgerPeerIndex];
                LOG.info(method, `Moving ${nextPeer.getName()} to top of queue`);
                const peerIndex = this.channel.getPeers().indexOf(nextPeer);
                this.channel.getPeers().splice(peerIndex, 1);
                this.channel.getPeers().unshift(nextPeer);
            }
        }
```

seems in case first peer unavailable you wanted to make first next peer in queue
so you do
```
            this.channel.getPeers().splice(peerIndex, 1);
                this.channel.getPeers().unshift(nextPeer);
```

peers tried to mutate in place, but if we look inside fabric client Channel.js implementation
```
	getPeers() {
		logger.debug('getPeers - list size: %s.', this._channel_peers.size);
		const peers = [];
		this._channel_peers.forEach((channel_peer) => {
			peers.push(channel_peer);
		});
		return this._channel_peers;
	}
```

we will see that it returns copy array, so there is no way to mutate it inside channel file, it means that initialize channel always invoked on a first peer, so if you stop 1 peer - it will always fail

Seems it was broken since fabric client 1.2, in fabric client 1.1 it was 

```
	getPeers() {
		logger.debug('getPeers - list size: %s.', this._peers.length);
		return this._peers;
	}
```

**Comment by davidkel** [comment]
Thanks for the report of this, due to changes between the node-sdk 1.1 and 1.2.
This implementation was a workaround to a limitation of the node-sdk of the initialize api which did not provide any failover capability in 1.1 but unfortunately hasn't picked up the need to provide fallback for this call on newer versions of the sdk. The signature was actually changed in 1.2 for initialise as well. Also as described here the getPeers api as changed in the way it returns the internal data defined by the node-sdk and now this workaround which manipulated the undocumented internal node-sdk structures now doesn't work. It probably is possible to exploit the change to the initialize api signature to make it work without having to manipulate internal structures making it more appropriate.

**Comment by davidkel** [comment]
Doesn't apply to composer 0.19.x, only applies to 0.20.x

**Comment by volodyad** [comment]
When version 20.5 is going to be released?

**Comment by davidkel** [comment]
@volodyad Hopefully will publish a release at the end of this week.

**Comment by davidkel** [comment]
@volodyad Composer 0.20.5 has now been published, many thanks for the contribution.
