### ISSUE TITLE
unable to  npm install -g composer-cli@0.20 

### ISSUE THREAD

**Issue by harivenkateshsj** [hyperledger/composer#4627]
npm WARN checkPermissions Missing write access to /home/jothi/.nvm/versions/node/v8.15.1/lib/node_modules
npm ERR! path /home/jothi/.nvm/versions/node/v8.15.1/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/home/jothi/.nvm/versions/node/v8.15.1/lib/node_modules'
npm ERR!  { Error: EACCES: permission denied, access '/home/jothi/.nvm/versions/node/v8.15.1/lib/node_modules'
npm ERR!   stack: 'Error: EACCES: permission denied, access \'/home/jothi/.nvm/versions/node/v8.15.1/lib/node_modules\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/home/jothi/.nvm/versions/node/v8.15.1/lib/node_modules' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

**Comment by WagnerCruz** [comment]
Hi, did you tried SUDO npm install? From the messdages it looks like a permission issue at your environment, is it linux ubuntu 16.04?

Check again if the current logged user has necessary rights to perform the installation of the packages.

Hope it helps!

**Comment by realChainLife** [comment]
Using **Sudo** to install any composer packages is not recommended. Its advisable to uninstall your current NPM package and install NVM Instead. You can use this guide [https://github.com/creationix/nvm](guide). 

You can then reinstall the recommended node js & NPM versions, v8.9 - you'll able to use npm install without sudo to avoid the permission issues that come with it.

**Comment by liamdennehy** [comment]
Can we remove the `-g` flags and rely on npm commands to locate and find binaries? Global installs can easily conflict e.g. this package depends on binary `composer` being in my PATH, which already has a binary called [composer](https://github.com/composer/composer).

`-g` does not play well with others.

**Comment by liamdennehy** [comment]
> did you tried SUDO npm install?

@WagnerCruz Is there a good reason I need to grant root privileges to install these packages? I'm not modifying my entire system, I'm trying to get a dev environment set up...

**Comment by SantoshKumarSahu** [comment]
I also had faced the same issue.
Once you install the per-requisites, terminate the terminal, as it asks to logout.
It worked for me.

**Comment by alchemist107** [comment]
The problem is that you are on a root env session of your ubuntu os , to solve this problem all you have to do is to create a new user on Linux and use that user to setup your hyperledger development environment

Add new user :
$ sudo adduser fabric

Grant sudo writes to the new user
$ sudo usermod -aG sudo playground

Switch to fabric user session
$ su - fabric

**Comment by liamdennehy** [comment]
No no no.

The problem is that hyperledger fabric assumes it has the final say on how my development station is configured. Global package changes affect _everything_ that uses it, while npm is designed specifically to allow for local package management. If I have two applications that require two different library versions, I should be able to handle these. Global installs make that impossible.

The problem is not that the account lacks sufficient rights.
