### ISSUE TITLE
Business Network installation failed. Is there any way to debug it?

### ISSUE THREAD

**Issue by Mandy27** [hyperledger/composer#4630]
I am trying to install business network to one of the peer but i got the below error. Is there any logs that I can look at to know more what is going on?

> ✖ Installing business network. This may take a minute...
Error: Error trying install business network. Error: No valid responses from any peers.
Response from attempted peer comms was an error: Error: Failed to connect before the deadline
Command failed

**Comment by realChainLife** [comment]
I had a similar problem and someone suggested the business network installation fails with a timeout error because npm has to install additional packages. If you're using hlfv12 I solved my problem by adding this code `- CORE_CHAINCODE_STARTUPTIMEOUT=1200s` to the docker-composer.yml file found in /fabric-dev-servers/fabric-scripts/hlfv12/composer. Code will look like this. 

    peer0.org1.example.com:
    container_name: peer0.org1.example.com
    image: hyperledger/fabric-peer:1.2.1
    environment:
      - CORE_LOGGING_LEVEL=debug
      - CORE_CHAINCODE_STARTUPTIMEOUT=1200s
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.org1.example.com

If that doesn't work try increasing it to 2400s. All the best.

**Comment by DissYas** [comment]
I am having the same issue, even with trying to increase the timeout to 2400s, I still get the same error, Is there any other solution? 

Thank you

**Comment by abhik-99** [comment]
Could you detail the steps you took and commands if possible before you encountered this error? I had the same error and increasing the timeout was a good solution. It might be different considering what you did.
