### ISSUE TITLE
Composer Playground should use one abstract alert component

### ISSUE THREAD

**Issue by Jakeeyturner** [hyperledger/composer#539]
## Context
The Composer Playground should use one alert component. At the moment we have a success and error component.

These components could be simplified and merged into one component.

## Expected Behavior
Should have one component which can be used to create, show and hide alerts.

## Actual Behavior
We have separate alert components all with the same purpose

## Possible Fix
Create one component for handling alerts

## Your Environment

**Comment by caroline-church** [comment]
@EdMoffatt @winslet Can you add designs in here for alerts please?

**Comment by winslet** [comment]
I am a little confused, we would ideally like "success" notifications to be as per this:

![image](https://cloud.githubusercontent.com/assets/13980028/25008633/3c7b3ab2-205c-11e7-8aa5-f5d125a0ca58.png)

![image](https://cloud.githubusercontent.com/assets/13980028/25008722/7228f140-205c-11e7-8922-e987183c0265.png)

(as positive notifications, _which require no action_, should not need to be dismissed.)

Alert Modal Designs are slightly different as these often require the user to actively select something in order to continue:

![fabric composer playground define 2 copy 78](https://cloud.githubusercontent.com/assets/13980028/25008541/f949f814-205b-11e7-8233-987c23c88aff.png)

![fabric composer playground define 2 copy 60](https://cloud.githubusercontent.com/assets/13980028/25008549/01272dfe-205c-11e7-8398-83894791521f.png)

**Marketch:**
[Alert_Modals_SW_1.zip](https://github.com/fabric-composer/fabric-composer/files/919855/Alert_Modals_SW_1.zip)

So I would suggest we try and keep these still separate if possible? And work towards getting the notification style in if possible.

**Comment by EdMoffatt** [comment]
I'm closing this one because I think we've concluded we want different behaviour for failures and successes.

The current failure behaviour seems pretty good e.g. if you try to submit a Transaction and don't have permission, the modal stays open with an inline error.  I *wouldn't* agree with switching this for the same behaviour we should use for success, which is that the modal closes, and a smaller "pop-over" success notification (like the first ones in Sam's latest comment) confirms that it worked.

I'm going to raise a new issue to implement the success notifications, and list out the situations in which we need to display them.
