### ISSUE TITLE
As a user of a business network, I can view a record of all significant business events

### ISSUE THREAD

**Issue by dselman** [hyperledger/composer#55]
The Historian component for a business network will store significant business events. These include:

- the transactions that have been processed
- the details of the side-effects of processing transactions (updates to assets and participants)
- the details of events emitted during the processing of transactions
- identity issue/revoke operations
- business network definition changes

Strawman schema:
- ID
- Timestamp
- Current Participant ID
- History Entry Type (String)
- JSON Data that describes the history entry

The Historian is read-only from the client API. It is read-only and append-only from the runtime API.

The Historian is exposed over a REST API.

Note that this would replace the existing `TransactionRegistry`.

In addition is should be possible to register for notifications when a new entry is added to the Historian. This would allow this history entry to be stored in an external analytics data store.

## Questions

- Do we need to be able to optionally limit the Historian to a fixed number of entries (LIFO queue), or to a fixed time window (store all events for 30 days)?
- Do we need to be able to optionally configure what system events get stored in the historian? E.g only store transactions of type X

**Comment by trauts2** [comment]
How could access to historian data be restricted?  For instance, if competitors are peers on the chain, each should not be able to see the others' data, only their own.   Or maybe only other assets referencing their ID.

Is this sort of restriction envisioned to be handled in ACLs or maybe within custom logic in transactions for accessing data?

**Comment by sstone1** [comment]
@trauts2 I believe that we should be using ACLs to control access to all data stored in Composer, including the historian records.

**Comment by mbwhite** [comment]
After a F-F discussion last week about using Composer, I captured the following requirements. For reference, there was some initial confusion about what could and could not be captured in the Historian, so the [associated diagram](https://cloud.githubusercontent.com/assets/6673453/26126448/899bf22e-3a7d-11e7-8c0f-a4423066f869.png) was very useful in removing confusion. 

Transaction TX0 is triggered, being passed Assets A and B. During processing (and this processing has to be deterministic)
 
- Asset B is updated with information
- Asset A is read, deleted, and Assets A-1 and Assets A-2
- Asset C is identified during processing and updated
- Asset D is identified during processing but remains unchanged. 

*There is no requirement for the transaction and the other assets to have a model-defined relationship.*

**Comment by winslet** [comment]
Just had a chat with @caroline-church and @Tobias-Hunter 

We were talking things through and in the demo we show a transaction which says something has been **created** in the regulator screen. This does not seem to be shown above, we would like to expand the scope of this issue slightly to include that "create" transaction in the historian.

**Comment by kletkeman** [comment]
IoT Requirements would ideally support requirements such as:

- Save every incoming transaction in a transaction history ledger and every resulting registry operation and calculated asset state (including the state object and an emitted event objects if an update of some kind) in asset history ledgers

  - Link each asset state ledger entry backward to the original incoming transaction and payload
  - Link each transaction in the history ledger forward to all calculated asset state changes, operations and new state 

- Query asset states from history by timestamp range, filtering by qualified object property values or a more advanced rich query syntax

  - Offer the ability to return just the transaction list for a specific asset history range

**Comment by mbwhite** [comment]
Plan to start working on this tomorrow.

**Comment by sstone1** [comment]
@mbwhite can you liase with Ed/Sam on the design front for the rebranded transaction registry - the changes will likely be minor text changes and you'll be able to handle them, but if you end up needing someone with mad UI skillz speak to @caroline-church and see who can help out 👍

**Comment by mahoney1** [comment]
will Historian handle situations where (in a historian record) a Participant or Identity relationship no longer exists? Perfectly valid scenario, where the Participant or Identity has since been 'deleted' and thus the relationship is now defunct or no longer 'extant' when reporting/querying asset records etc
 etc.  Adding following a discussion this AM with @mbwhite ..

**Comment by mbwhite** [comment]
Version 0.11.0 of Composer has delivered on a number of the use-cases associated with this.

- Ability to track Network transactions that are submitted DONE
- Use of system transactions to track the creation, deletion and update of Assets, Participants DONE
- Events issues as part of the transactions, the identity used and participant are also tracked DONE
- Use of query means that more sophisticated analysis of the records is possible. DONE

Limitations/Next Phase
- CouchDB has limitations on the range of data and sort - this makes some use cases for Historian a bit harder.
- Currently we are storing a new record for each transaction id. This makes looking at transactions a lot simpler. However it's hard to review what has happened starting with an asset. 
- The Deltas are needed to do this - or least some tracking off them
- The question of how much data has to be in the world state has yet to be fully answered. Is it sufficient to have historian records as-today - and then use a graph-style database that is better optimised for this type of query. 
- Query via a REST API currently not available.

Codebase:
- They are some areas of code that could be refined in engineering terms
- More test must be added
- Samples and Examples especially how this relates to the ACLs
- Refinement of the HistorianRecord - note that requirements were already made to include the transaction type here. 

Must stress - that the codebase issues I'll commit to fixing shortly.

**Comment by sstone1** [comment]
Since I didn't get to review the historian code, I'm going to add the strictly-not-bug codebase issues here.

Firstly, here's a bug:
Historian does not record fully qualified type names #1852

You seem to have introduced a new registry type of `Historian` and defined a registry ID of `HistorianRegistry` instead of the default registry ID `org.hyperledger.composer.system.HistorianRecord`.
We don't need multiple registry types for each "system" registry, so this should be `Asset`.
We should use the default registry ID as it is simpler - it means that you don't need the `FROM` clause in queries.
This is the same as identity registry.

Following on from that, the code in `composer-client` could be simplified as there will only ever be one `HistorianRecord` registry. Again, see identity registry.

https://github.com/hyperledger/composer/blob/master/packages/composer-runtime/lib/engine.transactions.js#L188
This code would be a lot cleaner if `Context.loadCurrentParticipant` just stored the loaded identity during context initialisation, and then you could refer to it later. Also, there is no need for that `istanbul ignore next`!

Why is there not separate transactions for adding a single resource and adding multiple resources? It would neatly track which APIs are being used.

The transactions need to use relationships to the registries, not the registryType and registryId properties - I did see a TODO for this somewhere.

What is this `SystemRegistry` type you have introduced? What is its purpose?

https://github.com/hyperledger/composer/blob/master/packages/composer-systests/systest/historian.js
Commented out system tests! How did this get merged?!

**Comment by markcastle3** [comment]
@mbwhite can you check if any of these need to remain open or can be closed out ?

**Comment by mbwhite** [comment]
Build has completed https://travis-ci.org/hyperledger/composer/builds/275785484

@sstone1  If you could take a look please :-)

**Comment by mbwhite** [comment]
Verion bump to v0.13.0 underway prior to releases the latest updates.
