### ISSUE TITLE
Use npm shrinkwrap (or fix version numbers) to ensure releases remain strong and stable

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#651]
There are 2 problems that occur
- Due to our declaration in package.json we allow for minor changes to third party libraries outside of our releases. For example we depend on Package A and when we test prior to release, Package A is on version 1.0.1 and we are happy and release. Package A then updates to 1.0.9 and those changes cause problems, our released version will now fail where it could still continue to work if it had been fixed to version 1.0.1
- Dependencies on our own components is not consistent. If I install composer-cli@0.5.5 for example it still pulls in composer-common@0.5.8. We don't keep version consistency within our own levels. Also if someone has 0.5.5 installed, another npm install would update dependent versions to newer levels which may not be compatible. If you are at 0.5.5 and install 0.5.5 then it should install the matching versions.

**Comment by jt-nti** [comment]
Fixing version numbers wouldn't help with transitive dependencies, and it looks like shrinkwrap won't work with lerna - https://github.com/lerna/lerna/issues/377
It's possible that switching to yarn may help although, failing that, this could require a bigger change, e.g. different monorepo manager, or splitting in to multiple repos?

**Comment by jt-nti** [comment]
As far as I can tell yarn isn't helping either. Doing a yarn install at the root of the monorepo does create a yarn.lock, but that doesn't seem to fix versions as I was expecting. Could be due to this bug https://github.com/yarnpkg/yarn/issues/3313

Even if that works, I'm not sure how a yarn.lock file at the root of the monorepo would work with each of the packages, since they have their own package.json which yarn expects to be in the same place.

And finally, I'm not sure we'd want to lock down dependency versions in all the packages in the monorepo. From what I understand, packages that are consumed by other packages should not lock down versions, whereas we definitely do want to lock down dependencies for applications. The problem is, there is a mix of both in the same repo, e.g. composer-common vs composer-playground

**Comment by jt-nti** [comment]
Another hint that lerna is likely to hinder shrinkwrapping... https://github.com/lerna/lerna/issues/882#issuecomment-314884763
> It's not recommended to shrinkwrap lerna-managed modules.

**Comment by jt-nti** [comment]
It seems like using yarn with workspaces should help, although getting _lots_ of `lerna ERR! execute   stderr: 'lerna info version 2.2.0\nlerna info Bootstrapping 22 packages\nlerna ERR! execute Error: Command failed: yarn install --mutex network:61972` errors at the moment.

Another thought would be using a repository like bintray instead of the npm repository. (yarn also includes an offline option which looks interesting.)

**Comment by jt-nti** [comment]
Errors were due to lerna bootstrap in postinstall lerna/lerna#1017
The good news is that there is no need to bootstrap when using yarn workspaces anyway

**Comment by jt-nti** [comment]
Help! https://stackoverflow.com/questions/46492597/how-can-i-successfully-lock-down-node-module-dependencies-in-a-monorepo

**Comment by jt-nti** [comment]
No luck with the Stack Overflow appeal so far but the next thing I'm planning to try is replacing lerna with [rush](https://www.npmjs.com/package/@microsoft/rush)
