### ISSUE TITLE
Composer runtime alters relationships to store as the base resource type

### ISSUE THREAD

**Issue by pospi** [hyperledger/composer#696]
I'm unsure if this is intended functionality or simply something that needs further explanation. The `assetRegistry` appears to alter relationship data prior to saving, and stores relationships as the base type from the model schema instead of the type provided.

## Context

We have multiple different participant subclasses used in our network for different domains/clients/channels. Attempting to create relationships between assets & participants within transactions to track ownership is a problem, because all relationship types use the base participant class. Thus we are unable to retrieve the related participant records for an asset without storing extra metadata fields, something we expect should be handled by the relationship itself.

These are our model files:

(in a module dependency)
```
namespace org.network.core

abstract asset BaseAsset identified by id {
  o String id
  o DateTime createdOn
  --> BaseMember invoker
  --> BaseAsset parent optional
}

abstract participant BaseMember identified by id {
  o String id
  o DateTime createdOn
  --> BaseMember invoker optional
}
```
(in the network repository)
```
namespace org.network.test

import org.network.core.BaseAsset
import org.network.core.BaseMember

asset TestAsset extends BaseAsset {
  o String testField
}

participant TestMember extends BaseMember {
  o String testField
}

transaction TestTransaction identified by id {
  o String id
  o String invoker
}
```
(transaction logic)
```
function onTestTransaction(testTransaction) {
    var factory = getFactory();

    var asset = factory.newResource('org.network.test', 'TestAsset', 'assetfrom_' + testTransaction.id);
    Object.assign(asset, {
        createdOn: new Date(),
        invoker: factory.newRelationship('org.network.test', 'TestMember', testTransaction.invoker),
        testField: 'test',
    });

    return getAssetRegistry('org.network.test.TestAsset')
        .then(function(AR) {
            return AR.add(asset);
        });
}
```

## Expected Behavior

The new asset's `invoker` relationship should be stored as a relationship to `org.network.test.TestMember`.

## Actual Behavior

The `invoker` relationship is stored as a relationship to `org.network.core.BaseMember`. When attempting to load the referenced record via this namespace we get the unknown namespace error: `Object with ID 'Participant:org.network.core.BaseMember' in collection with ID '$sysregistries' does not exist`. It must be loaded via `org.network.test.TestMember` but there is no way of determining this from the asset data.

**Comment by dselman** [comment]
This looks like a bug to me. @sstone1 do you confirm?

**Comment by pospi** [comment]
Further info: if the relationship is setup in calling code and passed into the transaction rather than being created within the `composer-runtime` then the following error is given instead:

```
[Error: Did not find a relationship for org.network.core.BaseMember found Relationship {id=org.network.test.TestMember#some-member}]
  JSONGenerator.getRelationshipText (node_modules/composer-common/lib/serializer/jsongenerator.js:233:19)
  JSONGenerator.visitRelationshipDeclaration (node_modules/composer-common/lib/serializer/jsongenerator.js:211:41)
  JSONGenerator.visit (node_modules/composer-common/lib/serializer/jsongenerator.js:63:25)
  RelationshipDeclaration.accept (node_modules/composer-common/lib/introspect/property.js:48:24)
  JSONGenerator.visitClassDeclaration (node_modules/composer-common/lib/serializer/jsongenerator.js:92:26)
  JSONGenerator.visit (node_modules/composer-common/lib/serializer/jsongenerator.js:61:25)
  AssetDeclaration.accept (node_modules/composer-common/lib/introspect/classdeclaration.js:63:24)
  Serializer.toJSON (node_modules/composer-common/lib/serializer.js:100:26)
  Registry.add (node_modules/composer-runtime/lib/registry.js:150:38)
  AssetRegistry.add (node_modules/composer-runtime/lib/api/assetregistry.js:195:29)
  callee$1$0$ (eval at <anonymous> (node_modules/composer-runtime/lib/jstransactionexecutor.js:170:20), <anonymous>:9284:14)
  tryCatch (eval at <anonymous> (node_modules/composer-runtime/lib/jstransactionexecutor.js:170:20), <anonymous>:9356:40)
  GeneratorFunctionPrototype.invoke [as _invoke] (eval at <anonymous> (node_modules/composer-runtime/lib/jstransactionexecutor.js:170:20), <anonymous>:9630:22)
  GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (eval at <anonymous> (node_modules/composer-runtime/lib/jstransactionexecutor.js:170:20), <anonymous>:9389:21)
  c (eval at <anonymous> (node_modules/composer-runtime/lib/jstransactionexecutor.js:170:20), <anonymous>:7:40)
```

**Comment by sstone1** [comment]
In order to resolve this problem, we need to decide on a serialisation format for relationships where the target resource is a subtype of the type specified in the model. The code I removed in #469 used the format `type#id`, e.g. `org.acme.Vehicle#VIN_1234`, our fully qualified identifier. That code got removed as we had no parsing code for it, so it didn't work.

I think that serialisation format is still valid, and lends itself well to our future plans for a URI/URL scheme for resources. We could enhance it with the business network ID or custom registry ID at a later date by adding another level, e.g. `/org.vehicle.leasingnet/org.acme.Vehicle#VIN` or `/org.vehicle.leasingnet/myCarRegistry/org.acme.Vehicle#VIN`.

The code that needs changing is:
- `JSONGenerator.getRelationshipText()` in `/composer/packages/composer-common/lib/serializer/jsongenerator.js` 
We need to validate that the relationship is of a compatible type to the model before serialising the relationship, and we should only use the new format if the types are different.
- `JSONPopulator.visitRelationshipDeclaration()` in `/composer/packages/composer-common/lib/serializer/jsonpopulator.js`
We need to look for the new format here, validate that the type specified is of a compatible type to the model before instantiating the new Relationship object.

That code also has the ability to handle Resource objects in place of Relationships (acceptResourcesForRelationships and permitResourcesForRelationships) and we need the same validation code there as well.

@dselman any comments?

**Comment by dselman** [comment]
That sounds correct to me.

**Comment by dselman** [comment]
I've refactored the code and added tests. Existing instances should continue to work and can be deserialized. On serialization their relationships will be rewritten to use the new URI format.

The only breaking change is in the format of data returned by the REST API. The relationships returned will have the new URI format, rather than the old format (just an id).
