### ISSUE TITLE
As a user I can generate sample data that excludes optional properties

### ISSUE THREAD

**Issue by dselman** [hyperledger/composer#796]
## Context
When a user presses the "Generate sample data" link in the Playground the same data includes all properties, including optional properties. It would be very useful to be able to optionally exclude the sample generation on optional properties.

## Expected Behavior
User can click a checkbox or similar to generate data for optional properties. The default generation should only generate sample data for required properties.

## Actual Behavior
Sample data is generated for all properties, including optional properties.

## Possible Fix
Add a UI option to control what sample data is generated.

## Steps to Reproduce
1. Import the vehicle-lifecycle-network into Playground
2. Switch to the Vehicles asset registry
3. Create a new asset
4. Click generate sample data

## Existing issues
- [x] [Stack Overflow issues](http://stackoverflow.com/tags/fabric-composer)
- [x] [GitHub Issues](https://github.com/hyperledger/composer/issues)
- [x] [Rocket Chat history](https://chat.hyperledger.org/channel/fabric-composer)

## Context
With large models with lots of optional properties the generated sample data is very intimidating.

## Your Environment
* Version used: 0.7.0
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by sstone1** [comment]
@Tobias-Hunter we would like some designs for this as soon as possible please?
@bestbeforetoday could you take a look at the API side of things for this please?

**Comment by bestbeforetoday** [comment]
As step one, how about I change things so that generation with _empty_ property values (this is what initially appears in a New Asset dialog) only creates mandatory properties, and generation with _sample_ property values generates both mandatory and optional properties. It might makes things a bit more friendly and isn't gated in UI changes.

Additionally, I think we can improve on things like how array properties are generated. Right now we always create three entries in any array property. I always end up deleting either all or all but one of these entries. How about generation with _empty_ property values creates empty arrays and generation with _sample_ property values creates arrays with one entry.

@Tobias-Hunter What do you think?

**Comment by Tobias-Hunter** [comment]
.XD Clickthrough: https://xd.adobe.com/view/1ad897e6-0075-48c8-984f-d10f456673c8/

Questions: With fields we use commonly in models could we define these data structures? (lastName, firstName, colour etc. etc. could have list of 20 potential data properties or even better like https://www.mockaroo.com/)

Assigning to @winslet for Hi-Fi's 😛

**Comment by winslet** [comment]
Initial hifis (please use in conjunction with Toby's above UX flow)

#### Modal with form inputs of the code (not sure about implementation status of this)
![fabric composer playground define 2 copy 64](https://user-images.githubusercontent.com/13980028/27541610-748ffe1a-5a7c-11e7-9198-c0e6cc31f021.png)

#### What happens if a complex form is made due to the addition of further fields *or* if the above is not implemented this will be the default view (without the "submit as json" copy on the left side). 

If the above is implemented then the transition when the checkbox to add "optional properties" is selected will be a slide across and a fade on the text fields.

![fabric composer playground define 2 copy 66](https://user-images.githubusercontent.com/13980028/27541695-c2b2ade0-5a7c-11e7-8f37-c82782f1c604.png)

There are no new assets here, please let me know if you need a Marketch. 👍

**Comment by bestbeforetoday** [comment]
Clarification to the UX flow above:
- Checking or unchecking _Optional Properties_ will cause a fresh set of empty data to be populated (either including or omitting the optional properties depending on checkbox state), regardless of whether _Generate Random Data_ was previously clicked.

**Comment by bestbeforetoday** [comment]
Generating data appropriate to the field (e.g. First Name, Last Name, email address) is tricky as the model does not provide any context about the meaning of the field; only what data type it is (e.g. String). We could make some educated guesses based on certain typical field names, but this will be hit-and-miss depending on the names the user specifies and the language they are using.

Some more robust and/or practical solutions might be:
1. Include additional metadata in the model to provide context for fields, e.g. email, name.
2. Generate random data that satisfies whatever constraints are applied to the field content. So if a regex was applied to constrain field content to something looking like an email address then we would generate something that looks like an email address. This relies on appropriate constraints being applied to fields in the model, which in some cases may be hard, and for us to be able to generate random data that satisfies the constraints, which may be extremely difficult.

**Comment by bestbeforetoday** [comment]
# Runtime API design
## Current API
composer-common/Factory provides several newXXX functions for creating new resources. These are used to generate the empty and sample data for Playground. These functions have an `options` Object parameter that allows behaviour to be specified. Currently there is a `options.generate` String property that can have one of the following values:
- _not set_ - don't generate and field values (other than model defaults).
- **empty** - generate empty field values.
- **sample** - generate sample/random field values.

## New requirement
In addition to the above we now need to specify whether optional fields should have their values generated, only if either **empty** or **sample** is specified, but independent of which of those is selected.

## Proposed solution
Add a `options.includeOptionalFields` truthy property that controls whether optional fields are assigned values only if the `options.generate` property specified that generation should occur. This provides minimum API change, backwards compatibility, and minimal nesting of arguments within option objects by keeping all the user-selectable properties at the top level of the `options` object.

**Comment by bestbeforetoday** [comment]
Another issue raised in this discussion is that for all array fields we generate exactly three members. This is excessive. Proposal is that we generate only one array member when sample/random data is requested. For empty data, this could be:
1. None to reduce clutter; or
2. One to provide an example of array content.

Thoughts?

**Comment by dselman** [comment]
I think generating 1 value is useful, whereas generating 3 adds almost no value.

**Comment by dselman** [comment]
Can this be closed now?

**Comment by winslet** [comment]
It would be great to get a little bit of css polish on the checkbox and text styling if possible? Shouldnt take more than 5 mins 👍

**Comment by bestbeforetoday** [comment]
@winslet We don't seem to have any existing styling for checkboxes in the Playground UI. Rather than try to invent some new CSS I am going to close this issue for now, but the styling needs to be re-visited when we re-work the dialogs for the form view of resources.

**Comment by winslet** [comment]
@bestbeforetoday thanks Mark, my mistake I thought we did!
