### ISSUE TITLE
quickstart layout is difficult to read

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#804]
For the quickstart
https://hyperledger.github.io/composer/installing/quickstart.html
the procedure section is particularly difficult to read. The commands a user should execute should be placed on individual lines especially as they include the linux command line prompt of '$'.

**Comment by EdProsser** [comment]
This is a formatting issue, and an insidious one. Will tinker.

**Comment by winslet** [comment]
@EdProsser I can help you get a local build of the docs running. I put some styling changes in for our code snippets across the rest of the docs a while back, however for some reason this page has not changed. I am assuming that this is due to the markdown being slightly different? Code snippets across the rest of the site are fine it seems.

**Comment by EdProsser** [comment]
Got my local build running now thanks to @davidkel and @mbwhite will be able to iterate on this problem much more quickly.
