### ISSUE TITLE
As a user I can easily edit complex business networks in Playground

### ISSUE THREAD

**Issue by dselman** [hyperledger/composer#828]
## Context
The left-nav in the Playground does not scale to BNs with lots of files.

## Expected Behavior
Provide a more scalable UI.

## Actual Behavior
No scrollbar. File names are hard to read as right truncated. Page gets very long.

## Steps to Reproduce
1. Import the vehicle-lifecycle-demo sample into the Playground
2. Look at the left-nav
3.
4.

## Existing issues

- [ ] [Stack Overflow issues](http://stackoverflow.com/tags/fabric-composer)
- [ ] [GitHub Issues](https://github.com/hyperledger/composer/issues)
- [ ] [Rocket Chat history](https://chat.hyperledger.org/channel/fabric-composer)

## Context
The vehicle-lifecycle-network is already starting to push the boundaries of the UI scalability.

## Your Environment
* Version used: 0.7.0
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by Tobias-Hunter** [comment]
Capturing initial thoughts after talking with @EdMoffatt 
![image](https://cloud.githubusercontent.com/assets/25635381/25857842/25759292-34d2-11e7-84a3-4ac8fd27005b.png)

- We display 5 files of a certain type (model files, script files & access control files) max to the user, anymore we have a scroll within this sidebar!
- Character length is limited, however we eliminate the beginning & allow the user to see the end of the name. (Perhaps some hover state on the files that are shortened to allow the user to see the full file name?)
- When the user selects "Script Files" the "Model Files" will collapse & the "Script Files" will expand!

Full UX Click-throughs coming soon! 🎈

**Comment by Tobias-Hunter** [comment]
.XD Click-through: https://xd.adobe.com/view/038d9ea9-7ecb-41d3-ad83-61e23895a166/
.XD File on Box: https://ibm.box.com/s/8c4ovvybmzonx3s7o8p46q0yz8sw4nd6

Please see the above comment for information & any questions let me know! 🤘🏻

Assigning to @winslet for Hi-Fis

**Comment by EdMoffatt** [comment]
That latest suggestion makes a LOT more sense to me, Toby - really like it

**Comment by Tobias-Hunter** [comment]
![image](https://cloud.githubusercontent.com/assets/25635381/26444150/0b54ac32-4133-11e7-955f-324bd93448ae.png)

Additionally, if we were to have trillions of files (in terms of scalability for this) we should fix the bottom context & only scroll the file browser area with that going behind that content! 🎈

**Comment by winslet** [comment]
This should also include dependencies - see issue #697 

On the backlog for now as this will require a fair amount of work and thought and is something which could also lead into a full navigation change.

**Comment by EdMoffatt** [comment]
I think to get this one closed out, we should go for a "tactical" fix for now ;)

So long term, we'd like to totally change that navigation - the designs above are a good start on that.  However, a piece of work that size is just gonna go sit on our backlog.  Which *would* be fine, except...

...We're planning to show off the Vehicle Lifecycle network a lot, as a shining example of what you can do with Composer...  And as soon as you open this network in Playground, you get issues!  Therefore, I think we should do a smaller fix, to maintain the current behaviour of that nav panel, whilst dealing with very long lists of files.

So, here's a rather old set of designs for a smaller fix - I think these would still be relevant, and would be a good fix for us to get in for the shorter term:

[Scrollbars For Days.pdf](https://github.com/hyperledger/composer/files/1058078/Scrollbars.For.Days.pdf)

Assigning over to Catherine for consideration of who to assign!  I feel like this should probably be a reasonable priority since it impacts how good the Vehicle Lifecycle demo looks.

**Comment by nklincoln** [comment]
Adding styling to scrollbars is currently unsupported in Firefox (though is in Chrome). In order to add custom scrollbars, we will need to use a slightly more complex method. 

There are existing npm modules that enable custom scroll bars for angular, the suggestion from me is to go with ngx-perfect-scrollbar (https://www.npmjs.com/package/ngx-perfect-scrollbar) which will build within Playground webpack.

Changes incorporating the above are ready for delivery.

@markcastle3 - are there any specific checks that need to be done against the package before inclusion?
