### ISSUE TITLE
Add a "learning" section in the docs

### ISSUE THREAD

**Issue by winslet** [hyperledger/composer#846]
We should start building out the previously spoken about section in the docs called "learning".

**Comment by EdMoffatt** [comment]
This one's not top of the priority pile right now, but because we've had some recent feedback on Rocket.Chat of people struggling to know where to get started, I think we might want to start by figuring out what we want to end up with on the docs page in terms of the navigation structure.

Suggest we should perhaps look at nailing the first 3 sections (Intro, Tutorials (/Learning), Installation) as the goal of this issue?

So the goal could be "A user reading through the docs can learn what Composer is, get setup ready to use it, and find other learning materials".  I think that'd then be a good statement of where we need to be with this work by the end of our current rough plan (i.e. by the end of July)

**Comment by sstone1** [comment]
Closing as covered by the new user experience work.
