### ISSUE TITLE
Playground should keep changes if user navigates from "Define" without deploying

### ISSUE THREAD

**Issue by EdMoffatt** [hyperledger/composer#922]
NEW PLAN!

After discussion, we're going to implement this differently from my original suggestion!  Instead, the behaviour we're going to go for is that even if there are undeployed changes when the user navigates away from the Define tab (to the Test tab or ID Registry), we'll keep them there for when they come back.

Undeployed changes will only be discarded if the user goes back to the My Business Networks screen.

* * *

OLD PLAN FOR THE RECORD: 

We sorta missed this one with the initial implementation of Playground, but it's been raised on Rocket.Chat and we should absolutely go back and add it in :)

From a super-old design...  The idea was that if the user clicked to navigate off the "Define" tab without Deploying their most recent changes:

![image](https://cloud.githubusercontent.com/assets/7454304/25892248/af6f2b18-356b-11e7-9238-072d0e266073.png)

These should be styled like a standard Playground modal (e.g. see Add File as an example).
There will be 2 possible types of modal, depending on whether the network is good to deploy of not:

1. No errors in code and you haven't deployed

Modal Title: "Warning: Undeployed Changes"
Body Copy: "Your most recent changes to the Business Network Definition have not been deployed.  Deploy or discard them before leaving the editor?"
Primary Button (indigo, right): "Deploy changes"
Secondary Button (white, left): "Discard changes"

2. Errors in code

Modal Title: "Warning: Undeployed Changes"
Body Copy: "Your most recent changes to the Business Network Definition have not been deployed.  It is not possible to deploy the updates because of errors found in your code.  Stay and edit the Business Network Definition, or discard your changes and leave the editor?"
Primary Button (indigo, right): "Stay and edit"
Secondary Button (white, left): "Discard changes"

**Comment by jt-nti** [comment]
Some sort of warning when the definition has been modified since the last deployment sounds useful however I'm not 100% sure I understand the designs above. It seems like you can get stuck in the editor if there are any errors, which doesn't seem helpful. For example, would it be reasonable to want to have a look at something under the test tab to understand migration implications of in flight model changes? Similarly, I don't want to have always fix errors before looking at another model file (see related issue #1097).

I guess there are challenges to allowing the definition to remain undeployed, and potentially with errors, but I'm not keen on a choice between "Stay and edit" or "Discard changes"!

**Comment by EdMoffatt** [comment]
In the designs above, if there are errors then there are 2 options offered:

1. Stay and Fix
2. Discard changes and test

(Thinking about it, "Discard and Continue" would be better, since it's not *necessarily* the Test tab that the user is navigating away to).

So, you're not stuck, you just need to select the option that's not "Stay", and you will not be forced to stay ;)

I think it's worse to be able to go to the Test tab and not actually be testing the thing that you were looking at in the Define tab.  My preference is to remind the user to deploy before they navigate away, and if what they have is not deploy-able then to inform them of this also.

**Comment by EdMoffatt** [comment]
If you want to understand migration implications, I believe the recommended route would be to deploy to the WebBrowser connection profile for purposes of testing before you then push the same changes to your ledger.

**Comment by jt-nti** [comment]
I'm stuck if I don't want to fix all errors in one shot or discard my work :)

I guess I can test something against a different connection profile (browser, or a different fabric) and switch back to modifying the next rev of my definition (assuming I can navigate away to the connection profiles without discarding anything) but the playground doesn't really fit with that workflow either.

I'm not sure what the right solution to this is, but there are probably lots of different approaches, e.g. dirty flag on define tab, warnings, disabling actions/freezing test tab, define vs. deployed tab etc. It's probably down to personal taste but I dislike tools that force me to discard something if I don't want to. Sometimes it's unavoidable but this doesn't feel like one of those times.

**Comment by samjsmith** [comment]
I think I agree with @jt-nti on this one. If I make a big mess in a file in a network (perhaps from something like "let's just copy this out of another BNA into our BNA then fix up as needed in a minute"), then it feels wrong to force people into discarding a file because it's not valid.

I'd be tempted to look at whether a 'valid/invalid' (or clean/dirty as JT suggested) flag on each file in the BNA in the Define tab which is then used to Enable/Disable the Deploy button and Test Tab.

@EdMoffatt I can look at doing that or do you have a different preferred approach?

**Comment by samjsmith** [comment]
I've seen some inconsistent behaviour this afternoon switching between the Define and Test tabs. 

This sequence sometimes recreates the error:
1. go to playground home and click 'let's blockchain'
2. with default model loaded, click Test tab
3. click Assets -> Sample Asset -> Create New Asset button, create a new asset with a value 'foo'
4. go back to the define tab
5. add a new field to Sample asset `o String thing`
6. Click Test tab.
7. Observe error in dev console: 
```ERROR ValidationException {originalStack: "Error: Instance org.acme.sample.SampleAsset#assetI…tp://localhost:3000/polyfills.bundle.js:31785:25)", zoneAwareStack: "Error: Instance org.acme.sample.SampleAsset#assetI…tp://localhost:3000/polyfills.bundle.js:31785:25)", stack: "ValidationException: Instance org.acme.sample.Samp…tp://localhost:3000/polyfills.bundle.js:31785:25)", message: "Instance org.acme.sample.SampleAsset#assetId:1064 missing required field thing", name: "ValidationException"…}```

However sometimes it deals fine with this, however, if you then try to edit the asset that you createdin step 3 then the UI can also lock up then.

It appears to depend on when you get `@JS : ModelManager             :updateModelFile()         updateModelFile [object Object], undefined` logged in the dev console.
I think that happens regardless of whether you've clicked 'Deploy' every time the model file is succesfully validated which I don't think it right.

**Comment by EdMoffatt** [comment]
Feels like this one is definitely worth some more thought than I initially suspected :)

Sticking a design tag and my name on it - will explore the idea of this "clean/dirty/scratch" state that @jt-nti and @samjsmith have suggested!

Sam - is the behaviour you've mentioned in your last comment worth splitting out into its own issue?  That sounds more like a bug than a "missing feature" to me maybe?

**Comment by samjsmith** [comment]
I'm not at the moment Ed. I know what you mean but I think that I'd need to look into it a bit further since at the moment we update the model whenever someone's edited a file (successfully) which makes me wonder whether the simple fix is to just stop doing that and only update the model when the deploy button is clicked.  
That sounds suspiciously easy though ;) 
I'll try it anyway and if it seems to work and passes tests etc. then I'll submit it via the other related issue #1144.

**Comment by EdMoffatt** [comment]
Work on #1530 has brought this one back to our attention!  Whilst we're fixing part of the editor behaviour, we may as well make an initial decision on this issue also - that way we can gather community feedback on the whole set of improvements in one go!

The weight of opinion seems to be in favour of *keeping* any undeployed updates in the Define view even if the user navigates away from that view and back.

I'm happy to decide that we go with that first!  I shall update the description of this issue to say what we'll actually be doing to address it, but keep the full discussion here for the community's reference!

**Comment by caroline-church** [comment]
closing as this has been done. If the behaviour that was implemented is not desirable then feel free to reopen and we can have another discussion
